var issafari=!1,ua=navigator.userAgent.toLowerCase();-1!=ua.indexOf("safari")&&0>ua.indexOf("chrome")&&(issafari=!0);
var g_last_blob_url,DEFAULT_URL="",DEFAULT_SCALE="auto",DEFAULT_SCALE_DELTA=1.1,UNKNOWN_SCALE=0,DEFAULT_CACHE_SIZE=10,CSS_UNITS=96/72,SCROLLBAR_PADDING=40,VERTICAL_PADDING=5,MAX_AUTO_SCALE=1.25,MIN_SCALE=.25,MAX_SCALE=10,VIEW_HISTORY_MEMORY=20,SCALE_SELECT_CONTAINER_PADDING=8,SCALE_SELECT_PADDING=22,THUMBNAIL_SCROLL_MARGIN=-19,CLEANUP_TIMEOUT=3E4,IGNORE_CURRENT_POSITION_ON_ZOOM=!1,RenderingStates={INITIAL:0,RUNNING:1,PAUSED:2,FINISHED:3},FindStates={FIND_FOUND:0,FIND_NOTFOUND:1,FIND_WRAPPED:2,FIND_PENDING:3};
PDFJS.imageResourcesPath="./images/";PDFJS.workerSrc="http://mozilla.github.io/pdf.js/build/pdf.worker.js";PDFJS.cMapUrl="../web/cmaps/";PDFJS.cMapPacked=!0;
var mozL10n=document.mozL10n||document.webL10n,CustomStyle=function(){function a(){}var b=["ms","Moz","Webkit","O"],c={};a.getProp=function(a,e){if(1===arguments.length&&"string"===typeof c[a])return c[a];e=e||document.documentElement;var f=e.style,g,h;if("string"===typeof f[a])return c[a]=a;h=a.charAt(0).toUpperCase()+a.slice(1);for(var k=0,l=b.length;k<l;k++)if(g=b[k]+h,"string"===typeof f[g])return c[a]=g;return c[a]="undefined"};a.setProp=function(a,b,c){a=this.getProp(a);"undefined"!==a&&(b.style[a]=
c)};return a}();function getFileName(a){var b=a.indexOf("#"),c=a.indexOf("?"),b=Math.min(0<b?b:a.length,0<c?c:a.length);return a.substring(a.lastIndexOf("/",b)+1,b)}function getOutputScale(a){a=(window.devicePixelRatio||1)/(a.webkitBackingStorePixelRatio||a.mozBackingStorePixelRatio||a.msBackingStorePixelRatio||a.oBackingStorePixelRatio||a.backingStorePixelRatio||1);return{sx:a,sy:a,scaled:1!==a}}
function scrollIntoView(a,b){var c=a.offsetParent,d=a.offsetTop+a.clientTop,e=a.offsetLeft+a.clientLeft;if(c){for(;c.clientHeight===c.scrollHeight;)if(c.dataset._scaleY&&(d/=c.dataset._scaleY,e/=c.dataset._scaleX),d+=c.offsetTop,e+=c.offsetLeft,c=c.offsetParent,!c)return;b&&(void 0!==b.top&&(d+=b.top),void 0!==b.left&&(e+=b.left,c.scrollLeft=e,document.body&&(document.body.scrollLeft=0)));c.scrollTop=d;document.body&&(document.body.scrollTop=0)}else console.error("offsetParent is not set -- cannot scroll")}
function noContextMenuHandler(a){a.preventDefault()}function getPDFFileNameFromURL(a){var b=/[^\/?#=]+\.pdf\b(?!.*\.pdf\b)/i;a=/^(?:([^:]+:)?\/\/[^\/]+)?([^?#]*)(\?[^#]*)?(#.*)?$/.exec(a);if(a=b.exec(a[1])||b.exec(a[2])||b.exec(a[3]))if(a=a[0],-1!==a.indexOf("%"))try{a=b.exec(decodeURIComponent(a))[0]}catch(c){}return a||"document.pdf"}
var ProgressBar=function(){function a(a,c){this.div=document.querySelector(a+" .progress");this.bar=this.div.parentNode;this.height=c.height||100;this.width=c.width||100;this.units=c.units||"%";this.div.style.height=this.height+this.units;this.percent=0}a.prototype={updateBar:function(){this._indeterminate?(this.div.classList.add("indeterminate"),this.div.style.width=this.width+this.units):(this.div.classList.remove("indeterminate"),this.div.style.width=this.width*this._percent/100+this.units)},get percent(){return this._percent},
set percent(a){this._indeterminate=isNaN(a);this._percent=Math.min(Math.max(a,0),100);this.updateBar()},setWidth:function(a){a&&(a=a.parentNode.offsetWidth-a.offsetWidth,0<a&&this.bar.setAttribute("style","width: calc(100% - "+a+"px);"))},hide:function(){this.bar.classList.add("hidden");this.bar.removeAttribute("style")}};return a}(),Cache=function(a){var b=[];this.push=function(c){var d=b.indexOf(c);0<=d&&b.splice(d,1);b.push(c);b.length>a&&b.shift().destroy()};this.resize=function(c){for(a=c;b.length>
a;)b.shift().destroy()}},DEFAULT_PREFERENCES={showPreviousViewOnLoad:!0,defaultZoomValue:"",sidebarViewOnLoad:0,enableHandToolOnLoad:!1,enableWebGL:!1,disableRange:!1,disableAutoFetch:!1,disableFontFace:!1,disableTextLayer:!1,useOnlyCssZoom:!1},SidebarView={NONE:0,THUMBS:1,OUTLINE:2,ATTACHMENTS:3},Preferences={prefs:Object.create(DEFAULT_PREFERENCES),isInitializedPromiseResolved:!1,initializedPromise:null,initialize:function(){return this.initializedPromise=this._readFromStorage(DEFAULT_PREFERENCES).then(function(a){this.isInitializedPromiseResolved=
!0;a&&(this.prefs=a)}.bind(this))},reset:function(){return this.initializedPromise.then(function(){this.prefs=Object.create(DEFAULT_PREFERENCES);return this._writeToStorage(DEFAULT_PREFERENCES)}.bind(this))},reload:function(){return this.initializedPromise.then(function(){this._readFromStorage(DEFAULT_PREFERENCES).then(function(a){a&&(this.prefs=a)}.bind(this))}.bind(this))},set:function(a,b){return this.initializedPromise.then(function(){if(void 0===DEFAULT_PREFERENCES[a])throw Error("preferencesSet: '"+
a+"' is undefined.");if(void 0===b)throw Error("preferencesSet: no value is specified.");var c=typeof b,d=typeof DEFAULT_PREFERENCES[a];if(c!==d)if("number"===c&&"string"===d)b=b.toString();else throw Error("Preferences_set: '"+b+"' is a \""+c+'", expected "'+d+'".');else if("number"===c&&(b|0)!==b)throw Error("Preferences_set: '"+b+'\' must be an "integer".');this.prefs[a]=b;return this._writeToStorage(this.prefs)}.bind(this))},get:function(a){return this.initializedPromise.then(function(){var b=
DEFAULT_PREFERENCES[a];if(void 0===b)throw Error("preferencesGet: '"+a+"' is undefined.");var c=this.prefs[a];return void 0!==c?c:b}.bind(this))},_writeToStorage:function(a){return new Promise(function(b){localStorage.setItem("pdfjs.preferences",JSON.stringify(a));b()})},_readFromStorage:function(a){return new Promise(function(a){var c=JSON.parse(localStorage.getItem("pdfjs.preferences"));a(c)})}};
(function(){function a(a){var b=document.createEvent("CustomEvent");b.initCustomEvent(a,!1,!1,"custom");window.dispatchEvent(b)}function b(){if(e)if(d(),++f<e.length){var a=e[f];"function"===typeof a.mozPrintCallback?a.mozPrintCallback({context:a.getContext("2d"),abort:c,done:b}):b()}else d(),g.call(window),setTimeout(c,20)}function c(){e&&(e=null,d(),a("afterprint"))}function d(){var a=document.getElementById("mozPrintCallback-shim");if(e){var b=Math.round(100*f/e.length),d=a.querySelector("progress"),
g=a.querySelector(".relative-progress");d.value=b;g.textContent=b+"%";a.removeAttribute("hidden");a.onclick=c}else a.setAttribute("hidden","")}if(!("mozPrintCallback"in document.createElement("canvas"))){HTMLCanvasElement.prototype.mozPrintCallback=void 0;var e,f,g=window.print;window.print=function(){if(e)console.warn("Ignored window.print() because of a pending print job.");else try{a("beforeprint")}finally{e=document.querySelectorAll("canvas"),f=-1,b()}};var h=!!document.attachEvent;window.addEventListener("keydown",
function(a){80!==a.keyCode||!a.ctrlKey&&!a.metaKey||a.altKey||a.shiftKey&&!window.chrome&&!window.opera?27===a.keyCode&&e&&c():(window.print(),h||(a.preventDefault(),a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation()))},!0);h&&document.attachEvent("onkeydown",function(a){a=a||window.event;if(80===a.keyCode&&a.ctrlKey)return a.keyCode=0,!1});if("onbeforeprint"in window){var k=function(a){"custom"!==a.detail&&a.stopImmediatePropagation&&a.stopImmediatePropagation()};window.addEventListener("beforeprint",
k,!1);window.addEventListener("afterprint",k,!1)}}})();
var DownloadManager=function(){function a(a,b){var e=document.createElement("a");e.click?(e.href=a,e.target="_parent","download"in e&&(e.download=b),(document.body||document.documentElement).appendChild(e),e.click(),e.parentNode.removeChild(e)):(window.top===window&&a.split("#")[0]===window.location.href.split("#")[0]&&(e=-1===a.indexOf("?")?"?":"&",a=a.replace(/#|$/,e+"$&")),window.open(a,"_parent"))}function b(){}b.prototype={downloadUrl:function(b,d){PDFJS.isValidUrl(b,!0)&&a(b+"#pdfjs.action=download",
d)},downloadData:function(b,d,e){if(navigator.msSaveBlob)return navigator.msSaveBlob(new Blob([b],{type:e}),d);b=PDFJS.createObjectURL(b,e);a(b,d)},download:function(b,d,e){URL?navigator.msSaveBlob?navigator.msSaveBlob(b,e)||this.downloadUrl(d,e):(b=URL.createObjectURL(b),a(b,e)):this.downloadUrl(d,e)}};return b}(),cache=new Cache(DEFAULT_CACHE_SIZE),currentPageNumber=1,ViewHistory=function(){function a(a){this.fingerprint=a;this.isInitializedPromiseResolved=!1;this.initializedPromise=this._readFromStorage().then(function(a){this.isInitializedPromiseResolved=
!0;a=JSON.parse(a||"{}");"files"in a||(a.files=[]);a.files.length>=VIEW_HISTORY_MEMORY&&a.files.shift();for(var b,e=0,f=a.files.length;e<f;e++)if(a.files[e].fingerprint===this.fingerprint){b=e;break}"number"!==typeof b&&(b=a.files.push({fingerprint:this.fingerprint})-1);this.file=a.files[b];this.database=a}.bind(this))}a.prototype={_writeToStorage:function(){return new Promise(function(a){var c=JSON.stringify(this.database);localStorage.setItem("database",c);a()}.bind(this))},_readFromStorage:function(){return new Promise(function(a){a(localStorage.getItem("database"))})},
set:function(a,c){if(this.isInitializedPromiseResolved)return this.file[a]=c,this._writeToStorage()},setMultiple:function(a){if(this.isInitializedPromiseResolved){for(var c in a)this.file[c]=a[c];return this._writeToStorage()}},get:function(a,c){return this.isInitializedPromiseResolved?this.file[a]||c:c}};return a}(),PDFFindBar=function(){function a(a){this.opened=!1;this.bar=a.bar||null;this.toggleButton=a.toggleButton||null;this.findField=a.findField||null;this.highlightAll=a.highlightAllCheckbox||
null;this.caseSensitive=a.caseSensitiveCheckbox||null;this.findMsg=a.findMsg||null;this.findStatusIcon=a.findStatusIcon||null;this.findPreviousButton=a.findPreviousButton||null;this.findNextButton=a.findNextButton||null;this.findController=a.findController||null;if(null===this.findController)throw Error("PDFFindBar cannot be used without a PDFFindController instance.");var c=this;this.toggleButton.addEventListener("click",function(){c.toggle()});this.findField.addEventListener("input",function(){c.dispatchEvent("")});
this.bar.addEventListener("keydown",function(a){switch(a.keyCode){case 13:a.target===c.findField&&c.dispatchEvent("again",a.shiftKey);break;case 27:c.close()}});this.findPreviousButton.addEventListener("click",function(){c.dispatchEvent("again",!0)});this.findNextButton.addEventListener("click",function(){c.dispatchEvent("again",!1)});this.highlightAll.addEventListener("click",function(){c.dispatchEvent("highlightallchange")});this.caseSensitive.addEventListener("click",function(){c.dispatchEvent("casesensitivitychange")})}
a.prototype={dispatchEvent:function(a,c){var d=document.createEvent("CustomEvent");d.initCustomEvent("find"+a,!0,!0,{query:this.findField.value,caseSensitive:this.caseSensitive.checked,highlightAll:this.highlightAll.checked,findPrevious:c});return window.dispatchEvent(d)},updateUIState:function(a,c){var d=!1,e="",f="";switch(a){case FindStates.FIND_PENDING:f="pending";break;case FindStates.FIND_NOTFOUND:e=mozL10n.get("find_not_found",null,"Phrase not found");d=!0;break;case FindStates.FIND_WRAPPED:e=
c?mozL10n.get("find_reached_top",null,"Reached top of document, continued from bottom"):mozL10n.get("find_reached_bottom",null,"Reached end of document, continued from top")}d?this.findField.classList.add("notFound"):this.findField.classList.remove("notFound");this.findField.setAttribute("data-status",f);this.findMsg.textContent=e},open:function(){this.opened||(this.opened=!0,this.toggleButton.classList.add("toggled"),this.bar.classList.remove("hidden"));this.findField.select();this.findField.focus()},
close:function(){this.opened&&(this.opened=!1,this.toggleButton.classList.remove("toggled"),this.bar.classList.add("hidden"),this.findController.active=!1)},toggle:function(){this.opened?this.close():this.open()}};return a}(),PDFFindController=function(){function a(a){this.startedTextExtraction=!1;this.extractTextPromises=[];this.pendingFindMatches={};this.active=!1;this.pageContents=[];this.pageMatches=[];this.selected={pageIdx:-1,matchIdx:-1};this.offset={pageIdx:null,matchIdx:null};this.state=
this.resumePageIdx=null;this.dirtyMatch=!1;this.findTimeout=null;this.pdfPageSource=a.pdfPageSource||null;this.integratedFind=a.integratedFind||!1;this.charactersToNormalize={"\u2018":"'","\u2019":"'","\u201a":"'","\u201b":"'","\u201c":'"',"\u201d":'"',"\u201e":'"',"\u201f":'"',"\u00bc":"1/4","\u00bd":"1/2","\u00be":"3/4"};this.findBar=a.findBar||null;a=Object.keys(this.charactersToNormalize).join("");this.normalizationRegex=new RegExp("["+a+"]","g");a=["find","findagain","findhighlightallchange",
"findcasesensitivitychange"];this.firstPagePromise=new Promise(function(a){this.resolveFirstPage=a}.bind(this));this.handleEvent=this.handleEvent.bind(this);for(var c=0,d=a.length;c<d;c++)window.addEventListener(a[c],this.handleEvent)}a.prototype={setFindBar:function(a){this.findBar=a},reset:function(){this.startedTextExtraction=!1;this.extractTextPromises=[];this.active=!1},normalize:function(a){var c=this;return a.replace(this.normalizationRegex,function(a){return c.charactersToNormalize[a]})},
calcFindMatch:function(a){var c=this.normalize(this.pageContents[a]),d=this.normalize(this.state.query),e=this.state.caseSensitive,f=d.length;if(0!==f){e||(c=c.toLowerCase(),d=d.toLowerCase());for(var e=[],g=-f;;){g=c.indexOf(d,g+f);if(-1===g)break;e.push(g)}this.pageMatches[a]=e;this.updatePage(a);this.resumePageIdx===a&&(this.resumePageIdx=null,this.nextPageMatch())}},extractText:function(){function a(d){f.pdfPageSource.pages[d].getTextContent().then(function(e){e=e.items;for(var k=[],l=0,n=e.length;l<
n;l++)k.push(e[l].str);f.pageContents.push(k.join(""));c[d](d);d+1<f.pdfPageSource.pages.length&&a(d+1)})}if(!this.startedTextExtraction){this.startedTextExtraction=!0;this.pageContents=[];for(var c=[],d=this.pdfPageSource.pdfDocument.numPages,e=0;e<d;e++)this.extractTextPromises.push(new Promise(function(a){c.push(a)}));var f=this;a(0)}},handleEvent:function(a){if(null===this.state||"findagain"!==a.type)this.dirtyMatch=!0;this.state=a.detail;this.updateUIState(FindStates.FIND_PENDING);this.firstPagePromise.then(function(){this.extractText();
clearTimeout(this.findTimeout);"find"===a.type?this.findTimeout=setTimeout(this.nextMatch.bind(this),250):this.nextMatch()}.bind(this))},updatePage:function(a){var c=this.pdfPageSource.pages[a];this.selected.pageIdx===a&&c.scrollIntoView();c.textLayer&&c.textLayer.updateMatches()},nextMatch:function(){var a=this.state.findPrevious,c=this.pdfPageSource.page-1,d=this.pdfPageSource.pages.length;this.active=!0;if(this.dirtyMatch){this.dirtyMatch=!1;this.selected.pageIdx=this.selected.matchIdx=-1;this.offset.pageIdx=
c;this.offset.matchIdx=null;this.hadMatch=!1;this.resumePageIdx=null;this.pageMatches=[];for(var e=this,c=0;c<d;c++)this.updatePage(c),c in this.pendingFindMatches||(this.pendingFindMatches[c]=!0,this.extractTextPromises[c].then(function(a){delete e.pendingFindMatches[a];e.calcFindMatch(a)}))}if(""===this.state.query)this.updateUIState(FindStates.FIND_FOUND);else if(!this.resumePageIdx){d=this.offset;if(null!==d.matchIdx){c=this.pageMatches[d.pageIdx].length;if(!a&&d.matchIdx+1<c||a&&0<d.matchIdx){this.hadMatch=
!0;d.matchIdx=a?d.matchIdx-1:d.matchIdx+1;this.updateMatch(!0);return}this.advanceOffsetPage(a)}this.nextPageMatch()}},matchesReady:function(a){var c=this.offset;a=a.length;var d=this.state.findPrevious;if(a)return this.hadMatch=!0,c.matchIdx=d?a-1:0,this.updateMatch(!0),!0;this.advanceOffsetPage(d);return c.wrapped&&(c.matchIdx=null,!this.hadMatch)?(this.updateMatch(!1),!0):!1},nextPageMatch:function(){null!==this.resumePageIdx&&console.error("There can only be one pending page.");do{var a=this.offset.pageIdx,
c=this.pageMatches[a];if(!c){this.resumePageIdx=a;break}}while(!this.matchesReady(c))},advanceOffsetPage:function(a){var c=this.offset,d=this.extractTextPromises.length;c.pageIdx=a?c.pageIdx-1:c.pageIdx+1;c.matchIdx=null;if(c.pageIdx>=d||0>c.pageIdx)c.pageIdx=a?d-1:0,c.wrapped=!0},updateMatch:function(a){var c=FindStates.FIND_NOTFOUND,d=this.offset.wrapped;this.offset.wrapped=!1;a&&(a=this.selected.pageIdx,this.selected.pageIdx=this.offset.pageIdx,this.selected.matchIdx=this.offset.matchIdx,c=d?FindStates.FIND_WRAPPED:
FindStates.FIND_FOUND,-1!==a&&a!==this.selected.pageIdx&&this.updatePage(a));this.updateUIState(c,this.state.findPrevious);-1!==this.selected.pageIdx&&this.updatePage(this.selected.pageIdx,!0)},updateUIState:function(a,c){if(this.integratedFind)FirefoxCom.request("updateFindControlState",{result:a,findPrevious:c});else{if(null===this.findBar)throw Error("PDFFindController is not initialized with a PDFFindBar instance.");this.findBar.updateUIState(a,c)}}};return a}(),PDFHistory={initialized:!1,initialDestination:null,
initialize:function(a){function b(){var a=c._getPreviousParams(null,!0);a&&(c._pushToHistory(a,!1,!c.current.dest&&c.current.hash!==c.previousHash),c._updatePreviousBookmark());window.removeEventListener("beforeunload",b,!1)}if(!PDFJS.disableHistory&&!PDFView.isViewerEmbedded){this.initialized=!0;this.reInitialized=!1;this.historyUnlocked=this.allowHashChange=!0;this.previousHash=window.location.hash.substring(1);this.currentBookmark="";this.currentPage=0;this.updatePreviousBookmark=!1;this.previousBookmark=
"";this.previousPage=0;this.nextHashParam="";this.fingerprint=a;this.currentUid=this.uid=0;this.current={};a=window.history.state;this._isStateObjectDefined(a)?(a.target.dest?this.initialDestination=a.target.dest:PDFView.initialBookmark=a.target.hash,this.currentUid=a.uid,this.uid=a.uid+1,this.current=a.target):(a&&a.fingerprint&&this.fingerprint!==a.fingerprint&&(this.reInitialized=!0),this._pushOrReplaceState({fingerprint:this.fingerprint},!0));var c=this;window.addEventListener("popstate",function(a){a.preventDefault();
a.stopPropagation();c.historyUnlocked&&(a.state?c._goTo(a.state):(c.previousHash=window.location.hash.substring(1),0===c.uid&&(a=c.previousHash&&c.currentBookmark&&c.previousHash!==c.currentBookmark?{hash:c.currentBookmark,page:c.currentPage}:{page:1},c.historyUnlocked=!1,c.allowHashChange=!1,window.history.back(),c._pushToHistory(a,!1,!0),window.history.forward(),c.historyUnlocked=!0),c._pushToHistory({hash:c.previousHash},!1,!0),c._updatePreviousBookmark()))},!1);window.addEventListener("beforeunload",
b,!1);window.addEventListener("pageshow",function(a){window.addEventListener("beforeunload",b,!1)},!1)}},_isStateObjectDefined:function(a){return a&&0<=a.uid&&a.fingerprint&&this.fingerprint===a.fingerprint&&a.target&&a.target.hash?!0:!1},_pushOrReplaceState:function(a,b){b?window.history.replaceState(a,"",document.URL):window.history.pushState(a,"",document.URL)},get isHashChangeUnlocked(){if(!this.initialized)return!0;var a=this.allowHashChange;this.allowHashChange=!0;return a},_updatePreviousBookmark:function(){this.updatePreviousBookmark&&
this.currentBookmark&&this.currentPage&&(this.previousBookmark=this.currentBookmark,this.previousPage=this.currentPage,this.updatePreviousBookmark=!1)},updateCurrentBookmark:function(a,b){this.initialized&&(this.currentBookmark=a.substring(1),this.currentPage=b|0,this._updatePreviousBookmark())},updateNextHashParam:function(a){this.initialized&&(this.nextHashParam=a)},push:function(a,b){if(this.initialized&&this.historyUnlocked)if(a.dest&&!a.hash&&(a.hash=this.current.hash&&this.current.dest&&this.current.dest===
a.dest?this.current.hash:PDFView.getDestinationHash(a.dest).split("#")[1]),a.page&&(a.page|=0),b){var c=window.history.state.target;c||(this._pushToHistory(a,!1),this.previousHash=window.location.hash.substring(1));this.updatePreviousBookmark=this.nextHashParam?!1:!0;c&&this._updatePreviousBookmark()}else{if(this.nextHashParam){if(this.nextHashParam===a.hash){this.nextHashParam=null;this.updatePreviousBookmark=!0;return}this.nextHashParam=null}a.hash?this.current.hash?this.current.hash!==a.hash?this._pushToHistory(a,
!0):(!this.current.page&&a.page&&this._pushToHistory(a,!1,!0),this.updatePreviousBookmark=!0):this._pushToHistory(a,!0):this.current.page&&a.page&&this.current.page!==a.page&&this._pushToHistory(a,!0)}},_getPreviousParams:function(a,b){if(!this.currentBookmark||!this.currentPage)return null;this.updatePreviousBookmark&&(this.updatePreviousBookmark=!1);if(0<this.uid&&(!this.previousBookmark||!this.previousPage))return null;if(!this.current.dest&&!a||b){if(this.previousBookmark===this.currentBookmark)return null}else if(this.current.page||
a){if(this.previousPage===this.currentPage)return null}else return null;var c={hash:this.currentBookmark,page:this.currentPage};PresentationMode.active&&(c.hash=null);return c},_stateObj:function(a){return{fingerprint:this.fingerprint,uid:this.uid,target:a}},_pushToHistory:function(a,b,c){this.initialized&&(!a.hash&&a.page&&(a.hash="page="+a.page),b&&!c&&(b=this._getPreviousParams())&&this._pushToHistory(b,!1,!this.current.dest&&this.current.hash!==this.previousHash),this._pushOrReplaceState(this._stateObj(a),
c||0===this.uid),this.currentUid=this.uid++,this.current=a,this.updatePreviousBookmark=!0)},_goTo:function(a){if(this.initialized&&this.historyUnlocked&&this._isStateObjectDefined(a)){if(!this.reInitialized&&a.uid<this.currentUid){var b=this._getPreviousParams(!0);if(b){this._pushToHistory(this.current,!1);this._pushToHistory(b,!1);this.currentUid=a.uid;window.history.back();return}}this.historyUnlocked=!1;a.target.dest?PDFView.navigateTo(a.target.dest):PDFView.setHash(a.target.hash);this.currentUid=
a.uid;a.uid>this.uid&&(this.uid=a.uid);this.current=a.target;this.updatePreviousBookmark=!0;a=window.location.hash.substring(1);this.previousHash!==a&&(this.allowHashChange=!1);this.previousHash=a;this.historyUnlocked=!0}},back:function(){this.go(-1)},forward:function(){this.go(1)},go:function(a){if(this.initialized&&this.historyUnlocked){var b=window.history.state;-1===a&&b&&0<b.uid?window.history.back():1===a&&b&&b.uid<this.uid-1&&window.history.forward()}}},SecondaryToolbar={opened:!1,previousContainerHeight:null,
newContainerHeight:null,initialize:function(a){this.toolbar=a.toolbar;this.presentationMode=a.presentationMode;this.documentProperties=a.documentProperties;this.buttonContainer=this.toolbar.firstElementChild;this.toggleButton=a.toggleButton;this.presentationModeButton=a.presentationModeButton;this.openFile=a.openFile;this.print=a.print;this.download=a.download;this.viewBookmark=a.viewBookmark;this.firstPage=a.firstPage;this.lastPage=a.lastPage;this.pageRotateCw=a.pageRotateCw;this.pageRotateCcw=a.pageRotateCcw;
this.documentPropertiesButton=a.documentPropertiesButton;a=[{element:this.toggleButton,handler:this.toggle},{element:this.presentationModeButton,handler:this.presentationModeClick},{element:this.openFile,handler:this.openFileClick},{element:this.print,handler:this.printClick},{element:this.download,handler:this.downloadClick},{element:this.viewBookmark,handler:this.viewBookmarkClick},{element:this.firstPage,handler:this.firstPageClick},{element:this.lastPage,handler:this.lastPageClick},{element:this.pageRotateCw,
handler:this.pageRotateCwClick},{element:this.pageRotateCcw,handler:this.pageRotateCcwClick},{element:this.documentPropertiesButton,handler:this.documentPropertiesClick}];for(var b in a){var c=a[b].element;c&&c.addEventListener("click",a[b].handler.bind(this))}},presentationModeClick:function(a){this.presentationMode.request();this.close()},openFileClick:function(a){document.getElementById("fileInput").click();this.close()},printClick:function(a){window.print();this.close()},downloadClick:function(a){PDFView.download();
this.close()},viewBookmarkClick:function(a){this.close()},firstPageClick:function(a){PDFView.page=1;this.close()},lastPageClick:function(a){PDFView.pdfDocument&&(PDFView.page=PDFView.pdfDocument.numPages);this.close()},pageRotateCwClick:function(a){PDFView.rotatePages(90)},pageRotateCcwClick:function(a){PDFView.rotatePages(-90)},documentPropertiesClick:function(a){this.documentProperties.open();this.close()},setMaxHeight:function(a){a&&this.buttonContainer&&(this.newContainerHeight=a.clientHeight,
this.previousContainerHeight!==this.newContainerHeight&&(this.buttonContainer.setAttribute("style","max-height: "+(this.newContainerHeight-SCROLLBAR_PADDING)+"px;"),this.previousContainerHeight=this.newContainerHeight))},open:function(){this.opened||(this.opened=!0,this.toggleButton.classList.add("toggled"),this.toolbar.classList.remove("hidden"))},close:function(a){!this.opened||a&&!this.toolbar.contains(a)||(this.opened=!1,this.toolbar.classList.add("hidden"),this.toggleButton.classList.remove("toggled"))},
toggle:function(){this.opened?this.close():this.open()}},DELAY_BEFORE_HIDING_CONTROLS=3E3,SELECTOR="presentationControls",DELAY_BEFORE_RESETTING_SWITCH_IN_PROGRESS=1E3,PresentationMode={active:!1,args:null,contextMenuOpen:!1,prevCoords:{x:null,y:null},initialize:function(a){this.container=a.container;this.secondaryToolbar=a.secondaryToolbar;this.viewer=this.container.firstElementChild;this.firstPage=a.firstPage;this.lastPage=a.lastPage;this.pageRotateCw=a.pageRotateCw;this.pageRotateCcw=a.pageRotateCcw;
this.firstPage.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.firstPageClick()}.bind(this));this.lastPage.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.lastPageClick()}.bind(this));this.pageRotateCw.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.pageRotateCwClick()}.bind(this));this.pageRotateCcw.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.pageRotateCcwClick()}.bind(this))},
get isFullscreen(){return document.fullscreenElement||document.mozFullScreen||document.webkitIsFullScreen||document.msFullscreenElement},_setSwitchInProgress:function(){this.switchInProgress&&clearTimeout(this.switchInProgress);this.switchInProgress=setTimeout(function(){delete this.switchInProgress}.bind(this),DELAY_BEFORE_RESETTING_SWITCH_IN_PROGRESS);PDFView.currentPosition=null},_resetSwitchInProgress:function(){this.switchInProgress&&(clearTimeout(this.switchInProgress),delete this.switchInProgress)},
request:function(){if(!PDFView.supportsFullscreen||this.isFullscreen||!this.viewer.hasChildNodes())return!1;this._setSwitchInProgress();if(this.container.requestFullscreen)this.container.requestFullscreen();else if(this.container.mozRequestFullScreen)this.container.mozRequestFullScreen();else if(this.container.webkitRequestFullScreen)this.container.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);else if(this.container.msRequestFullscreen)this.container.msRequestFullscreen();else return!1;this.args=
{page:PDFView.page,previousScale:PDFView.currentScaleValue};return!0},enter:function(){this.active=!0;this._resetSwitchInProgress();setTimeout(function(){PDFView.page=this.args.page;PDFView.setScale("page-fit",!0)}.bind(this),0);window.addEventListener("mousemove",this.mouseMove,!1);window.addEventListener("mousedown",this.mouseDown,!1);window.addEventListener("contextmenu",this.contextMenu,!1);this.showControls();HandTool.enterPresentationMode();this.contextMenuOpen=!1;this.container.setAttribute("contextmenu",
"viewerContextMenu")},exit:function(){var a=PDFView.page;setTimeout(function(){this.active=!1;PDFView.setScale(this.args.previousScale);PDFView.page=a;this.args=null}.bind(this),0);window.removeEventListener("mousemove",this.mouseMove,!1);window.removeEventListener("mousedown",this.mouseDown,!1);window.removeEventListener("contextmenu",this.contextMenu,!1);this.hideControls();PDFView.clearMouseScrollState();HandTool.exitPresentationMode();this.container.removeAttribute("contextmenu");this.contextMenuOpen=
!1;scrollIntoView(document.getElementById("thumbnailContainer"+a))},showControls:function(){this.controlsTimeout?clearTimeout(this.controlsTimeout):this.container.classList.add(SELECTOR);this.controlsTimeout=setTimeout(function(){this.container.classList.remove(SELECTOR);delete this.controlsTimeout}.bind(this),DELAY_BEFORE_HIDING_CONTROLS)},hideControls:function(){this.controlsTimeout&&(this.container.classList.remove(SELECTOR),clearTimeout(this.controlsTimeout),delete this.controlsTimeout)},mouseMove:function(a){a=
{x:a.clientX,y:a.clientY};var b=PresentationMode.prevCoords;PresentationMode.prevCoords=a;a.x===b.x&&a.y===b.y||PresentationMode.showControls()},mouseDown:function(a){var b=PresentationMode;b.contextMenuOpen?(b.contextMenuOpen=!1,a.preventDefault()):0!==a.button||a.target.href&&a.target.classList.contains("internalLink")||(a.preventDefault(),PDFView.page+=a.shiftKey?-1:1)},contextMenu:function(a){PresentationMode.contextMenuOpen=!0}};
(function(){function a(a){PresentationMode.isFullscreen?PresentationMode.enter():PresentationMode.exit()}window.addEventListener("fullscreenchange",a,!1);window.addEventListener("mozfullscreenchange",a,!1);window.addEventListener("webkitfullscreenchange",a,!1);window.addEventListener("MSFullscreenChange",a,!1)})();"use strict";
var GrabToPan=function(){function a(a){this.element=a.element;this.document=a.element.ownerDocument;"function"===typeof a.ignoreTarget&&(this.ignoreTarget=a.ignoreTarget);this.onActiveChanged=a.onActiveChanged;this.activate=this.activate.bind(this);this.deactivate=this.deactivate.bind(this);this.toggle=this.toggle.bind(this);this._onmousedown=this._onmousedown.bind(this);this._onmousemove=this._onmousemove.bind(this);this._endPan=this._endPan.bind(this);(this.overlay=document.createElement("div")).className=
"grab-to-pan-grabbing"}a.prototype={CSS_CLASS_GRAB:"grab-to-pan-grab",activate:function(){if(!this.active&&(this.active=!0,this.element.addEventListener("mousedown",this._onmousedown,!0),this.element.classList.add(this.CSS_CLASS_GRAB),this.onActiveChanged))this.onActiveChanged(!0)},deactivate:function(){if(this.active&&(this.active=!1,this.element.removeEventListener("mousedown",this._onmousedown,!0),this._endPan(),this.element.classList.remove(this.CSS_CLASS_GRAB),this.onActiveChanged))this.onActiveChanged(!1)},
toggle:function(){this.active?this.deactivate():this.activate()},ignoreTarget:function(a){return a[b]("a[href], a[href] *, input, textarea, button, button *, select, option")},_onmousedown:function(a){if(0===a.button&&!this.ignoreTarget(a.target)){if(a.originalTarget)try{a.originalTarget.tagName}catch(b){return}this.scrollLeftStart=this.element.scrollLeft;this.scrollTopStart=this.element.scrollTop;this.clientXStart=a.clientX;this.clientYStart=a.clientY;this.document.addEventListener("mousemove",this._onmousemove,
!0);this.document.addEventListener("mouseup",this._endPan,!0);this.element.addEventListener("scroll",this._endPan,!0);a.preventDefault();a.stopPropagation();this.document.documentElement.classList.add(this.CSS_CLASS_GRABBING)}},_onmousemove:function(a){this.element.removeEventListener("scroll",this._endPan,!0);var b;b="buttons"in a&&c?!(a.buttons|1):e||f?0===a.which:void 0;b?this._endPan():(b=a.clientX-this.clientXStart,this.element.scrollTop=this.scrollTopStart-(a.clientY-this.clientYStart),this.element.scrollLeft=
this.scrollLeftStart-b,this.overlay.parentNode||document.body.appendChild(this.overlay))},_endPan:function(){this.element.removeEventListener("scroll",this._endPan,!0);this.document.removeEventListener("mousemove",this._onmousemove,!0);this.document.removeEventListener("mouseup",this._endPan,!0);this.overlay.parentNode&&this.overlay.parentNode.removeChild(this.overlay)}};var b;["webkitM","mozM","msM","oM","m"].some(function(a){a+="atches";a in document.documentElement&&(b=a);a+="Selector";a in document.documentElement&&
(b=a);return b});var c=!document.documentMode||9<document.documentMode,d=window.chrome,e=d&&(d.webstore||d.app),f=/Apple/.test(navigator.vendor)&&/Version\/([6-9]\d*|[1-5]\d+)/.test(navigator.userAgent);return a}(),HandTool={initialize:function(a){var b=a.toggleHandTool;this.handTool=new GrabToPan({element:a.container,onActiveChanged:function(a){b&&(a?(b.title=mozL10n.get("hand_tool_disable.title",null,"Disable hand tool"),b.firstElementChild.textContent=mozL10n.get("hand_tool_disable_label",null,
"Disable hand tool")):(b.title=mozL10n.get("hand_tool_enable.title",null,"Enable hand tool"),b.firstElementChild.textContent=mozL10n.get("hand_tool_enable_label",null,"Enable hand tool")))}});b&&(b.addEventListener("click",this.toggle.bind(this),!1),window.addEventListener("localized",function(a){Preferences.get("enableHandToolOnLoad").then(function(a){a&&this.handTool.activate()}.bind(this),function(a){})}.bind(this)))},toggle:function(){this.handTool.toggle();SecondaryToolbar.close()},enterPresentationMode:function(){this.handTool.active&&
(this.wasActive=!0,this.handTool.deactivate())},exitPresentationMode:function(){this.wasActive&&(this.wasActive=null,this.handTool.activate())}},OverlayManager={overlays:{},active:null,register:function(a,b,c){return new Promise(function(d){var e,f;if(!a||!(e=document.getElementById(a))||!(f=e.parentNode))throw Error("Not enough parameters.");if(this.overlays[a])throw Error("The overlay is already registered.");this.overlays[a]={element:e,container:f,callerCloseMethod:b||null,canForceClose:c||!1};
d()}.bind(this))},unregister:function(a){return new Promise(function(b){if(!this.overlays[a])throw Error("The overlay does not exist.");if(this.active===a)throw Error("The overlay cannot be removed while it is active.");delete this.overlays[a];b()}.bind(this))},open:function(a){return new Promise(function(b){if(!this.overlays[a])throw Error("The overlay does not exist.");if(this.active)if(this.overlays[a].canForceClose)this._closeThroughCaller();else{if(this.active===a)throw Error("The overlay is already active.");
throw Error("Another overlay is currently active.");}this.active=a;this.overlays[this.active].element.classList.remove("hidden");this.overlays[this.active].container.classList.remove("hidden");window.addEventListener("keydown",this._keyDown);b()}.bind(this))},close:function(a){return new Promise(function(b){if(this.overlays[a]){if(!this.active)throw Error("The overlay is currently not active.");if(this.active!==a)throw Error("Another overlay is currently active.");}else throw Error("The overlay does not exist.");
this.overlays[this.active].container.classList.add("hidden");this.overlays[this.active].element.classList.add("hidden");this.active=null;window.removeEventListener("keydown",this._keyDown);b()}.bind(this))},_keyDown:function(a){var b=OverlayManager;b.active&&27===a.keyCode&&(b._closeThroughCaller(),a.preventDefault())},_closeThroughCaller:function(){this.overlays[this.active].callerCloseMethod&&this.overlays[this.active].callerCloseMethod();this.active&&this.close(this.active)}},PasswordPrompt={overlayName:null,
updatePassword:null,reason:null,passwordField:null,passwordText:null,passwordSubmit:null,passwordCancel:null,initialize:function(a){this.overlayName=a.overlayName;this.passwordField=a.passwordField;this.passwordText=a.passwordText;this.passwordSubmit=a.passwordSubmit;this.passwordCancel=a.passwordCancel;this.passwordSubmit.addEventListener("click",this.verifyPassword.bind(this));this.passwordCancel.addEventListener("click",this.close.bind(this));this.passwordField.addEventListener("keydown",function(a){13===
a.keyCode&&this.verifyPassword()}.bind(this));OverlayManager.register(this.overlayName,this.close.bind(this),!0)},open:function(){OverlayManager.open(this.overlayName).then(function(){this.passwordField.focus();var a=mozL10n.get("password_label",null,"Enter the password to open this PDF file.");this.reason===PDFJS.PasswordResponses.INCORRECT_PASSWORD&&(a=mozL10n.get("password_invalid",null,"Invalid password. Please try again."));this.passwordText.textContent=a}.bind(this))},close:function(){OverlayManager.close(this.overlayName).then(function(){this.passwordField.value=
""}.bind(this))},verifyPassword:function(){var a=this.passwordField.value;if(a&&0<a.length)return this.close(),this.updatePassword(a)}},DocumentProperties={overlayName:null,rawFileSize:0,fileNameField:null,fileSizeField:null,titleField:null,authorField:null,subjectField:null,keywordsField:null,creationDateField:null,modificationDateField:null,creatorField:null,producerField:null,versionField:null,pageCountField:null,initialize:function(a){this.overlayName=a.overlayName;this.fileNameField=a.fileNameField;
this.fileSizeField=a.fileSizeField;this.titleField=a.titleField;this.authorField=a.authorField;this.subjectField=a.subjectField;this.keywordsField=a.keywordsField;this.creationDateField=a.creationDateField;this.modificationDateField=a.modificationDateField;this.creatorField=a.creatorField;this.producerField=a.producerField;this.versionField=a.versionField;this.pageCountField=a.pageCountField;a.closeButton&&a.closeButton.addEventListener("click",this.close.bind(this));this.dataAvailablePromise=new Promise(function(a){this.resolveDataAvailable=
a}.bind(this));OverlayManager.register(this.overlayName,this.close.bind(this))},getProperties:function(){OverlayManager.active&&(PDFView.pdfDocument.getDownloadInfo().then(function(a){a.length!==this.rawFileSize&&(this.setFileSize(a.length),this.updateUI(this.fileSizeField,this.parseFileSize()))}.bind(this)),PDFView.pdfDocument.getMetadata().then(function(a){a=[{field:this.fileNameField,content:getPDFFileNameFromURL(PDFView.url)},{field:this.fileSizeField,content:this.parseFileSize()},{field:this.titleField,
content:a.info.Title},{field:this.authorField,content:a.info.Author},{field:this.subjectField,content:a.info.Subject},{field:this.keywordsField,content:a.info.Keywords},{field:this.creationDateField,content:this.parseDate(a.info.CreationDate)},{field:this.modificationDateField,content:this.parseDate(a.info.ModDate)},{field:this.creatorField,content:a.info.Creator},{field:this.producerField,content:a.info.Producer},{field:this.versionField,content:a.info.PDFFormatVersion},{field:this.pageCountField,
content:PDFView.pdfDocument.numPages}];for(var b in a){var c=a[b];this.updateUI(c.field,c.content)}}.bind(this)))},updateUI:function(a,b){a&&void 0!==b&&""!==b&&(a.textContent=b)},setFileSize:function(a){0<a&&(this.rawFileSize=a)},parseFileSize:function(){var a=this.rawFileSize,b=a/1024;if(b)return 1024>b?mozL10n.get("document_properties_kb",{size_kb:(+b.toPrecision(3)).toLocaleString(),size_b:a.toLocaleString()},"{{size_kb}} KB ({{size_b}} bytes)"):mozL10n.get("document_properties_mb",{size_mb:(+(b/
1024).toPrecision(3)).toLocaleString(),size_b:a.toLocaleString()},"{{size_mb}} MB ({{size_b}} bytes)")},open:function(){Promise.all([OverlayManager.open(this.overlayName),this.dataAvailablePromise]).then(function(){this.getProperties()}.bind(this))},close:function(){OverlayManager.close(this.overlayName)},parseDate:function(a){var b=a;if(void 0===b)return"";"D:"===b.substring(0,2)&&(b=b.substring(2));a=parseInt(b.substring(0,4),10);var c=parseInt(b.substring(4,6),10)-1,d=parseInt(b.substring(6,8),
10),e=parseInt(b.substring(8,10),10),f=parseInt(b.substring(10,12),10),g=parseInt(b.substring(12,14),10),h=b.substring(14,15),k=parseInt(b.substring(15,17),10),b=parseInt(b.substring(18,20),10);"-"===h?(e+=k,f+=b):"+"===h&&(e-=k,f-=b);c=new Date(Date.UTC(a,c,d,e,f,g));a=c.toLocaleDateString();c=c.toLocaleTimeString();return mozL10n.get("document_properties_date_string",{date:a,time:c},"{{date}}, {{time}}")}},PDFView={pages:[],thumbnails:[],currentScale:UNKNOWN_SCALE,currentScaleValue:null,initialBookmark:document.location.hash.substring(1),
container:null,thumbnailContainer:null,initialized:!1,fellback:!1,pdfDocument:null,sidebarOpen:!1,printing:!1,pageViewScroll:null,thumbnailViewScroll:null,pageRotation:0,mouseScrollTimeStamp:0,mouseScrollDelta:0,lastScroll:0,previousPageNumber:1,isViewerEmbedded:window.parent!==window,idleTimeout:null,currentPosition:null,url:"",initialize:function(){var a=this,b=this.container=document.getElementById("viewerContainer");this.pageViewScroll={};this.watchScroll(b,this.pageViewScroll,updateViewarea);
var c=this.thumbnailContainer=document.getElementById("thumbnailView");this.thumbnailViewScroll={};this.watchScroll(c,this.thumbnailViewScroll,this.renderHighestPriority.bind(this));Preferences.initialize();this.findController=new PDFFindController({pdfPageSource:this,integratedFind:this.supportsIntegratedFind});this.findBar=new PDFFindBar({bar:document.getElementById("findbar"),toggleButton:document.getElementById("viewFind"),findField:document.getElementById("findInput"),highlightAllCheckbox:document.getElementById("findHighlightAll"),
caseSensitiveCheckbox:document.getElementById("findMatchCase"),findMsg:document.getElementById("findMsg"),findStatusIcon:document.getElementById("findStatusIcon"),findPreviousButton:document.getElementById("findPrevious"),findNextButton:document.getElementById("findNext"),findController:this.findController});this.findController.setFindBar(this.findBar);HandTool.initialize({container:b,toggleHandTool:document.getElementById("toggleHandTool")});SecondaryToolbar.initialize({toolbar:document.getElementById("secondaryToolbar"),
presentationMode:PresentationMode,toggleButton:document.getElementById("secondaryToolbarToggle"),presentationModeButton:document.getElementById("secondaryPresentationMode"),openFile:document.getElementById("secondaryOpenFile"),print:document.getElementById("secondaryPrint"),download:document.getElementById("secondaryDownload"),viewBookmark:document.getElementById("secondaryViewBookmark"),firstPage:document.getElementById("firstPage"),lastPage:document.getElementById("lastPage"),pageRotateCw:document.getElementById("pageRotateCw"),
pageRotateCcw:document.getElementById("pageRotateCcw"),documentProperties:DocumentProperties,documentPropertiesButton:document.getElementById("documentProperties")});PresentationMode.initialize({container:b,secondaryToolbar:SecondaryToolbar,firstPage:document.getElementById("contextFirstPage"),lastPage:document.getElementById("contextLastPage"),pageRotateCw:document.getElementById("contextPageRotateCw"),pageRotateCcw:document.getElementById("contextPageRotateCcw")});PasswordPrompt.initialize({overlayName:"passwordOverlay",
passwordField:document.getElementById("password"),passwordText:document.getElementById("passwordText"),passwordSubmit:document.getElementById("passwordSubmit"),passwordCancel:document.getElementById("passwordCancel")});DocumentProperties.initialize({overlayName:"documentPropertiesOverlay",closeButton:document.getElementById("documentPropertiesClose"),fileNameField:document.getElementById("fileNameField"),fileSizeField:document.getElementById("fileSizeField"),titleField:document.getElementById("titleField"),
authorField:document.getElementById("authorField"),subjectField:document.getElementById("subjectField"),keywordsField:document.getElementById("keywordsField"),creationDateField:document.getElementById("creationDateField"),modificationDateField:document.getElementById("modificationDateField"),creatorField:document.getElementById("creatorField"),producerField:document.getElementById("producerField"),versionField:document.getElementById("versionField"),pageCountField:document.getElementById("pageCountField")});
b.addEventListener("scroll",function(){a.lastScroll=Date.now()},!1);return Promise.all([Preferences.get("enableWebGL").then(function(a){PDFJS.disableWebGL=!a}),Preferences.get("sidebarViewOnLoad").then(function(b){a.preferenceSidebarViewOnLoad=b}),Preferences.get("disableTextLayer").then(function(a){!0!==PDFJS.disableTextLayer&&(PDFJS.disableTextLayer=a)}),Preferences.get("disableRange").then(function(a){!0!==PDFJS.disableRange&&(PDFJS.disableRange=a)}),Preferences.get("disableAutoFetch").then(function(a){PDFJS.disableAutoFetch=
a}),Preferences.get("disableFontFace").then(function(a){!0!==PDFJS.disableFontFace&&(PDFJS.disableFontFace=a)}),Preferences.get("useOnlyCssZoom").then(function(a){PDFJS.useOnlyCssZoom=a})]).catch(function(a){}).then(function(){PDFView.initialized=!0})},getPage:function(a){return this.pdfDocument.getPage(a)},watchScroll:function(a,b,c){b.down=!0;b.lastY=a.scrollTop;b.rAF=null;a.addEventListener("scroll",function(d){b.rAF||(b.rAF=window.requestAnimationFrame(function(){b.rAF=null;if(PDFView.pdfDocument){var d=
a.scrollTop,f=b.lastY;d>f?b.down=!0:d<f&&(b.down=!1);b.lastY=d;c()}}))},!0)},_setScaleUpdatePages:function(a,b,c,d){this.currentScaleValue=b;if(a!==this.currentScale){b=0;for(var e=this.pages.length;b<e;b++)this.pages[b].update(a);this.currentScale=a;if(!d){d=this.page;var f;this.currentPosition&&!IGNORE_CURRENT_POSITION_ON_ZOOM&&(d=this.currentPosition.page,f=[null,{name:"XYZ"},this.currentPosition.left,this.currentPosition.top,null]);this.pages[d-1].scrollIntoView(f)}f=document.createEvent("UIEvents");
f.initUIEvent("scalechange",!1,!1,window,0);f.scale=a;f.resetAutoSettings=c;window.dispatchEvent(f)}},setScale:function(a,b,c){if("custom"!==a){var d=parseFloat(a);if(0<d)this._setScaleUpdatePages(d,a,!0,c);else{var e=this.pages[this.page-1];if(e){d=(this.container.clientWidth-(PresentationMode.active?0:SCROLLBAR_PADDING))/e.width*e.scale;e=(this.container.clientHeight-(PresentationMode.active?0:VERTICAL_PADDING))/e.height*e.scale;switch(a){case "page-actual":d=1;break;case "page-width":break;case "page-height":d=
e;break;case "page-fit":d=Math.min(d,e);break;case "auto":d=Math.min(MAX_AUTO_SCALE,d);break;default:console.error("pdfViewSetScale: '"+a+"' is an unknown zoom value.");return}this._setScaleUpdatePages(d,a,b,c);selectScaleOption(a)}}}},zoomIn:function(a){var b=this.currentScale;do b=(b*DEFAULT_SCALE_DELTA).toFixed(2),b=Math.ceil(10*b)/10,b=Math.min(MAX_SCALE,b);while(--a&&b<MAX_SCALE);this.setScale(b,!0)},zoomOut:function(a){var b=this.currentScale;do b=(b/DEFAULT_SCALE_DELTA).toFixed(2),b=Math.floor(10*
b)/10,b=Math.max(MIN_SCALE,b);while(--a&&b>MIN_SCALE);this.setScale(b,!0)},set page(a){var b=this.pages,c=document.createEvent("UIEvents");c.initUIEvent("pagechange",!1,!1,window,0);0<a&&a<=b.length?(b[a-1].updateStats(),this.previousPageNumber=currentPageNumber,currentPageNumber=a,c.pageNumber=a,window.dispatchEvent(c),updateViewarea.inProgress||this.loading&&1===a||b[a-1].scrollIntoView()):(this.previousPageNumber=a,c.pageNumber=this.page,window.dispatchEvent(c))},get page(){return currentPageNumber},
get supportsPrinting(){var a="mozPrintCallback"in document.createElement("canvas");Object.defineProperty(this,"supportsPrinting",{value:a,enumerable:!0,configurable:!0,writable:!1});return a},get supportsFullscreen(){var a=document.documentElement,a=a.requestFullscreen||a.mozRequestFullScreen||a.webkitRequestFullScreen||a.msRequestFullscreen;if(!1===document.fullscreenEnabled||!1===document.mozFullScreenEnabled||!1===document.webkitFullscreenEnabled||!1===document.msFullscreenEnabled)a=!1;Object.defineProperty(this,
"supportsFullscreen",{value:a,enumerable:!0,configurable:!0,writable:!1});return a},get supportsIntegratedFind(){Object.defineProperty(this,"supportsIntegratedFind",{value:!1,enumerable:!0,configurable:!0,writable:!1});return!1},get supportsDocumentFonts(){Object.defineProperty(this,"supportsDocumentFonts",{value:!0,enumerable:!0,configurable:!0,writable:!1});return!0},get supportsDocumentColors(){Object.defineProperty(this,"supportsDocumentColors",{value:!0,enumerable:!0,configurable:!0,writable:!1});
return!0},get loadingBar(){var a=new ProgressBar("#loadingBar",{});Object.defineProperty(this,"loadingBar",{value:a,enumerable:!0,configurable:!0,writable:!1});return a},get isHorizontalScrollbarEnabled(){return PresentationMode.active?!1:this.container.scrollWidth>this.container.clientWidth},setTitleUsingUrl:function(a){this.url=a;try{this.setTitle(decodeURIComponent(getFileName(a))||a)}catch(b){this.setTitle(a)}},setTitle:function(a){document.title=a},close:function(){document.getElementById("errorWrapper").setAttribute("hidden",
"true");if(this.pdfDocument){this.pdfDocument.destroy();this.pdfDocument=null;for(var a=document.getElementById("thumbnailView");a.hasChildNodes();)a.removeChild(a.lastChild);for(a=document.getElementById("viewer");a.hasChildNodes();)a.removeChild(a.lastChild);"undefined"!==typeof PDFBug&&PDFBug.cleanup()}},open:function(a,b,c,d,e,f){a&&a.indexOf&&0==a.indexOf("blob:http:")&&(issafari||(a=a.replace(/(http:)/,"http%3A")));if(g_last_blob_url&&0==g_last_blob_url.indexOf("blob:"))try{(window.URL||window.webkitURL).revokeObjectURL(g_last_blob_url)}catch(g){}g_last_blob_url=
null;a&&a.indexOf&&(g_last_blob_url=a);this.pdfDocument&&Preferences.reload();this.close();c={password:c};"string"===typeof a?(f?this.setTitleUsingUrl(f):this.setTitleUsingUrl(a),c.url=a):a&&"byteLength"in a&&(c.data=a);if(e)for(var h in e)c[h]=e[h];var k=this;k.loading=!0;k.downloadComplete=!1;PDFJS.getDocument(c,d,function(a,b){PasswordPrompt.updatePassword=a;PasswordPrompt.reason=b;PasswordPrompt.open()},function(a){k.progress(a.loaded/a.total)}).then(function(a){k.load(a,b);k.loading=!1},function(a,
b){var c=mozL10n.get("loading_error",null,"An error occurred while loading the PDF.");b&&"InvalidPDFException"===b.name&&(c=mozL10n.get("invalid_file_error",null,"Invalid or corrupted PDF file."));b&&"MissingPDFException"===b.name&&(c=mozL10n.get("missing_file_error",null,"Missing PDF file."));k.error(c,{message:a});k.loading=!1});e&&e.length&&DocumentProperties.setFileSize(e.length)},download:function(){function a(){d.downloadUrl(b,c)}var b=this.url.split("#")[0],c=getPDFFileNameFromURL(b),d=new DownloadManager;
d.onerror=function(a){PDFView.error("PDF failed to download.")};this.pdfDocument?this.downloadComplete?this.pdfDocument.getData().then(function(a){a=PDFJS.createBlob(a,"application/pdf");d.download(a,b,c)},a).then(null,a):a():a()},fallback:function(a){},navigateTo:function(a){var b="",c=this,d=function(e){c.pendingRefStr=null;var f=e instanceof Object?c.pagesRefMap[e.num+" "+e.gen+" R"]:e+1;f?(f>c.pages.length&&(f=c.pages.length),c.pages[f-1].scrollIntoView(a),PDFHistory.push({dest:a,hash:b,page:f})):
c.pdfDocument.getPageIndex(e).then(function(a){c.pagesRefMap[e.num+" "+e.gen+" R"]=a+1;d(e)})};this.destinationsPromise.then(function(){"string"===typeof a&&(b=a,a=c.destinations[a]);a instanceof Array&&d(a[0])})},getDestinationHash:function(a){if("string"===typeof a)return PDFView.getAnchorUrl("#"+escape(a));if(a instanceof Array){var b=a[0];if(b=b instanceof Object?this.pagesRefMap[b.num+" "+b.gen+" R"]:b+1){var b=PDFView.getAnchorUrl("#page="+b),c=a[1];if("object"===typeof c&&"name"in c&&"XYZ"===
c.name){var c=a[4]||this.currentScaleValue,d=parseFloat(c);d&&(c=100*d);b+="&zoom="+c;if(a[2]||a[3])b+=","+(a[2]||0)+","+(a[3]||0)}return b}}return""},getAnchorUrl:function(a){return a},error:function(a,b){var c=mozL10n.get("error_version_info",{version:PDFJS.version||"?",build:PDFJS.build||"?"},"PDF.js v{{version}} (build: {{build}})")+"\n";b&&(c+=mozL10n.get("error_message",{message:b.message},"Message: {{message}}"),b.stack?c+="\n"+mozL10n.get("error_stack",{stack:b.stack},"Stack: {{stack}}"):
(b.filename&&(c+="\n"+mozL10n.get("error_file",{file:b.filename},"File: {{file}}")),b.lineNumber&&(c+="\n"+mozL10n.get("error_line",{line:b.lineNumber},"Line: {{line}}"))));var d=document.getElementById("errorWrapper");d.removeAttribute("hidden");document.getElementById("errorMessage").textContent=a;var e=document.getElementById("errorClose");e.onclick=function(){d.setAttribute("hidden","true")};var f=document.getElementById("errorMoreInfo"),g=document.getElementById("errorShowMore"),h=document.getElementById("errorShowLess");
g.onclick=function(){f.removeAttribute("hidden");g.setAttribute("hidden","true");h.removeAttribute("hidden");f.style.height=f.scrollHeight+"px"};h.onclick=function(){f.setAttribute("hidden","true");g.removeAttribute("hidden");h.setAttribute("hidden","true")};g.oncontextmenu=noContextMenuHandler;h.oncontextmenu=noContextMenuHandler;e.oncontextmenu=noContextMenuHandler;g.removeAttribute("hidden");h.setAttribute("hidden","true");f.value=c},progress:function(a){a=Math.round(100*a);if(a>PDFView.loadingBar.percent||
isNaN(a))PDFView.loadingBar.percent=a},load:function(a,b){function c(a,b){a.onAfterDraw=function(){e||(e=!0,f());b.setImage(a.canvas)}}var d=this,e=!1,f=null,g=new Promise(function(a){f=a});PDFView.findController.reset();this.pdfDocument=a;DocumentProperties.resolveDataAvailable();var h=a.getDownloadInfo().then(function(){d.downloadComplete=!0;PDFView.loadingBar.hide();document.getElementById("outerContainer").classList.remove("loadingInProgress")}),k=a.numPages,l=a.fingerprint;document.getElementById("numPages").textContent=
mozL10n.get("page_of",{pageCount:k},"of {{pageCount}}");document.getElementById("pageNumber").max=k;PDFView.documentFingerprint=l;var n=PDFView.store=new ViewHistory(l);this.pageRotation=0;var s=this.pages=[],t=this.pagesRefMap={},x=this.thumbnails=[],q;this.pagesPromise=l=new Promise(function(a){q=a});var m=a.getPage(1),r=document.getElementById("viewer"),p=document.getElementById("thumbnailView");m.then(function(e){e=e.getViewport((b||1)*CSS_UNITS);for(var f=1;f<=k;++f){var l=e.clone(),n=new PageView(r,
f,b,d.navigateTo.bind(d),l),l=new ThumbnailView(p,f,l);c(n,l);s.push(n);x.push(l)}g.then(function(){if(PDFJS.disableAutoFetch)q();else for(var b=k,c=1;c<=k;++c)a.getPage(c).then(function(a,c){var d=s[a-1];d.pdfPage||d.setPdfPage(c);t[c.ref.num+" "+c.ref.gen+" R"]=a;b--;b||q()}.bind(null,c))});h.then(function(){var a=document.createEvent("CustomEvent");a.initCustomEvent("documentload",!0,!0,{});window.dispatchEvent(a)});PDFView.loadingBar.setWidth(r);PDFView.findController.resolveFirstPage();PDFHistory.initialize(d.documentFingerprint)});
var v,u=Preferences.get("showPreviousViewOnLoad").then(function(a){v=a}),w,y=Preferences.get("defaultZoomValue").then(function(a){w=a});Promise.all([m,n.initializedPromise,u,y]).then(function(){var a=null;if(v&&n.get("exists",!1))var a=n.get("page","1"),c=w||n.get("zoom",PDFView.currentScale),e=n.get("scrollLeft","0"),f=n.get("scrollTop","0"),a="page="+a+"&zoom="+c+","+e+","+f;else w&&(a="page=1&zoom="+w);d.setInitialView(a,b);d.isViewerEmbedded||d.container.focus()},function(a){console.error(a);
m.then(function(){d.setInitialView(null,b)})});l.then(function(){PDFView.supportsPrinting&&a.getJavaScript().then(function(a){a.length&&(console.warn("Warning: JavaScript is not supported"),PDFView.fallback(PDFJS.UNSUPPORTED_FEATURES.javaScript));for(var b=/\bprint\s*\(/g,c=0,d=a.length;c<d;c++){var e=a[c];if(e&&b.test(e)){setTimeout(function(){window.print()});break}}})});u=this.destinationsPromise=a.getDestinations();u.then(function(a){d.destinations=a});Promise.all([l,u,PDFView.animationStartedPromise]).then(function(){a.getOutline().then(function(a){d.outline=
new DocumentOutlineView(a);document.getElementById("viewOutline").disabled=!a;a&&d.preferenceSidebarViewOnLoad===SidebarView.OUTLINE&&d.switchSidebarView("outline",!0)});a.getAttachments().then(function(a){d.attachments=new DocumentAttachmentsView(a);document.getElementById("viewAttachments").disabled=!a;a&&d.preferenceSidebarViewOnLoad===SidebarView.ATTACHMENTS&&d.switchSidebarView("attachments",!0)})});d.preferenceSidebarViewOnLoad===SidebarView.THUMBS&&Promise.all([m,g]).then(function(){d.switchSidebarView("thumbs",
!0)});a.getMetadata().then(function(b){var c=b.info;b=b.metadata;d.documentInfo=c;d.metadata=b;console.log("PDF "+a.fingerprint+" ["+c.PDFFormatVersion+" "+(c.Producer||"-").trim()+" / "+(c.Creator||"-").trim()+"] (PDF.js: "+(PDFJS.version||"-")+(PDFJS.disableWebGL?"":" [WebGL]")+")");var e;b&&b.has("dc:title")&&(e=b.get("dc:title"));!e&&c&&c.Title&&(e=c.Title);e&&d.setTitle(e+" - "+document.title);c.IsAcroFormPresent&&(console.warn("Warning: AcroForm/XFA is not supported"),PDFView.fallback(PDFJS.UNSUPPORTED_FEATURES.forms))})},
setInitialView:function(a,b){this.currentScale=0;this.currentScaleValue=null;document.getElementById("pageNumber").value=currentPageNumber=1;this.currentPosition=null;PDFHistory.initialDestination?(this.navigateTo(PDFHistory.initialDestination),PDFHistory.initialDestination=null):this.initialBookmark?(this.setHash(this.initialBookmark),PDFHistory.push({hash:this.initialBookmark},!!this.initialBookmark),this.initialBookmark=null):a?this.setHash(a):b&&(this.setScale(b,!0),this.page=1);PDFView.currentScale===
UNKNOWN_SCALE&&this.setScale(DEFAULT_SCALE,!0)},renderHighestPriority:function(a){PDFView.idleTimeout&&(clearTimeout(PDFView.idleTimeout),PDFView.idleTimeout=null);a=a||this.getVisiblePages();if(a=this.getHighestPriority(a,this.pages,this.pageViewScroll.down))this.renderView(a,"page");else{if(this.sidebarOpen&&(a=this.getVisibleThumbs(),a=this.getHighestPriority(a,this.thumbnails,this.thumbnailViewScroll.down))){this.renderView(a,"thumbnail");return}this.printing||(PDFView.idleTimeout=setTimeout(function(){PDFView.cleanup()},
CLEANUP_TIMEOUT))}},cleanup:function(){for(var a=0,b=this.pages.length;a<b;a++)this.pages[a]&&this.pages[a].renderingState!==RenderingStates.FINISHED&&this.pages[a].reset();this.pdfDocument.cleanup();ThumbnailView.tempImageCache=null},getHighestPriority:function(a,b,c){var d=a.views,e=d.length;if(0===e)return!1;for(var f=0;f<e;++f){var g=d[f].view;if(!this.isViewFinished(g))return g}a=c?a.last.id:a.first.id-2;return b[a]&&!this.isViewFinished(b[a])?b[a]:!1},isViewFinished:function(a){return a.renderingState===
RenderingStates.FINISHED},renderView:function(a,b){switch(a.renderingState){case RenderingStates.FINISHED:return!1;case RenderingStates.PAUSED:PDFView.highestPriorityPage=b+a.id;a.resume();break;case RenderingStates.RUNNING:PDFView.highestPriorityPage=b+a.id;break;case RenderingStates.INITIAL:PDFView.highestPriorityPage=b+a.id,a.draw(this.renderHighestPriority.bind(this))}return!0},setHash:function(a){var b="Fit FitB FitH FitBH FitV FitBV FitR".split(" ");if(a)if(0<=a.indexOf("="))if(a=PDFView.parseQueryString(a),
"nameddest"in a)PDFHistory.updateNextHashParam(a.nameddest),PDFView.navigateTo(a.nameddest);else{var c,d;"page"in a&&(c=a.page|0||1);if("zoom"in a){d=a.zoom.split(",");var e=d[0],f=parseFloat(e),g="XYZ";f?e=f/100:0<=b.indexOf(e)&&(g=e);d=[null,{name:g},1<d.length?d[1]|0:null,2<d.length?d[2]|0:null,e]}d?this.pages[(c||this.page)-1].scrollIntoView(d):c&&(this.page=c);"pagemode"in a&&("thumbs"===a.pagemode||"bookmarks"===a.pagemode||"attachments"===a.pagemode?this.switchSidebarView("bookmarks"===a.pagemode?
"outline":a.pagemode,!0):"none"===a.pagemode&&this.sidebarOpen&&document.getElementById("sidebarToggle").click())}else/^\d+$/.test(a)?this.page=a:(PDFHistory.updateNextHashParam(unescape(a)),PDFView.navigateTo(unescape(a)))},switchSidebarView:function(a,b){b&&!this.sidebarOpen&&document.getElementById("sidebarToggle").click();var c=document.getElementById("thumbnailView"),d=document.getElementById("outlineView"),e=document.getElementById("attachmentsView"),f=document.getElementById("viewThumbnail"),
g=document.getElementById("viewOutline"),h=document.getElementById("viewAttachments");switch(a){case "thumbs":var k=c.classList.contains("hidden");f.classList.add("toggled");g.classList.remove("toggled");h.classList.remove("toggled");c.classList.remove("hidden");d.classList.add("hidden");e.classList.add("hidden");PDFView.renderHighestPriority();k&&scrollIntoView(document.getElementById("thumbnailContainer"+this.page));break;case "outline":f.classList.remove("toggled");g.classList.add("toggled");h.classList.remove("toggled");
c.classList.add("hidden");d.classList.remove("hidden");e.classList.add("hidden");if(g.getAttribute("disabled"))break;break;case "attachments":f.classList.remove("toggled"),g.classList.remove("toggled"),h.classList.add("toggled"),c.classList.add("hidden"),d.classList.add("hidden"),e.classList.remove("hidden"),h.getAttribute("disabled")}},getVisiblePages:function(){if(PresentationMode.active){var a=[],b=this.pages[this.page-1];a.push({id:b.id,view:b});return{first:b,last:b,views:a}}return this.getVisibleElements(this.container,
this.pages,!0)},getVisibleThumbs:function(){return this.getVisibleElements(this.thumbnailContainer,this.thumbnails)},getVisibleElements:function(a,b,c){var d=a.scrollTop,e=d+a.clientHeight,f=a.scrollLeft,g=f+a.clientWidth;a=[];for(var h,k,l,n,s,t=0,x=b.length;t<x;++t)if(h=b[t],k=h.el.offsetTop+h.el.clientTop,l=h.el.clientHeight,!(k+l<d)){if(k>e)break;s=h.el.offsetLeft+h.el.clientLeft;n=h.el.clientWidth;s+n<f||s>g||(n=Math.max(0,d-k)+Math.max(0,k+l-e),l=100*(l-n)/l|0,a.push({id:h.id,x:s,y:k,view:h,
percent:l}))}b=a[0];d=a[a.length-1];c&&a.sort(function(a,b){var c=a.percent-b.percent;return.001<Math.abs(c)?-c:a.id-b.id});return{first:b,last:d,views:a}},parseQueryString:function(a){a=a.split("&");for(var b={},c=0,d=a.length;c<d;++c){var e=a[c].split("="),f=1<e.length?e[1]:null;b[decodeURIComponent(e[0])]=decodeURIComponent(f)}return b},beforePrint:function(){if(this.supportsPrinting){var a=!1,b,c;if(this.pages.length)for(b=0,c=this.pages.length;b<c;++b){if(!this.pages[b].pdfPage){a=!0;break}}else a=
!0;if(a)a=mozL10n.get("printing_not_ready",null,"Warning: The PDF is not fully loaded for printing."),window.alert(a);else for(this.printing=!0,this.renderHighestPriority(),document.querySelector("body").setAttribute("data-mozPrintCallback",!0),b=0,c=this.pages.length;b<c;++b)this.pages[b].beforePrint()}else a=mozL10n.get("printing_not_supported",null,"Warning: Printing is not fully supported by this browser."),this.error(a)},afterPrint:function(){for(var a=document.getElementById("printContainer");a.hasChildNodes();)a.removeChild(a.lastChild);
this.printing=!1;this.renderHighestPriority()},rotatePages:function(a){var b=this.pages[this.page-1],c;this.pageRotation=(this.pageRotation+360+a)%360;a=0;for(c=this.pages.length;a<c;a++){var d=this.pages[a];d.update(d.scale,this.pageRotation)}a=0;for(c=this.thumbnails.length;a<c;a++)this.thumbnails[a].update(this.pageRotation);this.setScale(this.currentScaleValue,!0,!0);this.renderHighestPriority();b&&b.scrollIntoView()},mouseScroll:function(a){var b=(new Date).getTime(),c=this.mouseScrollTimeStamp;
b>c&&50>b-c||((0<this.mouseScrollDelta&&0>a||0>this.mouseScrollDelta&&0<a)&&this.clearMouseScrollState(),this.mouseScrollDelta+=a,120<=Math.abs(this.mouseScrollDelta)&&(a=0<this.mouseScrollDelta?-1:1,this.clearMouseScrollState(),c=this.page,1===c&&-1===a||c===this.pages.length&&1===a||(this.page+=a,this.mouseScrollTimeStamp=b)))},clearMouseScrollState:function(){this.mouseScrollDelta=this.mouseScrollTimeStamp=0}},PageView=function(a,b,c,d,e){function f(a,b,c){function d(a,b){a.href=PDFView.getDestinationHash(b);
a.onclick=function(){b&&PDFView.navigateTo(b);return!1};b&&(a.className="internalLink")}function e(a,b){a.href=PDFView.getAnchorUrl("");a.onclick=function(){switch(b){case "GoToPage":document.getElementById("pageNumber").focus();break;case "GoBack":PDFHistory.back();break;case "GoForward":PDFHistory.forward();break;case "Find":PDFView.supportsIntegratedFind||PDFView.findBar.toggle();break;case "NextPage":PDFView.page++;break;case "PrevPage":PDFView.page--;break;case "LastPage":PDFView.page=PDFView.pages.length;
break;case "FirstPage":PDFView.page=1}return!1};a.className="internalLink"}b.getAnnotations().then(function(f){c=c.clone({dontFlip:!0});var g="matrix("+c.transform.join(",")+")",m,r,p,v;if(h.annotationLayer){p=0;for(v=f.length;p<v;p++)m=f[p],(r=h.annotationLayer.querySelector('[data-annotation-id="'+m.id+'"]'))&&CustomStyle.setProp("transform",r,g);h.annotationLayer.removeAttribute("hidden")}else for(p=0,v=f.length;p<v;p++)if((m=f[p])&&m.hasHtml){r=PDFJS.AnnotationUtils.getHtmlElement(m,b.commonObjs);
r.setAttribute("data-annotation-id",m.id);mozL10n.translate(r);var u=m.rect,w=b.view,u=PDFJS.Util.normalizeRect([u[0],w[3]-u[1]+w[1],u[2],w[3]-u[3]+w[1]]);r.style.left=u[0]+"px";r.style.top=u[1]+"px";r.style.position="absolute";CustomStyle.setProp("transform",r,g);CustomStyle.setProp("transformOrigin",r,-u[0]+"px "+-u[1]+"px");"Link"!==m.subtype||m.url||(u=r.getElementsByTagName("a")[0])&&(m.action?e(u,m.action):d(u,"dest"in m?m.dest:null));h.annotationLayer||(m=document.createElement("div"),m.className=
"annotationLayer",a.appendChild(m),h.annotationLayer=m);h.annotationLayer.appendChild(r)}})}this.id=b;this.rotation=0;this.scale=c||1;this.viewport=e;this.pdfPageRotate=e.rotation;this.hasRestrictedScaling=!1;this.renderingState=RenderingStates.INITIAL;this.annotationLayer=this.zoomLayer=this.textLayer=this.resume=null;b=document.createElement("a");b.name=""+this.id;var g=this.el=document.createElement("div");g.id="pageContainer"+this.id;g.className="page";g.style.width=Math.floor(this.viewport.width)+
"px";g.style.height=Math.floor(this.viewport.height)+"px";a.appendChild(b);a.appendChild(g);this.setPdfPage=function(a){this.pdfPage=a;this.pdfPageRotate=a.rotate;this.viewport=a.getViewport(this.scale*CSS_UNITS,(this.rotation+this.pdfPageRotate)%360);this.stats=a.stats;this.reset()};this.destroy=function(){this.zoomLayer=null;this.reset();this.pdfPage&&this.pdfPage.destroy()};this.reset=function(a){this.renderTask&&this.renderTask.cancel();this.resume=null;this.renderingState=RenderingStates.INITIAL;
g.style.width=Math.floor(this.viewport.width)+"px";g.style.height=Math.floor(this.viewport.height)+"px";for(var b=g.childNodes,c=g.childNodes.length-1;0<=c;c--){var d=b[c];this.zoomLayer&&this.zoomLayer===d||a&&this.annotationLayer===d||g.removeChild(d)}g.removeAttribute("data-loaded");a?this.annotationLayer&&this.annotationLayer.setAttribute("hidden","true"):this.annotationLayer=null;this.canvas&&(this.canvas.width=0,this.canvas.height=0,delete this.canvas);this.loadingIconDiv=document.createElement("div");
this.loadingIconDiv.className="loadingIcon";g.appendChild(this.loadingIconDiv)};this.update=function(a,b){this.scale=a||this.scale;"undefined"!==typeof b&&(this.rotation=b);this.viewport=this.viewport.clone({scale:this.scale*CSS_UNITS,rotation:(this.rotation+this.pdfPageRotate)%360});var c=!1;if(this.canvas&&0<PDFJS.maxCanvasPixels){var d=this.canvas.getContext("2d"),d=getOutputScale(d);Math.sqrt(PDFJS.maxCanvasPixels/(this.viewport.width*this.viewport.height));(Math.floor(this.viewport.width)*d.sx|
0)*(Math.floor(this.viewport.height)*d.sy|0)>PDFJS.maxCanvasPixels&&(c=!0)}this.canvas&&(PDFJS.useOnlyCssZoom||this.hasRestrictedScaling&&c)?this.cssTransform(this.canvas,!0):(this.canvas&&!this.zoomLayer&&(this.zoomLayer=this.canvas.parentNode,this.zoomLayer.style.position="absolute"),this.zoomLayer&&this.cssTransform(this.zoomLayer.firstChild),this.reset(!0))};this.cssTransform=function(a,b){var c=this.viewport.width,d=this.viewport.height;a.style.width=a.parentNode.style.width=g.style.width=Math.floor(c)+
"px";a.style.height=a.parentNode.style.height=g.style.height=Math.floor(d)+"px";var e=this.viewport.rotation-a._viewport.rotation,h=Math.abs(e),q=1,m=1;if(90===h||270===h)q=d/c,m=c/d;CustomStyle.setProp("transform",a,"rotate("+e+"deg) scale("+q+","+m+")");if(this.textLayer){h=this.textLayer.viewport;d=Math.abs(this.viewport.rotation-h.rotation);e=c/h.width;if(90===d||270===d)e=c/h.height;var c=this.textLayer.textLayerDiv,r,p;switch(d){case 0:r=p=0;break;case 90:r=0;p="-"+c.style.height;break;case 180:r=
"-"+c.style.width;p="-"+c.style.height;break;case 270:r="-"+c.style.width;p=0;break;default:console.error("Bad rotation value.")}CustomStyle.setProp("transform",c,"rotate("+d+"deg) scale("+e+", "+e+") translate("+r+", "+p+")");CustomStyle.setProp("transformOrigin",c,"0% 0%")}b&&this.annotationLayer&&f(g,this.pdfPage,this.viewport)};Object.defineProperty(this,"width",{get:function(){return this.viewport.width},enumerable:!0});Object.defineProperty(this,"height",{get:function(){return this.viewport.height},
enumerable:!0});var h=this;this.getPagePoint=function(a,b){return this.viewport.convertToPdfPoint(a,b)};this.scrollIntoView=function(a){if(PresentationMode.active){if(PDFView.page!==this.id){PDFView.page=this.id;return}a=null;PDFView.setScale(PDFView.currentScaleValue,!0,!0)}if(a){var b=0,c=0,d=0,e=0,f,h;h=0===this.rotation%180?!1:!0;f=(h?this.height:this.width)/this.scale/CSS_UNITS;h=(h?this.width:this.height)/this.scale/CSS_UNITS;var m=0;switch(a[1].name){case "XYZ":b=a[2];c=a[3];m=a[4];b=null!==
b?b:0;c=null!==c?c:h;break;case "Fit":case "FitB":m="page-fit";break;case "FitH":case "FitBH":c=a[2];m="page-width";break;case "FitV":case "FitBV":b=a[2];d=f;e=h;m="page-height";break;case "FitR":b=a[2];c=a[3];d=a[4]-b;e=a[5]-c;f=(PDFView.container.clientWidth-SCROLLBAR_PADDING)/d/CSS_UNITS;h=(PDFView.container.clientHeight-SCROLLBAR_PADDING)/e/CSS_UNITS;m=Math.min(Math.abs(f),Math.abs(h));break;default:return}m&&m!==PDFView.currentScale?PDFView.setScale(m,!0,!0):PDFView.currentScale===UNKNOWN_SCALE&&
PDFView.setScale(DEFAULT_SCALE,!0,!0);"page-fit"!==m||a[4]?(b=[this.viewport.convertToViewportPoint(b,c),this.viewport.convertToViewportPoint(b+d,c+e)],a=Math.min(b[0][0],b[1][0]),b=Math.min(b[0][1],b[1][1]),scrollIntoView(g,{left:a,top:b})):scrollIntoView(g)}else scrollIntoView(g)};this.getTextContent=function(){return PDFView.getPage(this.id).then(function(a){return a.getTextContent()})};this.draw=function(a){function b(d){v===p.renderTask&&(p.renderTask=null);if("cancelled"!==d){p.renderingState=
RenderingStates.FINISHED;p.loadingIconDiv&&(g.removeChild(p.loadingIconDiv),delete p.loadingIconDiv);p.zoomLayer&&(g.removeChild(p.zoomLayer),p.zoomLayer=null);d&&PDFView.error(mozL10n.get("rendering_error",null,"An error occurred while rendering the page."),d);p.stats=c.stats;p.updateStats();if(p.onAfterDraw)p.onAfterDraw();d=document.createEvent("CustomEvent");d.initCustomEvent("pagerender",!0,!0,{pageNumber:c.pageNumber});g.dispatchEvent(d);a()}}var c=this.pdfPage;if(!this.pagePdfPromise)if(c){this.renderingState!==
RenderingStates.INITIAL&&console.error("Must be in new state before drawing");this.renderingState=RenderingStates.RUNNING;var d=this.viewport,e=document.createElement("div");e.style.width=g.style.width;e.style.height=g.style.height;e.classList.add("canvasWrapper");var h=document.createElement("canvas");h.id="page"+this.id;e.appendChild(h);this.annotationLayer?g.insertBefore(e,this.annotationLayer):g.appendChild(e);this.canvas=h;var e=h.getContext("2d"),q=getOutputScale(e);if(PDFJS.useOnlyCssZoom){var m=
d.clone({scale:CSS_UNITS});q.sx*=m.width/d.width;q.sy*=m.height/d.height;q.scaled=!0}0<PDFJS.maxCanvasPixels&&(m=Math.sqrt(PDFJS.maxCanvasPixels/(d.width*d.height)),q.sx>m||q.sy>m?(q.sx=m,q.sy=m,this.hasRestrictedScaling=q.scaled=!0):this.hasRestrictedScaling=!1);h.width=Math.floor(d.width)*q.sx|0;h.height=Math.floor(d.height)*q.sy|0;h.style.width=Math.floor(d.width)+"px";h.style.height=Math.floor(d.height)+"px";h._viewport=d;d=null;PDFJS.disableTextLayer||(d=document.createElement("div"),d.className=
"textLayer",d.style.width=h.style.width,d.style.height=h.style.height,this.annotationLayer?g.insertBefore(d,this.annotationLayer):g.appendChild(d));var r=this.textLayer=d?new TextLayerBuilder({textLayerDiv:d,pageIndex:this.id-1,lastScrollSource:PDFView,viewport:this.viewport,isViewerInPresentationMode:PresentationMode.active,findController:PDFView.findController}):null;e._scaleX=q.sx;e._scaleY=q.sy;q.scaled&&e.scale(q.sx,q.sy);var p=this,v=this.renderTask=this.pdfPage.render({canvasContext:e,viewport:this.viewport,
textLayer:r,continueCallback:function(a){PDFView.highestPriorityPage!=="page"+p.id?(p.renderingState=RenderingStates.PAUSED,p.resume=function(){p.renderingState=RenderingStates.RUNNING;a()}):a()}});this.renderTask.promise.then(function(){b(null);r&&p.getTextContent().then(function(a){r.setTextContent(a)})},function(a){b(a)});f(g,c,this.viewport);g.setAttribute("data-loaded",!0);cache.push(this)}else h=PDFView.getPage(this.id),h.then(function(b){delete this.pagePdfPromise;this.setPdfPage(b);this.draw(a)}.bind(this)),
this.pagePdfPromise=h};this.beforePrint=function(){var a=this.pdfPage,b=a.getViewport(1),c=document.createElement("canvas");c.width=2*Math.floor(b.width);c.height=2*Math.floor(b.height);c.style.width=2*b.width+"pt";c.style.height=2*b.height+"pt";CustomStyle.setProp("transform",c,"scale(0.5, 0.5)");CustomStyle.setProp("transformOrigin",c,"0% 0%");var d=document.getElementById("printContainer"),e=document.createElement("div");e.style.width=b.width+"pt";e.style.height=b.height+"pt";e.appendChild(c);
d.appendChild(e);c.mozPrintCallback=function(d){var e=d.context;e.save();e.fillStyle="rgb(255, 255, 255)";e.fillRect(0,0,c.width,c.height);e.restore();e.scale(2,2);a.render({canvasContext:e,viewport:b,intent:"print"}).promise.then(function(){d.done()},function(a){console.error(a);"abort"in d?d.abort():d.done()})}};this.updateStats=function(){this.stats&&PDFJS.pdfBug&&Stats.enabled&&Stats.add(this.id,this.stats)}},ThumbnailView=function(a,b,c){function d(a,b){var c=ThumbnailView.tempImageCache;c||
(c=document.createElement("canvas"),ThumbnailView.tempImageCache=c);c.width=a;c.height=b;return c}var e=document.createElement("a");e.href=PDFView.getAnchorUrl("#page="+b);e.title=mozL10n.get("thumb_page_title",{page:b},"Page {{page}}");e.onclick=function(){PDFView.page=b;return!1};this.pdfPage=void 0;this.viewport=c;this.pdfPageRotate=c.rotation;this.rotation=0;this.pageWidth=this.viewport.width;this.pageHeight=this.viewport.height;this.pageRatio=this.pageWidth/this.pageHeight;this.id=b;this.canvasWidth=
98;this.canvasHeight=this.canvasWidth/this.pageWidth*this.pageHeight;this.scale=this.canvasWidth/this.pageWidth;var f=this.el=document.createElement("div");f.id="thumbnailContainer"+b;f.className="thumbnail";1===b&&f.classList.add("selected");var g=document.createElement("div");g.className="thumbnailSelectionRing";g.style.width=this.canvasWidth+"px";g.style.height=this.canvasHeight+"px";f.appendChild(g);e.appendChild(f);a.appendChild(e);this.hasImage=!1;this.renderingState=RenderingStates.INITIAL;
this.setPdfPage=function(a){this.pdfPage=a;this.pdfPageRotate=a.rotate;this.viewport=a.getViewport(1,(this.rotation+this.pdfPageRotate)%360);this.update()};this.update=function(a){void 0!==a&&(this.rotation=a);this.viewport=this.viewport.clone({scale:1,rotation:(this.rotation+this.pdfPageRotate)%360});this.pageWidth=this.viewport.width;this.pageHeight=this.viewport.height;this.pageRatio=this.pageWidth/this.pageHeight;this.canvasHeight=this.canvasWidth/this.pageWidth*this.pageHeight;this.scale=this.canvasWidth/
this.pageWidth;f.removeAttribute("data-loaded");g.textContent="";g.style.width=this.canvasWidth+"px";g.style.height=this.canvasHeight+"px";this.hasImage=!1;this.renderingState=RenderingStates.INITIAL;this.resume=null};this.getPageDrawContext=function(){var a=document.createElement("canvas");a.id="thumbnail"+b;a.width=this.canvasWidth;a.height=this.canvasHeight;a.className="thumbnailImage";a.setAttribute("aria-label",mozL10n.get("thumb_page_canvas",{page:b},"Thumbnail of Page {{page}}"));f.setAttribute("data-loaded",
!0);g.appendChild(a);a=a.getContext("2d");a.save();a.fillStyle="rgb(255, 255, 255)";a.fillRect(0,0,this.canvasWidth,this.canvasHeight);a.restore();return a};this.drawingRequired=function(){return!this.hasImage};this.draw=function(a){if(this.pdfPage)if(this.renderingState!==RenderingStates.INITIAL&&console.error("Must be in new state before drawing"),this.renderingState=RenderingStates.RUNNING,this.hasImage)a();else{var b=this,c=this.getPageDrawContext(),d=this.viewport.clone({scale:this.scale});this.pdfPage.render({canvasContext:c,
viewport:d,continueCallback:function(a){PDFView.highestPriorityPage!=="thumbnail"+b.id?(b.renderingState=RenderingStates.PAUSED,b.resume=function(){b.renderingState=RenderingStates.RUNNING;a()}):a()}}).promise.then(function(){b.renderingState=RenderingStates.FINISHED;a()},function(c){b.renderingState=RenderingStates.FINISHED;a()});this.hasImage=!0}else PDFView.getPage(this.id).then(function(b){this.setPdfPage(b);this.draw(a)}.bind(this))};this.setImage=function(a){if(!this.pdfPage)PDFView.getPage(this.id).then(function(b){this.setPdfPage(b);
this.setImage(a)}.bind(this));else if(!this.hasImage&&a){this.renderingState=RenderingStates.FINISHED;var b=this.getPageDrawContext(),c=a,e=a.width,f=a.height;if(2<Math.max(a.width/b.canvas.width,a.height/b.canvas.height)){var e=e>>1,f=f>>1,c=d(e,f),g=c.getContext("2d");for(g.drawImage(a,0,0,a.width,a.height,0,0,e,f);2<Math.max(e/b.canvas.width,f/b.canvas.height);)g.drawImage(c,0,0,e,f,0,0,e>>1,f>>1),e>>=1,f>>=1}b.drawImage(c,0,0,e,f,0,0,b.canvas.width,b.canvas.height);this.hasImage=!0}}};
ThumbnailView.tempImageCache=null;var FIND_SCROLL_OFFSET_TOP=-50,FIND_SCROLL_OFFSET_LEFT=-400,MAX_TEXT_DIVS_TO_RENDER=1E5,RENDER_DELAY=200,NonWhitespaceRegexp=/\S/;function isAllWhitespace(a){return!NonWhitespaceRegexp.test(a)}
var TextLayerBuilder=function(){function a(a){this.textLayerDiv=a.textLayerDiv;this.divContentDone=this.layoutDone=!1;this.pageIdx=a.pageIndex;this.matches=[];this.lastScrollSource=a.lastScrollSource||null;this.viewport=a.viewport;this.isViewerInPresentationMode=a.isViewerInPresentationMode;this.textDivs=[];this.findController=a.findController||null}a.prototype={renderLayer:function(){var a=document.createDocumentFragment(),c=this.textDivs,d=c.length,e=document.createElement("canvas").getContext("2d");
if(!(d>MAX_TEXT_DIVS_TO_RENDER)){for(var f,g,h=0;h<d;h++){var k=c[h];if(void 0===k.dataset.isWhitespace){var l=k.style.fontSize,n=k.style.fontFamily;if(l!==f||n!==g)e.font=l+" "+n,f=l,g=n;n=e.measureText(k.textContent).width;0<n&&(a.appendChild(k),l=k.dataset.angle,n="scale("+k.dataset.canvasWidth/n+", 1)",l&&(n="rotate("+l+"deg) "+n),CustomStyle.setProp("transform",k,n))}}this.textLayerDiv.appendChild(a);this.renderingDone=!0;this.updateMatches()}},setupRenderLayoutTimer:function(){var a=this,c=
null===this.lastScrollSource?0:this.lastScrollSource.lastScroll;Date.now()-c>RENDER_DELAY?this.renderLayer():(this.renderTimer&&clearTimeout(this.renderTimer),this.renderTimer=setTimeout(function(){a.setupRenderLayoutTimer()},RENDER_DELAY))},appendText:function(a,c){var d=c[a.fontName],e=document.createElement("div");this.textDivs.push(e);if(isAllWhitespace(a.str))e.dataset.isWhitespace=!0;else{var f=PDFJS.Util.transform(this.viewport.transform,a.transform),g=Math.atan2(f[1],f[0]);d.vertical&&(g+=
Math.PI/2);var h=Math.sqrt(f[2]*f[2]+f[3]*f[3]),k=h;d.ascent?k*=d.ascent:d.descent&&(k*=1+d.descent);var l;0===g?(l=f[4],f=f[5]-k):(l=f[4]+k*Math.sin(g),f=f[5]-k*Math.cos(g));e.style.left=l+"px";e.style.top=f+"px";e.style.fontSize=h+"px";e.style.fontFamily=d.fontFamily;e.textContent=a.str;PDFJS.pdfBug&&(e.dataset.fontName=a.fontName);0!==g&&(e.dataset.angle=180/Math.PI*g);e.dataset.canvasWidth=d.vertical?a.height*this.viewport.scale:a.width*this.viewport.scale}},setTextContent:function(a){this.textContent=
a;for(var c=a.items,d=0,e=c.length;d<e;d++)this.appendText(c[d],a.styles);this.divContentDone=!0;this.setupRenderLayoutTimer()},convertMatches:function(a){for(var c=0,d=0,e=this.textContent.items,f=e.length-1,g=null===this.findController?0:this.findController.state.query.length,h=[],k=0,l=a.length;k<l;k++){for(var n=a[k];c!==f&&n>=d+e[c].str.length;)d+=e[c].str.length,c++;c===e.length&&console.error("Could not find a matching mapping");for(var s={begin:{divIdx:c,offset:n-d}},n=n+g;c!==f&&n>d+e[c].str.length;)d+=
e[c].str.length,c++;s.end={divIdx:c,offset:n-d};h.push(s)}return h},renderMatches:function(a){function c(a,b){var c=a.divIdx;f[c].textContent="";d(c,0,a.offset,b)}function d(a,b,c,d){var g=f[a];a=e[a].str.substring(b,c);a=document.createTextNode(a);d?(b=document.createElement("span"),b.className=d,b.appendChild(a),g.appendChild(b)):g.appendChild(a)}if(0!==a.length){var e=this.textContent.items,f=this.textDivs,g=null,h=null===this.findController?!1:this.pageIdx===this.findController.selected.pageIdx,
k=null===this.findController?-1:this.findController.selected.matchIdx,l=k,n=l+1;if(null===this.findController?0:this.findController.state.highlightAll)l=0,n=a.length;else if(!h)return;for(;l<n;l++){var s=a[l],t=s.begin,s=s.end,x=h&&l===k,q=x?" selected":"";x&&!this.isViewerInPresentationMode&&scrollIntoView(f[t.divIdx],{top:FIND_SCROLL_OFFSET_TOP,left:FIND_SCROLL_OFFSET_LEFT});g&&t.divIdx===g.divIdx?d(g.divIdx,g.offset,t.offset):(null!==g&&d(g.divIdx,g.offset,void 0),c(t));if(t.divIdx===s.divIdx)d(t.divIdx,
t.offset,s.offset,"highlight"+q);else{d(t.divIdx,t.offset,void 0,"highlight begin"+q);g=t.divIdx+1;for(t=s.divIdx;g<t;g++)f[g].className="highlight middle"+q;c(s,"highlight end"+q)}g=s}g&&d(g.divIdx,g.offset,void 0)}},updateMatches:function(){if(this.renderingDone){for(var a=this.matches,c=this.textDivs,d=this.textContent.items,e=-1,f=0,g=a.length;f<g;f++){for(var h=a[f],e=Math.max(e,h.begin.divIdx),k=h.end.divIdx;e<=k;e++){var l=c[e];l.textContent=d[e].str;l.className=""}e=h.end.divIdx+1}null!==
this.findController&&this.findController.active&&(this.matches=this.convertMatches(null===this.findController?[]:this.findController.pageMatches[this.pageIdx]||[]),this.renderMatches(this.matches))}}};return a}(),DocumentOutlineView=function(a){function b(a,b){a.href=PDFView.getDestinationHash(b.dest);a.onclick=function(a){PDFView.navigateTo(b.dest);return!1}}for(var c=document.getElementById("outlineView");c.firstChild;)c.removeChild(c.firstChild);if(a)for(a=[{parent:c,items:a}];0<a.length;){var c=
a.shift(),d,e=c.items.length;for(d=0;d<e;d++){var f=c.items[d],g=document.createElement("div");g.className="outlineItem";var h=document.createElement("a");b(h,f);h.textContent=f.title;g.appendChild(h);0<f.items.length&&(h=document.createElement("div"),h.className="outlineItems",g.appendChild(h),a.push({parent:h,items:f.items}));c.parent.appendChild(g)}}else c.classList.contains("hidden")||PDFView.switchSidebarView("thumbs")},DocumentAttachmentsView=function(a){function b(a,b){a.onclick=function(a){(new DownloadManager).downloadData(b.content,
getFileName(b.filename),"");return!1}}for(var c=document.getElementById("attachmentsView");c.firstChild;)c.removeChild(c.firstChild);if(a)for(var d=Object.keys(a).sort(function(a,b){return a.toLowerCase().localeCompare(b.toLowerCase())}),e=0,f=d.length;e<f;e++){var g=a[d[e]],h=document.createElement("div");h.className="attachmentsItem";var k=document.createElement("button");b(k,g);k.textContent=getFileName(g.filename);h.appendChild(k);c.appendChild(h)}else c.classList.contains("hidden")||PDFView.switchSidebarView("thumbs")};
function webViewerLoad(a){PDFView.initialize().then(webViewerInitialized)}
function webViewerInitialized(){var a=PDFView.parseQueryString(document.location.search.substring(1)),b="file"in a?a.file:DEFAULT_URL,a=document.createElement("input");a.id="fileInput";a.className="fileInput";a.setAttribute("type","file");a.setAttribute("accept",".pdf");a.oncontextmenu=noContextMenuHandler;document.body.appendChild(a);window.File&&window.FileReader&&window.FileList&&window.Blob?document.getElementById("fileInput").value=null:(document.getElementById("openFile").setAttribute("hidden",
"true"),document.getElementById("secondaryOpenFile").setAttribute("hidden","true"));a=document.location.hash.substring(1);a=PDFView.parseQueryString(a);"disableWorker"in a&&(PDFJS.disableWorker="true"===a.disableWorker);"disableRange"in a&&(PDFJS.disableRange="true"===a.disableRange);"disableAutoFetch"in a&&(PDFJS.disableAutoFetch="true"===a.disableAutoFetch);"disableFontFace"in a&&(PDFJS.disableFontFace="true"===a.disableFontFace);"disableHistory"in a&&(PDFJS.disableHistory="true"===a.disableHistory);
"webgl"in a&&(PDFJS.disableWebGL="true"!==a.webgl);"useOnlyCssZoom"in a&&(PDFJS.useOnlyCssZoom="true"===a.useOnlyCssZoom);"verbosity"in a&&(PDFJS.verbosity=a.verbosity|0);"ignoreCurrentPositionOnZoom"in a&&(IGNORE_CURRENT_POSITION_ON_ZOOM="true"===a.ignoreCurrentPositionOnZoom);var c=PDFJS.locale||navigator.language;"locale"in a&&(c=a.locale);mozL10n.setLanguage(c);if("textLayer"in a)switch(a.textLayer){case "off":PDFJS.disableTextLayer=!0;break;case "visible":case "shadow":case "hover":document.getElementById("viewer").classList.add("textLayer-"+
a.textLayer)}"pdfBug"in a&&(PDFJS.pdfBug=!0,a=a.pdfBug.split(","),PDFBug.enable(a),PDFBug.init());PDFView.supportsPrinting||(document.getElementById("print").classList.add("hidden"),document.getElementById("secondaryPrint").classList.add("hidden"));PDFView.supportsFullscreen||(document.getElementById("presentationMode").classList.add("hidden"),document.getElementById("secondaryPresentationMode").classList.add("hidden"));PDFView.supportsIntegratedFind&&document.getElementById("viewFind").classList.add("hidden");
PDFJS.UnsupportedManager.listen(PDFView.fallback.bind(PDFView));document.getElementById("scaleSelect").oncontextmenu=noContextMenuHandler;var d=document.getElementById("mainContainer"),e=document.getElementById("outerContainer");d.addEventListener("transitionend",function(a){a.target===d&&(a=document.createEvent("UIEvents"),a.initUIEvent("resize",!1,!1,window,0),window.dispatchEvent(a),e.classList.remove("sidebarMoving"))},!0);document.getElementById("sidebarToggle").addEventListener("click",function(){this.classList.toggle("toggled");
e.classList.add("sidebarMoving");e.classList.toggle("sidebarOpen");PDFView.sidebarOpen=e.classList.contains("sidebarOpen");PDFView.renderHighestPriority()});document.getElementById("viewThumbnail").addEventListener("click",function(){PDFView.switchSidebarView("thumbs")});document.getElementById("viewOutline").addEventListener("click",function(){PDFView.switchSidebarView("outline")});document.getElementById("viewAttachments").addEventListener("click",function(){PDFView.switchSidebarView("attachments")});
document.getElementById("previous").addEventListener("click",function(){PDFView.page--});document.getElementById("next").addEventListener("click",function(){PDFView.page++});document.getElementById("zoomIn").addEventListener("click",function(){PDFView.zoomIn()});document.getElementById("zoomOut").addEventListener("click",function(){PDFView.zoomOut()});document.getElementById("pageNumber").addEventListener("click",function(){this.select()});document.getElementById("pageNumber").addEventListener("change",
function(){PDFView.page=this.value|0;this.value!==(this.value|0).toString()&&(this.value=PDFView.page)});document.getElementById("scaleSelect").addEventListener("change",function(){PDFView.setScale(this.value)});document.getElementById("presentationMode").addEventListener("click",SecondaryToolbar.presentationModeClick.bind(SecondaryToolbar));document.getElementById("openFile").addEventListener("click",SecondaryToolbar.openFileClick.bind(SecondaryToolbar));document.getElementById("print").addEventListener("click",
function(){alert("Sorry, not supported yet.")});document.getElementById("download").addEventListener("click",SecondaryToolbar.downloadClick.bind(SecondaryToolbar));if(b&&0===b.lastIndexOf("file:",0)){PDFView.setTitleUsingUrl(b);var f=new XMLHttpRequest;f.onload=function(){PDFView.open(new Uint8Array(f.response),0)};try{f.open("GET",b),f.responseType="arraybuffer",f.send()}catch(g){PDFView.error(mozL10n.get("loading_error",null,"An error occurred while loading the PDF."),g)}}else b&&((a=PDFView.parseQueryString(document.location.search))&&
a.title?PDFView.open(b,0,null,null,null,a.title):PDFView.open(b,0))}document.addEventListener("DOMContentLoaded",webViewerLoad,!0);
function updateViewarea(){if(PDFView.initialized){var a=PDFView.getVisiblePages(),b=a.views;if(0!==b.length){var c=Math.max(DEFAULT_CACHE_SIZE,2*b.length+1);cache.resize(c);PDFView.renderHighestPriority(a);for(var c=PDFView.page,a=a.first,d=0,e=b.length,f=!1;d<e;++d){var g=b[d];if(100>g.percent)break;if(g.id===PDFView.page){f=!0;break}}f||(c=b[0].id);PresentationMode.active||(updateViewarea.inProgress=!0,PDFView.page=c,updateViewarea.inProgress=!1);var b=PDFView.currentScale,c=PDFView.currentScaleValue,
h=parseFloat(c)===b?Math.round(1E4*b)/100:c,k=a.id,b="#page="+k+("&zoom="+h),c=PDFView.container,a=PDFView.pages[k-1].getPagePoint(c.scrollLeft-a.x,c.scrollTop-a.y),l=Math.round(a[0]),n=Math.round(a[1]),b=b+(","+l+","+n);PDFView.currentPosition=PresentationMode.active||PresentationMode.switchInProgress?null:{page:k,left:l,top:n};PDFView.store.initializedPromise.then(function(){PDFView.store.setMultiple({exists:!0,page:k,zoom:h,scrollLeft:l,scrollTop:n}).catch(function(){})});a=PDFView.getAnchorUrl(b);
document.getElementById("viewBookmark").href=a;document.getElementById("secondaryViewBookmark").href=a;PDFHistory.updateCurrentBookmark(b,k)}}}window.addEventListener("resize",function(a){PDFView.initialized&&(document.getElementById("pageWidthOption").selected||document.getElementById("pageFitOption").selected||document.getElementById("pageAutoOption").selected)&&PDFView.setScale(document.getElementById("scaleSelect").value);updateViewarea();SecondaryToolbar.setMaxHeight(PDFView.container)});
window.addEventListener("hashchange",function(a){PDFHistory.isHashChangeUnlocked&&PDFView.setHash(document.location.hash.substring(1))});
window.addEventListener("change",function(a){if((a=a.target.files)&&0!==a.length){a=a[0];if(!PDFJS.disableCreateObjectURL&&"undefined"!==typeof URL&&URL.createObjectURL)PDFView.open(URL.createObjectURL(a),0);else{var b=new FileReader;b.onload=function(a){a=new Uint8Array(a.target.result);PDFView.open(a,0)};b.readAsArrayBuffer(a)}PDFView.setTitleUsingUrl(a.name);document.getElementById("viewBookmark").setAttribute("hidden","true");document.getElementById("secondaryViewBookmark").setAttribute("hidden",
"true")}},!0);function selectScaleOption(a){for(var b=document.getElementById("scaleSelect").options,c=!1,d=0;d<b.length;d++){var e=b[d];e.value!==a?e.selected=!1:c=e.selected=!0}return c}
window.addEventListener("localized",function(a){document.getElementsByTagName("html")[0].dir=mozL10n.getDirection();PDFView.animationStartedPromise.then(function(){var a=document.getElementById("scaleSelectContainer");if(0<a.clientWidth){var c=document.getElementById("scaleSelect");c.setAttribute("style","min-width: inherit;");var d=c.clientWidth+SCALE_SELECT_CONTAINER_PADDING;c.setAttribute("style","min-width: "+(d+SCALE_SELECT_PADDING)+"px;");a.setAttribute("style","min-width: "+d+"px; max-width: "+
d+"px;")}SecondaryToolbar.setMaxHeight(PDFView.container)})},!0);
window.addEventListener("scalechange",function(a){document.getElementById("zoomOut").disabled=a.scale===MIN_SCALE;document.getElementById("zoomIn").disabled=a.scale===MAX_SCALE;var b=document.getElementById("customScaleOption");b.selected=!1;!a.resetAutoSettings&&(document.getElementById("pageWidthOption").selected||document.getElementById("pageFitOption").selected||document.getElementById("pageAutoOption").selected)||selectScaleOption(""+a.scale)||(b.textContent=Math.round(1E4*a.scale)/100+"%",b.selected=
!0);updateViewarea()},!0);
window.addEventListener("pagechange",function(a){a=a.pageNumber;if(PDFView.previousPageNumber!==a){document.getElementById("pageNumber").value=a;var b=document.querySelector(".thumbnail.selected");b&&b.classList.remove("selected");b=document.getElementById("thumbnailContainer"+a);b.classList.add("selected");var c=PDFView.getVisibleThumbs(),d=c.views.length;if(0<d){var e=c.first.id,c=1<d?c.last.id:e;(a<=e||a>=c)&&scrollIntoView(b,{top:THUMBNAIL_SCROLL_MARGIN})}}b=PDFView.pages.length;document.getElementById("previous").disabled=
1>=a;document.getElementById("next").disabled=a>=b;document.getElementById("firstPage").disabled=1>=a;document.getElementById("lastPage").disabled=a>=b},!0);function handleMouseWheel(a){var b="DOMMouseScroll"===a.type?-a.detail:a.wheelDelta/40,c=0>b?"zoomOut":"zoomIn";a.ctrlKey?(a.preventDefault(),PDFView[c](Math.abs(b))):PresentationMode.active&&PDFView.mouseScroll(40*b)}window.addEventListener("DOMMouseScroll",handleMouseWheel);window.addEventListener("mousewheel",handleMouseWheel);
window.addEventListener("click",function(a){PresentationMode.active?0===a.button&&a.preventDefault():SecondaryToolbar.opened&&PDFView.container.contains(a.target)&&SecondaryToolbar.close()},!1);
window.addEventListener("keydown",function(a){if(!OverlayManager.active){var b=!1,c=(a.ctrlKey?1:0)|(a.altKey?2:0)|(a.shiftKey?4:0)|(a.metaKey?8:0);if(1===c||8===c||5===c||12===c)switch(a.keyCode){case 70:PDFView.supportsIntegratedFind||(PDFView.findBar.open(),b=!0);break;case 71:PDFView.supportsIntegratedFind||(PDFView.findBar.dispatchEvent("again",5===c||12===c),b=!0);break;case 61:case 107:case 187:case 171:PDFView.zoomIn();b=!0;break;case 173:case 109:case 189:PDFView.zoomOut();b=!0;break;case 48:case 96:setTimeout(function(){PDFView.setScale(DEFAULT_SCALE,
!0)}),b=!1}if(1===c||8===c)switch(a.keyCode){case 83:PDFView.download(),b=!0}if(3===c||10===c)switch(a.keyCode){case 80:SecondaryToolbar.presentationModeClick();b=!0;break;case 71:document.getElementById("pageNumber").select(),b=!0}if(b)a.preventDefault();else{var d=document.activeElement||document.querySelector(":focus"),e=d&&d.tagName.toUpperCase();if("INPUT"!==e&&"TEXTAREA"!==e&&"SELECT"!==e||27===a.keyCode){if(0===c)switch(a.keyCode){case 38:case 33:case 8:if(!PresentationMode.active&&"page-fit"!==
PDFView.currentScaleValue)break;case 37:if(PDFView.isHorizontalScrollbarEnabled)break;case 75:case 80:PDFView.page--;b=!0;break;case 27:SecondaryToolbar.opened&&(SecondaryToolbar.close(),b=!0);!PDFView.supportsIntegratedFind&&PDFView.findBar.opened&&(PDFView.findBar.close(),b=!0);break;case 40:case 34:case 32:if(!PresentationMode.active&&"page-fit"!==PDFView.currentScaleValue)break;case 39:if(PDFView.isHorizontalScrollbarEnabled)break;case 74:case 78:PDFView.page++;b=!0;break;case 36:if(PresentationMode.active||
1<PDFView.page)PDFView.page=1,b=!0;break;case 35:if(PresentationMode.active||PDFView.pdfDocument&&PDFView.page<PDFView.pdfDocument.numPages)PDFView.page=PDFView.pdfDocument.numPages,b=!0;break;case 72:PresentationMode.active||HandTool.toggle();break;case 82:PDFView.rotatePages(90)}if(4===c)switch(a.keyCode){case 32:if(!PresentationMode.active&&"page-fit"!==PDFView.currentScaleValue)break;PDFView.page--;b=!0;break;case 82:PDFView.rotatePages(-90)}b||PresentationMode.active||(33<=a.keyCode&&40>=a.keyCode&&
!PDFView.container.contains(d)&&PDFView.container.focus(),32===a.keyCode&&"BUTTON"!==e&&(PDFView.container.contains(d)||PDFView.container.focus()));if(2===c)switch(a.keyCode){case 37:PresentationMode.active&&(PDFHistory.back(),b=!0);break;case 39:PresentationMode.active&&(PDFHistory.forward(),b=!0)}b&&(a.preventDefault(),PDFView.clearMouseScrollState())}}}});window.addEventListener("beforeprint",function(a){PDFView.beforePrint()});window.addEventListener("afterprint",function(a){PDFView.afterPrint()});
(function(){PDFView.animationStartedPromise=new Promise(function(a){window.requestAnimationFrame(a)})})();
