function setstorage(a,b){window.localStorage&&(localStorage[a]=b+"")}function getstorage(a){var b;window.localStorage&&(b=localStorage[a]);return b}
function number_format(a,b,c,d){a=(a+"").replace(/[^0-9+\-Ee.]/g,"");a=isFinite(+a)?+a:0;b=isFinite(+b)?Math.abs(b):0;d="undefined"===typeof d?",":d;c="undefined"===typeof c?".":c;var e="",e=function(a,c){var b=Math.pow(10,c);return""+Math.round(a*b)/b},e=(b?e(a,b):""+Math.round(a)).split(".");3<e[0].length&&(e[0]=e[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,d));(e[1]||"").length<b&&(e[1]=e[1]||"",e[1]+=Array(b-e[1].length+1).join("0"));return e.join(c)}
function getWindowWidth(){var a=0;if("number"==typeof window.innerWidth)a=window.innerWidth;else var a=document.documentElement.clientWidth,b=document.body.clientWidth,a=0<a?a:b;a||(a=0);return a}function getWindowHeight(){var a=0;if("number"==typeof window.innerHeight)a=window.innerHeight;else var a=document.documentElement.clientHeight,b=document.body.clientHeight,a=0<a?a:b;a||(a=0);return a}
function getScrollLeft(){var a;document.body&&document.body.scrollLeft?a=document.body.scrollLeft:document.documentElement&&document.documentElement.scrollLeft&&(a=document.documentElement.scrollLeft);a||(a=0);return a}function getScrollTop(){var a;document.body&&document.body.scrollTop?a=document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop&&(a=document.documentElement.scrollTop);a||(a=0);return a}
function getOffset(a,b){for(var c=0,d=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)c+=a.offsetLeft,d+=a.offsetTop,a=a.offsetParent;if(b)for(b2=b.target;b2&&!isNaN(b2.scrollLeft)&&!isNaN(b2.scrollTop)&&b2!=document.body;)c-=b2.scrollLeft,d-=b2.scrollTop,b2=b2.parentElement?b2.parentElement:b2.parentNode;return{left:c,top:d}}function _getid(a){return document.getElementById(a)}function trim(a){return a.replace(/^\s*|\s*$/g,"")}function makequeryescape(a){return a=a.replace(/&/gi,"%26")}
function html_entity_decode(a){a=a.replace(/&amp;/gi,"&");a=a.replace(/&gt;/gi,">");a=a.replace(/&lt;/gi,"<");a=a.replace(/&quot;/gi,'"');return a=a.replace(/&#039;/gi,"'")}function html_entity_encode(a){a=(a||"").replace(/&/gi,"&amp;");a=a.replace(/>/gi,"&gt;");a=a.replace(/</gi,"&lt;");a=a.replace(/\"/gi,"&quot;");a=a.replace(/\'/gi,"&#039;");return a=a.replace(/\r\n|\n/g,"<br>")}
function html_entity_encode_org(a){a=(a||"").replace(/&/gi,"&amp;");a=a.replace(/>/gi,"&gt;");a=a.replace(/</gi,"&lt;");a=a.replace(/\"/gi,"&quot;");return a=a.replace(/\'/gi,"&#039;")}function addCommas(a){x=(a+"").split(".");x1=x[0];x2=1<x.length?"."+x[1]:"";for(a=/(\d+)(\d{3})/;a.test(x1);)x1=x1.replace(a,"$1,$2");return x1+x2}function toBool(a){return"boolean"==typeof a?a:"false"===a?!1:!0}
function sprintf(){var a=arguments,b=0,c=function(a,c,b,d){b||(b=" ");c=a.length>=c?"":Array(1+c-a.length>>>0).join(b);return d?a+c:c+a},d=function(a,b,d,e,m,k){var l=e-a.length;0<l&&(a=d||!m?c(a,e,k,d):a.slice(0,b.length)+c("",l,"0",!0)+a.slice(b.length));return a},e=function(a,b,e,h,m,k,l){a>>>=0;e=e&&a&&{2:"0b",8:"0",16:"0x"}[b]||"";a=e+c(a.toString(b),k||0,"0",!1);return d(a,e,h,m,l)};return a[b++].replace(/%%|%(\d+\$)?([-+\'#0 ]*)(\*\d+\$|\*|\d+)?(\.(\*\d+\$|\*|\d+))?([scboxXuidfegEG])/g,function(f,
g,r,h,m,k,l){var p,q;if("%%"==f)return"%";var n=!1;q="";var t=m=!1;p=" ";for(var v=r.length,u=0;r&&u<v;u++)switch(r.charAt(u)){case " ":q=" ";break;case "+":q="+";break;case "-":n=!0;break;case "'":p=r.charAt(u+1);break;case "0":m=!0;break;case "#":t=!0}h=h?"*"==h?+a[b++]:"*"==h.charAt(0)?+a[h.slice(1,-1)]:+h:0;0>h&&(h=-h,n=!0);if(!isFinite(h))throw Error("sprintf: (minimum-)width must be finite");k=k?"*"==k?+a[b++]:"*"==k.charAt(0)?+a[k.slice(1,-1)]:+k:-1<"fFeE".indexOf(l)?6:"d"==l?0:void 0;g=g?
a[g.slice(0,-1)]:a[b++];switch(l){case "s":return l=String(g),null!=k&&(l=l.slice(0,k)),d(l,"",n,h,m,p);case "c":return l=String.fromCharCode(+g),null!=k&&(l=l.slice(0,k)),d(l,"",n,h,m,void 0);case "b":return e(g,2,t,n,h,k,m);case "o":return e(g,8,t,n,h,k,m);case "x":return e(g,16,t,n,h,k,m);case "X":return e(g,16,t,n,h,k,m).toUpperCase();case "u":return e(g,10,t,n,h,k,m);case "i":case "d":return p=parseInt(+g,10),f=0>p?"-":q,g=f+c(String(Math.abs(p)),k,"0",!1),d(g,f,n,h,m);case "e":case "E":case "f":case "F":case "g":case "G":return p=
+g,f=0>p?"-":q,q=["toExponential","toFixed","toPrecision"]["efg".indexOf(l.toLowerCase())],l=["toString","toUpperCase"]["eEfFgG".indexOf(l)%2],g=f+Math.abs(p)[q](k),d(g,f,n,h,m)[l]();default:return f}})}function get_shorturl(a){try{if(a&&a.trim()){var b=a.trim(),c=b.indexOf("//"),c=-1==c?0:c+2;if(c<b.length){var d=b.indexOf("?",c);-1==d&&(d=b.lastIndexOf("/"),-1==d||d<=c)&&(d=b.length);var e=b.substring(c,d);e&&-1!=e.indexOf(".")||(e="")}}}catch(f){}return e}
Date.prototype.setISO8601=function(a){if(a=a.match("^([-+]?)(\\d{4,})(?:-?(\\d{2})(?:-?(\\d{2})(?:[Tt ](\\d{2})(?::?(\\d{2})(?::?(\\d{2})(?:\\.(\\d{1,3})(?:\\d+)?)?)?)?(?:[Zz]|(?:([-+])(\\d{2})(?::?(\\d{2}))?)?)?)?)?)?$")){for(var b=[2,3,4,5,6,7,8,10,11],c=b.length-1;0<=c;--c)a[b[c]]="undefined"!=typeof a[b[c]]&&0<a[b[c]].length?parseInt(a[b[c]],10):0;"-"==a[1]&&(a[2]*=-1);b=Date.UTC(a[2],a[3],a[4],a[5],a[6],a[7],a[8]);"undefined"!=typeof a[9]&&0<a[9].length&&(b+=("+"==a[9]?-1:1)*(36E5*a[10]+6E4*
a[11]));0<=a[2]&&99>=a[2]&&(b-=59958144E6);this.setTime(b);return this}return null};function getValue(a,b,c){b=b.toLowerCase();c=c.toLowerCase();ss=a.toLowerCase();p1=ss.indexOf(b);if(!(0>p1||(s1=a.substr(p1+b.length,a.length),ss=s1.toLowerCase(),p1=ss.indexOf(c),0>p1)))return s1=s1.substr(0,p1)}function get_chrome_major_version(){var a=navigator.userAgent,a=getValue(a,"Chrome/"," ");null==a&&(a="");var a=a.split("."),b=0;0<a.length&&(b=parseInt(a[0]));isNaN(b)&&(b=0);return b}var messagetimer=null;
function show_message(a,b,c,d){b||(b=10);c||(c=10);d||(d=5);var e=1,f=document.getElementById("layer_message");if(!f)if(f=document.getElementById("layer_message2"))e=2;else{f=document.getElementById("layer_message3");if(!f)return;e=3}f.style.left="1px";f.style.top="1px";f.innerHTML="<label2>"+a+"</label2>";f.style.display="";1==e?(a=_getid("maintable"))?(c=getOffset(a),b=c.left+10,c=c.top+10,b<getScrollLeft()&&(b=getScrollLeft()),c<getScrollTop()&&(c=getScrollTop())):(b=getScrollLeft()+b,c=getScrollTop()+
c):2==e?(b=getScrollLeft()+(getWindowWidth()-f.clientWidth)/2,c=getScrollTop()+(getWindowHeight()-f.clientHeight)/2):(b=document.body.offsetWidth-f.clientWidth-5,c=getScrollTop()+c);b=parseInt(b);c=parseInt(c);f.style.left=b+"px";f.style.top=c+"px";f.style["background-color"]="#FFFFE1";f.style.border="1px solid #000000";f.style.padding=d+"px";messagetimer&&clearTimeout(messagetimer);messagetimer=setTimeout("hide_message()",2E3)}
function hide_message(){var a=document.getElementById("layer_message");a&&(a.style.display="none");if(a=document.getElementById("layer_message2"))a.style.display="none";if(a=document.getElementById("layer_message3"))a.style.display="none"}function r13(a){for(var b=[],c,d=a.length,e="a".charCodeAt(),f=e+26,g="A".charCodeAt(),r=g+26;d--;)c=a.charCodeAt(d),b[d]=c>=e&&c<f?String.fromCharCode((c-e+13)%26+e):c>=g&&c<r?String.fromCharCode((c-g+13)%26+g):a.charAt(d);return b.join("")}
function changebox(a){if((a=a.previousSibling)&&"checkbox"==a.type){a.checked=!a.checked;if(a.onchange)a.onchange();if(a.onclick)a.onclick()}}function changeboxbyid(a){if((a=document.getElementById(a))&&"checkbox"==a.type){a.checked=!a.checked;if(a.onchange)a.onchange();if(a.onclick)a.onclick()}}
function regex_decode(a){a=a.replace(/\\/gi,"\\\\");a=a.replace(/\^/gi,"\\^");a=a.replace(/\$/gi,"\\$");a=a.replace(/\*/gi,"\\*");a=a.replace(/\+/gi,"\\+");a=a.replace(/\?/gi,"\\?");a=a.replace(/\./gi,"\\.");a=a.replace(/\(/gi,"\\(");a=a.replace(/\)/gi,"\\)");a=a.replace(/\|/gi,"\\|");a=a.replace(/\{/gi,"\\{");a=a.replace(/\}/gi,"\\}");a=a.replace(/\[/gi,"\\[");return a=a.replace(/\]/gi,"\\]")}
function open_currenttab(a,b,c){chrome.windows.getLastFocused(function(d){chrome.tabs.getSelected(d.id,function(d){chrome.tabs.update(d.id,{url:a,selected:b});null!=c&&c()})})}
var en_h="rRseEfaqQtTdwWczxvg",reg_h="["+en_h+"]",en_b={k:0,o:1,i:2,O:3,j:4,p:5,u:6,P:7,h:8,hk:9,ho:10,hl:11,y:12,n:13,nj:14,np:15,nl:16,b:17,m:18,ml:19,l:20},reg_b="hk|ho|hl|nj|np|nl|ml|k|o|i|O|j|p|u|P|h|y|n|b|m|l",en_f={"":0,r:1,R:2,rt:3,s:4,sw:5,sg:6,e:7,f:8,fr:9,fa:10,fq:11,ft:12,fx:13,fv:14,fg:15,a:16,q:17,qt:18,t:19,T:20,d:21,w:22,c:23,z:24,x:25,v:26,g:27},reg_f="rt|sw|sg|fr|fa|fq|ft|fx|fv|fg|qt|r|R|s|e|f|a|q|t|T|d|w|c|z|x|v|g|";
function tokorean(a){return a.replace(new RegExp("("+reg_h+")("+reg_b+")((?:"+reg_f+")(?=(?:"+reg_h+")(?:"+reg_b+"))|(?:"+reg_f+"))","g"),tokorean_replace)}function tokorean_replace(a,b,c,d){return String.fromCharCode(588*en_h.indexOf(b)+28*en_b[c]+en_f[d]+44032)}function ishangul(a){return-1==escape(a).search(/%u/i)?!1:!0}
function getparam(a,b){b=(b+"=").toLowerCase();var c=a.toLowerCase().indexOf(b);if(0>c)return"";a=a.substr(c+b.length);c=a.toLowerCase().indexOf("&");return 0<=c?a.substr(0,c):a}function fillnumber(a){a=String(a);return 1==a.length?"0"+a:a}function isurl_links(a){return/^(?:(ftp|http|https):\/\/)?(?:[\w-]+\.)+[a-z]{2,6}/i.test(a)}function cutstring(a,b){for(var c=0,d=0;d<a.length;d++)if(c=ishangul(a[d])?c+2:c+1,c>=b)return a.substr(0,d);return a}function _i18n(a){return bg_i18n(a)}
function proc_spell_getlang(a,b){var c=bg_i18n(a);c||(c=b);return c}
var g_optionsurl="?action=option",default_maxwordlength=3E5,storagedefault={other_ko_spellcontextmenu:[!0,0],other_ko_spellopentype:[0,0],other_ko_spellwinpos:['{"left":0, "top":0, "width":0, "height":0}',0],other_ko_spellautoclose:[!1,0],other_ko_spellchangeall:[!1,0],other_ko_autocorrection:[!1,0],other_ko_spell_lang:["",0],other_maxwidth:[900,1],other_newtablast:[!1,0],other_ko_showdesc:[!0,0],prev_hotkey:["",0],prev_hotkey2:[117,0],next_hotkey:["",0],next_hotkey2:[118,0],sourcechange_hotkey:["",
0],sourcechange_hotkey2:[119,0],suggestchange_hotkey:["",0],suggestchange_hotkey2:[120,0],textchange_hotkey:["",0],textchange_hotkey2:[121,0],gospell_hotkey:["",0],gospell_hotkey2:[113,0],copytext_hotkey:["ctrl",0],copytext_hotkey2:[117,0],adduserdic_hotkey:["ctrl",0],adduserdic_hotkey2:[118,0],color_corrected:["008000",0],color_changed:["0000FF",0],color_userdic:["0A59A8",0],color_select:["FFFF00",0],last_savedata:["",0],last_spelldata:["",0],user_dic_data:["{}",0],extension_lastcheck:[0,0],extension_version:["",
0],etc_maxwordlength:[default_maxwordlength,0]};function setStorageDefaults2(a){var b=localStorage[a];if(null==b||"undefined"==b)localStorage[a]=storagedefault[a][0]}function setStorageDefaults_int(a){var b=localStorage[a];if(null==b||isNaN(parseInt(b))||"undefined"==b)localStorage[a]=storagedefault[a][0]}function getStorageDefaults(a){return storagedefault[a][0]}function setStorageDefaults(){for(var a in storagedefault)1==storagedefault[a][1]?setStorageDefaults_int(a):setStorageDefaults2(a)}try{setStorageDefaults()}catch(a){}
function bg_request(a){switch(a.type){case "set":localStorage[a.key]=a.value;break;case "get":return s=localStorage[a.key],null!=a.value&&null==s&&(s=a.value),s;case "getdefault":return getStorageDefaults(a.key);case "closecurrenttab":window.close();break;case "saveoptall":for(var b=0;b<a.data.length;b++){var c=a.data[b];"other_ko_spellcontextmenu"==c.name&&toBool(localStorage.other_ko_spellcontextmenu);localStorage[c.name]=c.value}setStorageDefaults();break;case "get_bgstorage":a.setdefault&&setStorageDefaults();
a={};for(c in storagedefault){if("extension_lastcheck"==c)break;"last_savedata"!=c&&"last_spelldata"!=c&&(a[c]=localStorage[c])}c={};c.bgstorage=a;c.g_enspellurl=r13(gsdata.url||"");c.g_optionsurl=g_optionsurl;c.ko_spellcheck_text="";c.maxwordlength=parseInt(localStorage.etc_maxwordlength);if(!c.maxwordlength||isNaN(c.maxwordlength)||1E3>c.maxwordlength)c.maxwordlength=default_maxwordlength;return c;case "open_tabexist":window.open(a.surl)}}
var gsdata={},i18n_en={locale:{message:"en"},ext_description:{message:"Spell Checker extension for Chrome. It's easy to use and fast. This extension supports 12 languages for spell check."},ext_name:{message:"Spell Checker for Chrome"},msg_spellcheck:{message:"Spell Check"},msg_changeall:{message:"Change all"},msg_changealldesc:{message:"Change all of the same source"},msg_change:{message:"Change"},msg_autoclosewin:{message:"Auto close this window"},msg_autoclosewindesc:{message:"Auto close this window after change"},
msg_prev:{message:"Prev"},msg_next:{message:"Next"},msg_gospellcheck:{message:"Go! Spell check"},msg_copytext:{message:"Copy text"},msg_close:{message:"Close"},msg_openeditwindow:{message:"Open edit window"},msg_source:{message:"Source"},msg_current:{message:"Current"},msg_suggest:{message:"Suggest"},msg_manual:{message:"Manual"},msg_wait:{message:"Wait"},msg_nodata:{message:"No data"},msg_notfound:{message:"Spell check Completed. Spelling errors were not found."},msg_spellanalysis:{message:"Spell Check Analysis"},
msg_desc:{message:"Show description"},msg_notselected:{message:"There are no chose."},msg_noinput:{message:"No data entered."},msg_first:{message:"It's first."},msg_last:{message:"It's last."},msg_ratedesc:{message:"If you like it, appreciate if you'd rate it with 5 star and tell your friends."},msg_ratethisitem:{message:"Rate this extension"},msg_opentype:{message:"Spell checker opentype"},msg_open_poswindow:{message:"Open in position window"},msg_open_newtab:{message:"Open in new tab"},msg_open_existtab:{message:"Open in exist new tab"},
msg_open_newwindow:{message:"Open in new window"},msg_open_current:{message:"Open in current tab"},conf_save:{message:"Save"},conf_saved:{message:"Has been saved"},conf_notsaved:{message:"Has not been saved"},conf_setdefault:{message:"Set Default"},msg_option:{message:"Options"},conf_enable:{message:"Enable"},msg_contextmenu:{message:"Chrome Context Menu"},msg_opennewtablast:{message:"Create new tab on the far right position"},msg_maxwidth:{message:"Max width of spell checker area"},msg_maxword:{message:"More than %s characters is truncated."},
msg_error:{message:"Error has occurred."},msg_shortcut:{message:"Shortcuts"},conf_none:{message:"None"},msg_load:{message:"Load"},msg_loadcomplete:{message:"Data has been loaded."},msg_areyousure:{message:"Are you sure?"},msg_color:{message:"Color"},msg_correctcolor:{message:"Corrected word color"},msg_changecolor:{message:"Changed word color"},msg_userdictionary:{message:"User dictionary"},msg_add:{message:"Add"},msg_edit:{message:"Edit"},msg_delete:{message:"Delete"},msg_addtouserdic:{message:"Add to user dictionary"},
msg_deletefromuserdic:{message:"Delete from user dictionary"},msg_sort:{message:"Sort"},msg_unsort:{message:"Cancel sort"},msg_copyclipboard:{message:'Please copy to the clipboard. Press "Ctrl+C" or "Apple Key+C"'},msg_suggestedlang:{message:"Suggested language"},msg_selectcolor:{message:"Selected color"},msg_nosuggest:{message:"No suggest"},msg_toolong:{message:"Data is too long. The latter part of the data was canceled."},msg_wrongword:{message:"Contains an invalid character (%s)."},msg_autocorrection:{message:"Auto correction"},
msg_stop:{message:"Stop"}};function bg_i18n(a){var b="";i18n_en[a]&&(b=i18n_en[a].message||"");return b};