var supportlang=[["da","Danish"],["nl","Dutch"],["en","English"],["fi","Finnish"],["fr","French"],["de","German"],["it","Italian"],["ko","Korean"],["pl","Polish"],["pt","Portuguese"],["ru","Russian"],["es","Spanish"],["sv","Swedish"]],bgstorage,g_config,g_enspellurl,ko_spellcheck_text,g_uniqid=getparamfromurl(location.href,"id"),g_maxwordlength;
function proc_get_start_data(b){b||(b=0);if(!(30<b)){var a=bg_request({type:"get_bgstorage",setdefault:!0,id:g_uniqid});a?(bgstorage=a.bgstorage,g_enspellurl=a.g_enspellurl,g_optionsurl=a.g_optionsurl,ko_spellcheck_text=a.ko_spellcheck_text,g_maxwordlength=a.maxwordlength,start()):(b++,setTimeout(function(){proc_get_start_data(b)},300))}}function proc_set_bgstorage(b,a){bgstorage[b]=a;bg_request({type:"set",key:b,value:a})}
function get_actionkey(b,a){var c="";"ctrl+shift"==b?c="Ctrl+Shift+":"ctrl+alt"==b?c="Ctrl+Alt+":"ctrl"==b?c="Ctrl+":"alt"==b?c="Alt+":"shift"==b&&(c="Shift+");c=65<=a&&90>=a?c+String.fromCharCode(a):112<=a&&121>=a?c+"F"+(a-111):48<=a&&57>=a?c+String.fromCharCode(a):188<=a&&191>=a?c+String.fromCharCode(a-188+44):219<=a&&221>=a?c+String.fromCharCode(a-219+91):37==a?c+"Left":38==a?c+"Up":39==a?c+"Right":40==a?c+"Down":33==a?c+"PageUp":34==a?c+"PageDown":35==a?c+"End":36==a?c+"Home":"";""==c&&(c=bg_i18n("conf_none"));
return c}
function start(){try{g_config=new function(){this.prev_hotkey=bgstorage.prev_hotkey.toLowerCase();this.prev_hotkey2=bgstorage.prev_hotkey2;this.prev_hotkey_name=get_actionkey(this.prev_hotkey,this.prev_hotkey2);this.next_hotkey=bgstorage.next_hotkey.toLowerCase();this.next_hotkey2=bgstorage.next_hotkey2;this.next_hotkey_name=get_actionkey(this.next_hotkey,this.next_hotkey2);this.sourcechange_hotkey=bgstorage.sourcechange_hotkey.toLowerCase();this.sourcechange_hotkey2=bgstorage.sourcechange_hotkey2;this.sourcechange_hotkey_name=
get_actionkey(this.sourcechange_hotkey,this.sourcechange_hotkey2);this.suggestchange_hotkey=bgstorage.suggestchange_hotkey.toLowerCase();this.suggestchange_hotkey2=bgstorage.suggestchange_hotkey2;this.suggestchange_hotkey_name=get_actionkey(this.suggestchange_hotkey,this.suggestchange_hotkey2);this.textchange_hotkey=bgstorage.textchange_hotkey.toLowerCase();this.textchange_hotkey2=bgstorage.textchange_hotkey2;this.textchange_hotkey_name=get_actionkey(this.textchange_hotkey,this.textchange_hotkey2);
this.gospell_hotkey=bgstorage.gospell_hotkey.toLowerCase();this.gospell_hotkey2=bgstorage.gospell_hotkey2;this.gospell_hotkey_name=get_actionkey(this.gospell_hotkey,this.gospell_hotkey2);this.copytext_hotkey=bgstorage.copytext_hotkey.toLowerCase();this.copytext_hotkey2=bgstorage.copytext_hotkey2;this.copytext_hotkey_name=get_actionkey(this.copytext_hotkey,this.copytext_hotkey2);this.adduserdic_hotkey=bgstorage.adduserdic_hotkey.toLowerCase();this.adduserdic_hotkey2=bgstorage.adduserdic_hotkey2;this.adduserdic_hotkey_name=
get_actionkey(this.adduserdic_hotkey,this.adduserdic_hotkey2);this.color_corrected="#"+bgstorage.color_corrected;this.color_changed="#"+bgstorage.color_changed;this.color_userdic="#"+bgstorage.color_userdic;this.color_select="#"+bgstorage.color_select}}catch(b){}try{proc_setlang()}catch(b){}try{user_dic_data=JSON.parse(bgstorage.user_dic_data)}catch(b){}init()}
window.addEventListener("message",function(b){if(b.source==window&&(b=b.data,b.type))if("bg_proc_change"==b.type){var a=document.getElementById(b.id);a&&proc_change2(a,b.x,b.y,scroll)}else"bg_proc_change_ok"==b.type&&proc_change_ok()},!1);
function proc_setlang(){for(var b,a=document.getElementsByTagName("*"),c=0;c<a.length;c++)if("i18n"==a[c].id){if(b=bg_i18n(a[c].title))a[c].innerHTML=b;a[c].title=""}else a[c].title&&0==a[c].title.indexOf("@")&&(b=bg_i18n(a[c].title.substr(1,a[c].title.length)))&&(a[c].title=b);if(a=_getid("en_script"))try{eval(a.value)}catch(d){}if(a=_getid("ko_script"))try{eval(a.value)}catch(d){}if(a=document.getElementById("i18n_msg_prev"))a.innerHTML=bg_i18n("msg_prev")+"("+g_config.prev_hotkey_name+")";if(a=
document.getElementById("i18n_msg_next"))a.innerHTML=bg_i18n("msg_next")+"("+g_config.next_hotkey_name+")";if(a=document.getElementById("i18n_msg_prev2"))a.innerHTML=bg_i18n("msg_prev")+"("+g_config.prev_hotkey_name+")";if(a=document.getElementById("i18n_msg_next2"))a.innerHTML=bg_i18n("msg_next")+"("+g_config.next_hotkey_name+")";if(a=document.getElementById("i18n_msg_change"))a.innerHTML=bg_i18n("msg_change")+"("+g_config.sourcechange_hotkey_name+")";if(a=document.getElementById("i18n_msg_change2"))a.innerHTML=
bg_i18n("msg_change")+"("+g_config.textchange_hotkey_name+")";if(a=document.getElementById("i18n_msg_gospellcheck"))a.innerHTML=bg_i18n("msg_gospellcheck")+"("+g_config.gospell_hotkey_name+")";if(a=document.getElementById("i18n_msg_openeditwindow"))a.innerHTML=bg_i18n("msg_openeditwindow")+"("+g_config.prev_hotkey_name+","+g_config.next_hotkey_name+")";if(a=document.getElementById("btn_proc_copy"))a.innerHTML=bg_i18n("msg_copytext")+"("+g_config.copytext_hotkey_name+")";if(a=document.getElementById("btn_add_userdic"))b=
a.innerText||a.textContent||"",a.innerHTML=b+"("+g_config.adduserdic_hotkey_name+")";if(a=document.getElementById("btn_proc_change_prev"))a.onclick=proc_change_prev;if(a=document.getElementById("btn_proc_change_next"))a.onclick=proc_change_next;if(a=document.getElementById("btn_proc_change_prev2"))a.onclick=proc_change_prev;if(a=document.getElementById("btn_proc_change_next2"))a.onclick=proc_change_next;if(a=document.getElementById("btn_proc_change_ok_source"))a.onclick=proc_change_ok_source;if(a=
document.getElementById("btn_add_userdic"))a.onclick=proc_add_userdic;if(a=document.getElementById("btn_proc_del_userdic"))a.onclick=proc_del_userdic;if(a=document.getElementById("btn_proc_go2"))a.onclick=proc_go2;if(a=document.getElementById("btn_proc_stop"))a.onclick=proc_stop;if(a=document.getElementById("btn_proc_savedata"))a.onclick=proc_savedata;if(a=document.getElementById("btn_proc_opendata"))a.onclick=proc_opendata;if(a=document.getElementById("btn_proc_copy"))a.onclick=proc_copy;if(a=document.getElementById("spell_copy_close"))a.onclick=
proc_copy_close;if(a=document.getElementById("spell_open_edit"))a.onclick=proc_open_edit_window;if(a=document.getElementById("other_ko_autocorrection"))a.onclick=function(){proc_set_bgstorage("other_ko_autocorrection",this.checked)};if(a=document.getElementById("other_ko_spellautoclose"))a.onclick=function(){proc_set_bgstorage("other_ko_spellautoclose",this.checked);var a=_getid("nav_1"),b=_getid("nav_2");this.checked?(a.style.display="none",b.style.display=""):(a.style.display="",b.style.display=
"none")};if(a=document.getElementById("other_ko_spellchangeall"))a.onclick=function(){proc_set_bgstorage("other_ko_spellchangeall",this.checked)};if(a=document.getElementById("other_ko_showdesc"))a.onclick=other_ko_showdesc_click;if(a=document.getElementById("btn_proc_change_ok_text"))a.onclick=function(){proc_change_ok_text(2)};(a=document.getElementById("maincontainer"))&&(a.style["max-width"]=bgstorage.other_maxwidth+"px");if(a=_getid("maintable"))a.style.width=bgstorage.other_maxwidth+"px";if(a=
document.getElementById("btn_option"))a.onclick=function(){var a=!1;0==bgstorage.other_ko_spellopentype&&(a=!0);bg_request({type:"open_tabexist",surl:g_optionsurl,last:a,id:!0,openurl:!1})};if(a=document.getElementById("other_ko_spell_lang"))a.onchange=other_ko_spell_lang_onchange}var user_dic_data={},srctext,controlfocused=!1,spells=[],current_edit_id,g_resized=!1,g_working=!1,xhr=new XMLHttpRequest;
function init(){function b(a){if(a=document.getElementById(a))a.addEventListener("focus",function(){controlfocused=!0},!0),a.addEventListener("blur",function(){controlfocused=!1},!0)}b("content");b("spell_copy_text");b("other_ko_spell_lang");b("spell_edit_userdic");var a=document.getElementById("content");a&&(a.focus(),controlfocused=!0);if(a=document.getElementById("spell_edit_userdic"))a.onkeydown=spell_edit_userdic_onkeydown;srctext=ko_spellcheck_text;document.getElementById("content").value=srctext;
document.addEventListener("mousedown",doc_eventMousedown,!0);document.addEventListener("keydown",doc_onkeydown,!0);window.onresize=function(){g_resized=!0;if(current_edit_id&&""==document.getElementById("spell_edit").style.display){var a=parseInt(current_edit_id.replace("spell_",""));0<=a&&a<=spells.length-1&&proc_edit_fill(a,!1)}};if(a=document.getElementById("spell_edit_desc"))a.addEventListener("mousewheel",function(a){var b=0;if(a&&(a.wheelDelta?(b=a.wheelDelta/120,window.opera&&(b=-b)):a.detail&&
(b=-a.detail/3),b=parseInt(b))){var c=!1,d=document.getElementById("spell_edit_desc");d&&(0<b?0>=d.scrollTop&&(c=!0):d.scrollTop+d.offsetHeight>=d.scrollHeight&&(c=!0),c&&(a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.returnValue=!1,a.cancelBubble=!0)))}},!0),a.addEventListener("keydown",function(a){var b=a.keyCode,c=!1,d=document.getElementById("spell_edit_desc");if(d){if(38==b||36==b||33==b)0>=d.scrollTop&&(c=!0);else if(40==b||35==b||34==b)d.scrollTop+d.offsetHeight>=d.scrollHeight&&
(c=!0);else return;c&&(a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.returnValue=!1,a.cancelBubble=!0))}},!0);if(a=document.getElementById("other_ko_autocorrection"))a.checked=toBool(bgstorage.other_ko_autocorrection);if(a=document.getElementById("other_ko_spellautoclose")){a.checked=toBool(bgstorage.other_ko_spellautoclose);var c=_getid("nav_1"),d=_getid("nav_2");a.checked?(c.style.display="none",d.style.display=""):(c.style.display="",d.style.display="none")}if(a=document.getElementById("other_ko_spellchangeall"))a.checked=
toBool(bgstorage.other_ko_spellchangeall);if(a=document.getElementById("other_ko_showdesc"))a.checked=toBool(bgstorage.other_ko_showdesc);if(a=document.getElementById("other_ko_spell_lang"))c=c=bgstorage.other_ko_spell_lang,""==c&&proc_set_bgstorage("other_ko_spell_lang","en"),a.value=bgstorage.other_ko_spell_lang,""!=a.value&&proc_go2()}function deinit(){}function find_user_dic_data(b){for(var a in user_dic_data)if(a==b)return user_dic_data[a]}
function spell_edit_userdic_onkeydown(b){var a=b.keyCode,c="undefined"==typeof b.modifiers?b.altKey:b.modifiers&Event.ALT_MASK,d="undefined"==typeof b.modifiers?b.shiftKey:b.modifiers&Event.SHIFT_MASK;("undefined"==typeof b.modifiers?b.ctrlKey:b.modifiers&Event.CONTROL_MASK)||c||d||13!=a||(proc_change_ok_text(2),b.stopPropagation())}
function sel_change_onkeydown(b){var a=b.keyCode,c="undefined"==typeof b.modifiers?b.altKey:b.modifiers&Event.ALT_MASK,d="undefined"==typeof b.modifiers?b.shiftKey:b.modifiers&Event.SHIFT_MASK;("undefined"==typeof b.modifiers?b.ctrlKey:b.modifiers&Event.CONTROL_MASK)||c||d||13!=a||(proc_change_ok(),b.stopPropagation())}function sel_change_onclick(){proc_change_ok()}
function fnSelect(b){fnDeSelect();if(document.selection){var a=document.body.createTextRange();a.moveToElementText(document.getElementById(b));a.select()}else window.getSelection&&(a=document.createRange(),a.selectNode(document.getElementById(b)),window.getSelection().addRange(a))}function fnDeSelect(){document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges()}
function showloading(){var b=document.getElementById("processing"),a,c;(a=_getid("maintable"))?(c=getOffset(a),a=c.left+10,c=c.top+10,a<getScrollLeft()&&(a=getScrollLeft()),c<getScrollTop()&&(c=getScrollTop())):(a=document.body.scrollLeft+10,c=document.body.scrollTop+10);b.style.left=a+"px";b.style.top=c+"px";b.style["background-color"]="#FFFFE1";b.style.border="1px solid #000000";b.style.padding="5px";b.style.display=""}
function hideloading(){document.getElementById("processing").style.display="none"}function getparamfromurl(b,a){a+="=";var c=b.indexOf(a);if(0>c)return"";b=b.substr(c+a.length,b.length);c=b.indexOf("&");return 0<=c?b.substr(0,c):b}function fetchRemotePost(b,a,c){xhr.abort();showloading();xhr.open("POST",b);xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xhr.send(a);xhr.onreadystatechange=function(){4==xhr.readyState&&c(xhr.responseText)}}
function proc_go_timer(b){try{if(g_working=b){var a=_getid("div_error");a&&(a.style.display="none");_getid("btn_proc_go2").disabled=!0;_getid("btn_proc_stop").disabled=!1}else _getid("btn_proc_go2").disabled=!1,_getid("btn_proc_stop").disabled=!0}catch(c){}}
function proc_go2(){if(!_getid("btn_proc_go2").disabled){current_edit_id=null;hide_spell_edit();var b=document.getElementById("fakescroll");b&&(b.style.top="0px");document.getElementById("suggest_content").innerHTML="";srctext=document.getElementById("content").value;proc_go()}}
function proc_go(){document.getElementById("div_extra").style.display="none";proc_copy_close();""==srctext?document.getElementById("suggest_content").innerHTML='<font color="blue">'+bg_i18n("msg_noinput")+"</font>":"ko"==document.getElementById("other_ko_spell_lang").value?window.proc_spell_ko_inf&&proc_spell_ko_inf():window.proc_spell_en_inf&&proc_spell_en_inf()}var label_current_spell,edit_scroll_timer=null;
function proc_edit_fill(b,a){var c=spells[b],d=document.getElementById("spell_edit_nav");d&&(d.innerHTML=b+1+"/"+spells.length);if(d=document.getElementById("spell_edit_nav2"))d.innerHTML=b+1+"/"+spells.length;var f,d=document.getElementById("spell_edit_current"),g=document.getElementById("spell_"+b);g&&(label_current_spell&&(label_current_spell.style["background-color"]=""),g.style["background-color"]=g_config.color_select,label_current_spell=g,f=g.innerText||g.textContent||"",d.innerHTML="&nbsp;"+
html_entity_encode(f));d=document.getElementById("spell_edit_source");d.innerHTML="&nbsp;"+html_entity_encode(c.source);var d=document.getElementById("spell_edit_userdic"),e=find_user_dic_data(c.source);e?(d.value=e,_getid("btn_proc_del_userdic").disabled=!1):(d.value="",_getid("btn_proc_del_userdic").disabled=!0);for(var d=e="",k,h=0;h<c.correct.length;h++)d=f==c.correct[h]?" selected ":"",k=html_entity_encode(c.correct[h]),e=e+"<option "+d+'value="'+k+'">'+k;d=document.getElementById("spell_edit_list");
d.innerHTML=""!=e?'<select id="sel_change" style="min-width:150px;font-size:13px" size="5" multiple="multiple">'+e+'</select><button onClick="proc_change_ok();">'+bg_i18n("msg_change")+"("+g_config.suggestchange_hotkey_name+")</button>":'&nbsp;<font style="font-size:13px;color:red">'+bg_i18n("msg_nosuggest")+"</font>";if(d=document.getElementById("sel_change"))d.onkeydown=sel_change_onkeydown,d.onclick=sel_change_onclick;d=document.getElementById("spell_edit_desc");f=toBool(bgstorage.other_ko_showdesc);
d.innerHTML=c.desc?c.desc:"";d.style.display=c.desc&&f?"":"none";d=document.getElementById("spell_edit_showdesc");d.style.display=c.desc?"":"none";d=getOffset(g);e=d.left;c=d.top+g.offsetHeight;d=document.getElementById("spell_edit");d.style.display="";k=d.clientWidth;f=d.clientHeight;var h=getScrollLeft(),l=getWindowWidth();e<h&&(e=h);e+k>h+l&&(e=h+l-k);d.style.left=e+"px";d.style.top=c+"px";d=document.getElementById("fakescroll");e=c+f;g_resized?(g_resized=!1,d.style.top=e+"px"):d.offsetTop<e&&
(d.style.top=e+"px");if(a){var m=g.offsetTop,n=c+f;edit_scroll_timer&&clearTimeout(edit_scroll_timer);edit_scroll_timer=setTimeout(function(){proc_edit_scroll(m,n)},10)}}function proc_edit_scroll(b,a){a>document.body.scrollTop+window.innerHeight&&window.scrollTo(0,a);(b<document.body.scrollTop||b>document.body.scrollTop+window.innerHeight)&&window.scrollTo(0,b);var c=document.getElementById("sel_change");c&&c.focus()}function proc_change(b,a,c){proc_change2(b,a.clientX,a.clientY,c)}
function proc_change2(b,a,c,d){current_edit_id=b=b.id;b=parseInt(b.replace("spell_",""));0>b||b>spells.length-1||(a=document.getElementById("spell_edit"),a.style.border="1px solid black",a.style["background-color"]="#FFFFE1",a.style.padding="5px",proc_edit_fill(b,d))}
function proc_open_edit_window(){var b=document.getElementById(current_edit_id);if(!b)for(var a=-1;;){a+=1;if(b=document.getElementById("spell_"+a))break;if(0>a||a>spells.length-1){alert(bg_i18n("msg_nodata"));return}}a=document.getElementById("spell_open_edit");proc_change2(b,a.offsetLeft,a.offsetTop+a.clientHeight-document.body.scrollTop,!0)}function set_lastchangeword(b,a){null==b&&(b=parseInt(current_edit_id.replace("spell_","")));0<=b&&b<=spells.length-1&&(spells[b].lastchangeword=a)}
function proc_change_ok(b){var a=document.getElementById("sel_change"),c=document.getElementById(current_edit_id);a&&c&&(""==a.value?show_message("<label2><font style='font-size:13px'>"+bg_i18n("msg_notselected")+"</font></label2>"):(!b&&document.getElementById("other_ko_spellchangeall").checked&&proc_change_all(a.value,!0)||(c.innerHTML='<font color="'+g_config.color_changed+'">'+a.value+"</font>",set_lastchangeword(null,a.value)),b||document.getElementById("other_ko_spellautoclose").checked&&hide_spell_edit()))}
function proc_change_ok_source(){if(current_edit_id){var b=parseInt(current_edit_id.replace("spell_",""));0>b||b>spells.length-1||(b=spells[b],document.getElementById("other_ko_spellchangeall").checked&&proc_change_all(b.source)||(document.getElementById(current_edit_id).innerHTML='<font color="'+g_config.color_changed+'">'+html_entity_encode(b.source)+"</font>",set_lastchangeword(null,b.source)),document.getElementById("other_ko_spellautoclose").checked&&hide_spell_edit())}}
function proc_change_ok_text(b){b=1==b?document.getElementById("spell_edit_text"):document.getElementById("spell_edit_userdic");var a=document.getElementById(current_edit_id);b&&a&&(""==b.value?show_message("<label2><font style='font-size:13px'>"+bg_i18n("msg_noinput")+"</font></label2>"):(document.getElementById("other_ko_spellchangeall").checked&&proc_change_all(b.value)||(a.innerHTML='<font color="'+g_config.color_changed+'">'+html_entity_encode(b.value)+"</font>",set_lastchangeword(null,b.value)),
document.getElementById("other_ko_spellautoclose").checked&&hide_spell_edit()))}function proc_setfocus(){var b=document.getElementById("sel_change");b&&b.focus()}
function proc_add_userdic(){if(current_edit_id){var b=parseInt(current_edit_id.replace("spell_",""));if(!(0>b||b>spells.length-1)){var b=spells[b],a=b.source;(a=prompt("Enter the source word.",a))&&(a=trim(a));if(a)if(0<=a.indexOf("->"))alert(sprintf(_i18n("msg_wrongword"),"->"));else{var c=document.getElementById("spell_edit_userdic"),d=b.lastchangeword;d||(d=c.value);d||(d=b.source);(d=prompt("Enter the replace word.",d))&&(d=trim(d));if(d)if(0<=d.indexOf("->"))alert(sprintf(_i18n("msg_wrongword"),
"->"));else{var f=0,g;for(g in user_dic_data)if(f++,1500<=f){alert("You can not add to user dictionary anymore.\nThe maximum possible number is 1500.");proc_setfocus();return}user_dic_data[a]=d;proc_set_bgstorage("user_dic_data",JSON.stringify(user_dic_data));b.source==a&&(c.value||(c.value=d),_getid("btn_proc_del_userdic").disabled=!1);show_message("<label2><font style='font-size:13px'>It was added to user dictionary.</font></label2>")}}proc_setfocus()}}}
function proc_del_userdic(){if(current_edit_id){var b=parseInt(current_edit_id.replace("spell_",""));0>b||b>spells.length-1||(b=spells[b].source,confirm(b+"\n\nDo you want to delete this word from user dictionary?")&&(delete user_dic_data[b],proc_set_bgstorage("user_dic_data",JSON.stringify(user_dic_data)),_getid("btn_proc_del_userdic").disabled=!0,show_message("<label2><font style='font-size:13px'>It was deleted from user dictionary.</font></label2>")),proc_setfocus())}}
function proc_change_all(b,a){if(!current_edit_id)return!0;var c=parseInt(current_edit_id.replace("spell_",""));if(0>c||c>spells.length-1)return!0;var d=spells[c],c=d.source;target2=a?b:html_entity_encode(b);for(var f=0,g=0;g<spells.length;g++)if(d=spells[g],d.source==c&&(d=document.getElementById("spell_"+g)))d.innerHTML='<font color="'+g_config.color_changed+'">'+target2+"</font>",f++,set_lastchangeword(g,b);show_message("<label2><font style='font-size:13px'>"+(f+" source has changed.")+"</font></label2>");
return!0}function proc_change_prev(){if(current_edit_id){for(var b=parseInt(current_edit_id.replace("spell_","")),a;;){--b;a="spell_"+b;if(document.getElementById(a))break;if(0>b||b>spells.length-1){""==_getid("spell_edit").style.display?show_message("<label2><font style='font-size:13px'>"+bg_i18n("msg_first")+"</font></label2>"):proc_open_edit_window();return}}current_edit_id=a;proc_edit_fill(b,!0)}}
function proc_change_next(){if(current_edit_id){for(var b=parseInt(current_edit_id.replace("spell_","")),a;;){b+=1;a="spell_"+b;if(document.getElementById(a))break;if(0>b||b>spells.length-1){""==_getid("spell_edit").style.display?show_message("<label2><font style='font-size:13px'>"+bg_i18n("msg_last")+"</font></label2>"):proc_open_edit_window();return}}current_edit_id=a;proc_edit_fill(b,!0)}}function other_ko_spell_lang_onchange(){proc_set_bgstorage("other_ko_spell_lang",this.value);proc_go2()}
function other_ko_showdesc_click(){proc_set_bgstorage("other_ko_showdesc",this.checked);document.getElementById("spell_edit_desc").style.display=this.checked?"":"none"}function hide_spell_edit(){document.getElementById("spell_edit").style.display="none";label_current_spell&&(label_current_spell.style["background-color"]="")}
function doc_eventMousedown(b){b.target.nodeName.toLowerCase();var a=document.getElementById("spell_edit");if(""==a.style.display){var c=b.clientX+document.body.scrollLeft;b=b.clientY+document.body.scrollTop;c>=a.offsetLeft&&c<=a.offsetLeft+a.clientWidth&&b>=a.offsetTop&&b<=a.offsetTop+a.clientHeight||hide_spell_edit()}}
function doc_onkeydown(b){function a(){b.preventDefault?(b.preventDefault(),b.stopPropagation()):(b.returnValue=!1,b.cancelBubble=!0)}var c=b.keyCode,d="undefined"==typeof b.modifiers?b.ctrlKey:b.modifiers&Event.CONTROL_MASK,f="undefined"==typeof b.modifiers?b.altKey:b.modifiers&Event.ALT_MASK,g="undefined"==typeof b.modifiers?b.shiftKey:b.modifiers&Event.SHIFT_MASK,e="";d&&g?e="ctrl+shift":d&&f?e="ctrl+alt":d?e="ctrl":f?e="alt":g&&(e="shift");if(!controlfocused||!(112>c||121<c)||""!=e&&"shift"!=
e)c==g_config.prev_hotkey2&&e==g_config.prev_hotkey?(c=document.getElementById("spell_open_edit"),c.disabled||(current_edit_id?proc_change_prev():proc_open_edit_window()),a()):c==g_config.next_hotkey2&&e==g_config.next_hotkey?(c=document.getElementById("spell_open_edit"),c.disabled||(current_edit_id?proc_change_next():proc_open_edit_window()),a()):(d=!1,""==document.getElementById("spell_edit").style.display?(d=!0,""==e&&27==c?hide_spell_edit():c==g_config.sourcechange_hotkey2&&e==g_config.sourcechange_hotkey?
proc_change_ok_source():c==g_config.suggestchange_hotkey2&&e==g_config.suggestchange_hotkey?proc_change_ok():c==g_config.textchange_hotkey2&&e==g_config.textchange_hotkey?proc_change_ok_text(2):c==g_config.gospell_hotkey2&&e==g_config.gospell_hotkey?proc_go2():c==g_config.copytext_hotkey2&&e==g_config.copytext_hotkey?proc_copy():c==g_config.adduserdic_hotkey2&&e==g_config.adduserdic_hotkey?proc_add_userdic():d=!1):(d=!0,c==g_config.gospell_hotkey2&&e==g_config.gospell_hotkey?proc_go2():c==g_config.copytext_hotkey2&&
e==g_config.copytext_hotkey?proc_copy():d=!1),d&&a())}
function proc_copy(){for(var b=document.getElementById("suggest_content"),a="",c,d=0;d<b.childNodes.length;d++)c=b.childNodes[d],a="BR"==c.tagName?a+"\n":a+(c.innerText||c.textContent||"");b=document.getElementById("spell_copy_text");b.value=a;b.style.display="";b.select();bg_request({type:"copytoclipboard",text:a});var f;try{0>navigator.userAgent.indexOf("MSIE")&&(f=document.execCommand("copy"))}catch(g){f=!1}f?show_message("<label2><font style='font-size:13px'>Text has copied to the clipboard.</font></label2>"):show_message("<label2><font style='font-size:13px'>"+
bg_i18n("msg_copyclipboard")+"</font></label2>");b=document.getElementById("spell_copy_close");b.disabled=!1}function proc_copy_close(){var b=document.getElementById("spell_copy_text");b.style.display="none";b.value="";b=document.getElementById("spell_copy_close");b.disabled=!0}function proc_error(b,a){var c=bg_i18n("msg_error");b&&(c=c+" ("+b+")");a&&(c+=a);var d=_getid("div_error");d&&(d.innerHTML='<font color="red">'+c+"</font>",d.style.display="")}var jobarr=[];
function proc_stop(){proc_go_timer(!1);for(var b=0;b<jobarr.length;b++)jobarr[b].xhr&&jobarr[b].xhr.abort();xhr&&xhr.abort()}var g_en_param;function proc_en_getparam(b,a){var c={method:"spelling.check",apiVersion:"v2",params:{}};c.params.text=b;c.params.language=a;c.params.key=gsdata.key;return c}
function proc_savedata(){if(confirm(bg_i18n("msg_areyousure"))){var b=document.getElementById("content").value;102400<b.length?alert("The text data is too large. The maximum possible size is 100 Kb."):(bg_request({type:"set",key:"last_savedata",value:b}),show_message("<label2><font style='font-size:13px'>"+bg_i18n("conf_saved")+"</font></label2>"))}}
function proc_opendata(){var b=bg_request({type:"get",key:"last_savedata"});b?(document.getElementById("content").value=b,show_message("<label2><font style='font-size:13px'>"+bg_i18n("msg_loadcomplete")+"</font></label2>")):show_message("<label2><font style='font-size:13px'>"+bg_i18n("conf_none")+"</font></label2>")}function proc_spell_en_inf(){}function proc_spell_ko_inf(){}
function init_get(){var b=new XMLHttpRequest;b.open("GET","?action=gsdata");b.send();b.onreadystatechange=function(){if(4==b.readyState){try{gsdata=JSON.parse(b.responseText)}catch(a){}g_en_param=gsdata.enurl;proc_get_start_data()}}}init_get();