var gresults=[],gcount=0,gsearchdata={},gseparate="========================",ginccount=0;function isunicode(b){return-1==escape(b).search(/%u/i)?!1:!0}function cutstring(b,d){for(var f=0,g=0;g<b.length;g++)if(f=isunicode(b[g])?f+2:f+1,f>=d)return b.substr(0,g)+"...";return b}
function getdatetime(b,d){var f=b,g=new Date(b);if(!isNaN(g)){g.getHours();g.getMinutes();var f=g.getFullYear()+"-"+(g.getMonth()+1)+"-"+g.getDate(),g=d.getTime()-g.getTime(),h=Math.floor(g/36E5),h=0>h?"about 1 minutes ago":0==h?"about 1 minutes ago".replace(/1/,Math.floor(g/6E4)):24>=h?"about 1 hours ago".replace(/1/,h):24<h&&48>=h?"Yesterday":"about 1 days ago".replace(/1/,Math.floor(h/24)),f=h+" ("+f+")"}return f}
function setCookie(b,d,f){f||(f=15768E7);path="/";domain=document.domain;secure=!1;var g=new Date;g.setTime(g.getTime());g=new Date(g.getTime()+f);document.cookie=b+"="+escape(d)+(f?";expires="+g.toGMTString():"")+(path?";path="+path:"")+(domain?";domain="+domain:"")+(secure?";secure":"")}
function getCookie(b){b+="=";for(var d=0;d<=document.cookie.length;){var f=d+b.length;if(document.cookie.substring(d,f)==b)return-1==(endOfCookie=document.cookie.indexOf(";",f))&&(endOfCookie=document.cookie.length),unescape(document.cookie.substring(f,endOfCookie));d=document.cookie.indexOf(" ",d)+1;if(0==d)break}return""}function _getid(b){return document.getElementById(b)}function trim(b){b&&b.replace||(b="");return b.replace(/^\s*|\s*$/g,"")}
function html_entity_encode(b){b&&b.replace||(b="");b=b.replace(/&/gi,"&amp;");b=b.replace(/>/gi,"&gt;");b=b.replace(/</gi,"&lt;");b=b.replace(/\"/gi,"&quot;");return b=b.replace(/\'/gi,"&#039;")}var henc=html_entity_encode;function shortstring(b,d){b||(b="");b.length>d&&(b=b.substr(0,d)+"...");return b}function cutstringmiddle(b,d,f,g){b||(b="");if(b.length<=d)return b;d=b.substr(0,f);b=b.substr(b.length-g,b.length);return d+"....."+b}
function getWindowWidth(){var b=0;if("number"==typeof window.innerWidth)b=window.innerWidth;else var b=document.documentElement.clientWidth,d=document.body.clientWidth,b=0<b?b:d;b||(b=0);return b}function getWindowHeight(){var b=0;if("number"==typeof window.innerHeight)b=window.innerHeight;else var b=document.documentElement.clientHeight,d=document.body.clientHeight,b=0<b?b:d;b||(b=0);return b}
function getScrollLeft(){var b;document.body&&document.body.scrollLeft?b=document.body.scrollLeft:document.documentElement&&document.documentElement.scrollLeft&&(b=document.documentElement.scrollLeft);b||(b=0);return b}function getScrollTop(){var b;document.body&&document.body.scrollTop?b=document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop&&(b=document.documentElement.scrollTop);b||(b=0);return b}
function number_format(b,d,f,g){b=(b+"").replace(/[^0-9+\-Ee.]/g,"");b=isFinite(+b)?+b:0;d=isFinite(+d)?Math.abs(d):0;g="undefined"===typeof g?",":g;f="undefined"===typeof f?".":f;var h="",h=function(b,d){var f=Math.pow(10,d);return""+Math.round(b*f)/f},h=(d?h(b,d):""+Math.round(b)).split(".");3<h[0].length&&(h[0]=h[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,g));(h[1]||"").length<d&&(h[1]=h[1]||"",h[1]+=Array(d-h[1].length+1).join("0"));return h.join(f)}var messagetimer=null;
function show_message(b,d,f,g,h){d||(d=10);f||(f=10);g||(g=5);h||(h=2E3);for(var k=1,l=1;4>=l;l++){var n="layer_message";1<l&&(n="layer_message"+l);if(n=document.getElementById(n)){k=l;break}}n.style.left="1px";n.style.top="1px";n.innerHTML=b;n.style.display="";1==k?(d=getScrollLeft()+d,f=getScrollTop()+f):2==k?(d=getScrollLeft()+(getWindowWidth()-n.clientWidth)/2,f=getScrollTop()+(getWindowHeight()-n.clientHeight)/2):3==k?(d=document.body.offsetWidth-n.clientWidth-5,f=getScrollTop()+f):99!=k&&(d=
getScrollLeft()+(getWindowWidth()-n.clientWidth)/2,f=getScrollTop()+f);d=parseInt(d);f=parseInt(f);n.style.border="1px solid #000000";n.style.padding=g+"px";n.style.left=d+"px";n.style.top=f+"px";n.style.zIndex="10001";messagetimer&&clearTimeout(messagetimer);messagetimer=setTimeout(hide_message,h)}function hide_message(){for(var b=1;4>=b;b++){var d="layer_message";1<b&&(d="layer_message"+b);if(d=document.getElementById(d))d.style.display="none"}}var g_logcount=0;
function _log(b,d,f,g){if("log4"==b||"log5"==b){b=_getid(b);var h=document.createElement("div");h.setAttribute("style","display:block;");f||(f="");g||(d=henc(d));h.innerHTML='<font class="'+f+'">'+d+"</font>";b.appendChild(h);b.scrollTop=b.scrollHeight;g_logcount++}else f=_getid(b),(g=f.value)&&(g+="\n"),f.value=g+d,f.scrollTop=f.scrollHeight}var iserror;
function proc_log(b,d,f,g){function h(b){if(b=_getid(b)){var h=document.createElement("div");h.setAttribute("style","display:block;");f||(f="");var n='<font class="'+f+'">'+henc(d)+"</font>";g&&(n+=" "+g);h.innerHTML=n;b.appendChild(h);b.scrollTop=b.scrollHeight}}"log1"==b&&(b="log4");h(b);"error"==f&&(iserror=!0,h("log5"))}
function proc_switchlog(b,d){for(var f=1;10>=f;f++){var g=_getid("log"+f);g&&(g.style.display="none")}g=_getid("log"+b);g.style.display="";g=_getid("logtab").getElementsByTagName("A");for(f=0;f<g.length;f++)g[f].style.fontWeight="normal";d.style.fontWeight="bold";return!1}function fillnumber(b){b=String(b);return 1==b.length?"0"+b:b}
function datetimetostring(b){b=new Date(b);var d="";if(!isNaN(b))var d=b.getFullYear(),f=b.getMonth()+1,g=b.getDate(),d=d+"-"+fillnumber(f)+"-"+fillnumber(g)+" "+fillnumber(b.getHours())+":"+fillnumber(b.getMinutes())+":"+fillnumber(b.getSeconds());return d}
var gformats=[["pdf","application/pdf"],["gif","image/gif"],["jpg","image/jpeg"],["jpeg","image/jpeg"],["png","image/png"],["doc","application/msword"],["docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],["htm","text/html"],["html","text/html"],["txt","text/plain"],["text","text/plain"],["odt","application/vnd.oasis.opendocument.text"],["ppt","application/vnd.ms-powerpoint"],["pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation"],["odp",
"application/vnd.oasis.opendocument.presentation"],["xls","application/vnd.ms-excel"],["ods","application/vnd.oasis.opendocument.spreadsheet"],["xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],["csv","text/csv"],["tsv","text/tab-separated-values"]];function getmimetype(b){b=(b||"").split(".");b=b[b.length-1].toLowerCase();for(var d=0;d<=gformats.length-1;d++)if(gformats[d][0]==b)return gformats[d][1]}
function getfilename(b){b=b.split(".");1<b.length&&b.splice(b.length-1,1);return b.join(".")}function getsize(b){if(!b)return"Unknown Size";if(1024>b)b+=" B";else{var d=-1;do b/=1024,++d;while(1024<=b);b=b.toFixed(1)+" "+"kB MB GB TB PB EB ZB YB".split(" ")[d]}return b}window.URL=window.URL||window.webkitURL;function _getfrmdoc(b){return b.contentWindow?b.contentWindow:b.contentDocument.document?b.contentDocument.document:b.contentDocument}var issafari=!1,ua=navigator.userAgent.toLowerCase();
-1!=ua.indexOf("safari")&&0>ua.indexOf("chrome")&&(issafari=!0);var ischrome=!1,isedge=!1,isfirefox=!1;0<=navigator.userAgent.indexOf("Chrome")&&(ischrome=!0);0<=navigator.userAgent.indexOf("Edge")&&(ischrome=!1,isedge=!0);0<=navigator.userAgent.indexOf("Firefox")&&(isfirefox=!0);function gd_getparam(b,d){d=(d+"=").toLowerCase();var f=b.toLowerCase().indexOf(d);if(0>f)return"";b=b.substr(f+d.length);f=b.toLowerCase().indexOf("&");return 0<=f?b.substr(0,f):b}
function setstorage(b,d){window.localStorage&&(localStorage[b]=d+"")}function getstorage(b){var d;window.localStorage&&(d=localStorage[b]);return d}function getValue(b,d,f){d=d.toLowerCase();f=f.toLowerCase();ss=b.toLowerCase();p1=ss.indexOf(d);if(!(0>p1||(s1=b.substr(p1+d.length,b.length),ss=s1.toLowerCase(),p1=ss.indexOf(f),0>p1)))return s1=s1.substr(0,p1)}
Date.prototype.setISO8601=function(b){if(b=b.match("^([-+]?)(\\d{4,})(?:-?(\\d{2})(?:-?(\\d{2})(?:[Tt ](\\d{2})(?::?(\\d{2})(?::?(\\d{2})(?:\\.(\\d{1,3})(?:\\d+)?)?)?)?(?:[Zz]|(?:([-+])(\\d{2})(?::?(\\d{2}))?)?)?)?)?)?$")){for(var d=[2,3,4,5,6,7,8,10,11],f=d.length-1;0<=f;--f)b[d[f]]="undefined"!=typeof b[d[f]]&&0<b[d[f]].length?parseInt(b[d[f]],10):0;"-"==b[1]&&(b[2]*=-1);d=Date.UTC(b[2],b[3]-1,b[4],b[5],b[6],b[7],b[8]);"undefined"!=typeof b[9]&&0<b[9].length&&(d+=("+"==b[9]?-1:1)*(36E5*b[10]+6E4*
b[11]));0<=b[2]&&99>=b[2]&&(d-=59958144E6);this.setTime(d);return this}return null};function proc_getdate(b){var d;try{var f=(new Date).setISO8601(b.modifiedDate);if(!isNaN(f)){var g=f.getHours(),h=f.getMinutes(),g=(10>g?"0":"")+g+":"+(10>h?"0":"")+h;d=f.getFullYear()+"-"+(f.getMonth()+1)+"-"+f.getDate()+" "+g}}catch(k){d=""}d||(d=(b.modifiedDate||"").split(".")[0]);return d}
function getOffset(b,d){for(var f=0,g=0;b&&!isNaN(b.offsetLeft)&&!isNaN(b.offsetTop);)f+=b.offsetLeft,g+=b.offsetTop,b=b.offsetParent;if(d)for(b2=d.target;b2&&!isNaN(b2.scrollLeft)&&!isNaN(b2.scrollTop)&&b2!=document.body;)f-=b2.scrollLeft,g-=b2.scrollTop,b2=b2.parentElement?b2.parentElement:b2.parentNode;return{left:f,top:g}}
var ginitfolder,FOLDER_MIMETYPE="application/vnd.google-apps.folder",QUAL_URL="https://content-googleapis-test.sandbox.google.com",FIELDS="id,title,mimeType,parents(id),fileExtension,fileSize,modifiedDate,modifiedByMeDate,lastViewedByMeDate,labels(trashed),shared,alternateLink,downloadUrl,owners(isAuthenticatedUser)",APP_FIELDS="id,createUrl,installed,name,openUrlTemplate,primaryFileExtensions,primaryMimeTypes,secondaryFileExtensions,secondaryMimeTypes,supportsCreate,useByDefault",$1={},goog={inherits:function(b,
d){function f(){}f.prototype=d.prototype;b.superClass_=d.prototype;b.prototype=new f;b.prototype.constructor=b},base:function(b,d,f){var g=arguments.callee.caller;if(g.superClass_)return g.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var h=Array.prototype.slice.call(arguments,2),k=!1,l=b.constructor;l;l=l.superClass_&&l.superClass_.constructor)if(l.prototype[d]===g)k=!0;else if(k)return l.prototype[d].apply(b,h);if(b[d]===g)return b.constructor.prototype[d].apply(b,
h);throw Error("goog.base called from a method of one name to a method of a different name");}};String.prototype.startsWith=function(b){return this.slice(0,b.length)==b};String.prototype.endsWith=function(b){return this.slice(this.length-b.length)==b};var util={array:{}};util.array.first=function(b,d){for(;0<b.length;)return d(b[0])?b[0]:null};util.array.each=function(b,d){for(var f=0;f<b.length;f++)d(b[f])};util.array.some=function(b,d){for(var f=0;f<b.length;f++)if(d(b[f]))return!0;return!1};
util.array.all=function(b,d){for(var f=0;f<b.length;f++)if(!d(b[f]))return!1;return!0};util.array.none=function(b,d){for(var f=0;f<b.length;f++)if(d(b[f]))return!1;return!0};util.array.map=function(b,d,f){var g=[];util.array.each(b,function(b){!d(b)&&f||g.push(d(b))});return g};util.array.noDups=function(b,d){for(var f=d||function(b){return b},g={},h=[],k=0;k<b.length;k++){var l=b[k];g[f(l)]||(g[f(l)]=!0,h.push(l))}return h};util.object={};util.object.each=function(b,d){for(var f in b)d(b[f])};
util.doLater=function(b){window.setTimeout(b,0)};var Predicates={ALL:function(b){return!0}},Deferred=function(){this.callbacks_=[];this.errbacks_=[];this.val_=null;this.hasFired_=this.isError_=!1};Deferred.prototype.addCallback=function(b){this.addCallbacks(b,null)};Deferred.prototype.addErrback=function(b){this.addCallbacks(null,b)};Deferred.prototype.addCallbacks=function(b,d){b&&this.callbacks_.push(b);d&&this.errbacks_.push(d);this.hasFired_&&(this.isError_&&d?d(this.val_):b&&b(this.val_))};
Deferred.prototype.addBoth=function(b){this.addCallbacks(b,b)};Deferred.prototype.callback=function(b){this.val_=b;this.hasFired_=!0;util.array.each(this.callbacks_,function(b){b(this.val_)}.bind(this))};Deferred.prototype.errback=function(b){this.val_=b;this.isError_=this.hasFired_=!0;util.array.each(this.errbacks_,function(b){b(this.val_)}.bind(this))};Deferred.prototype.follow=function(b){b.addCallbacks(this.callback.bind(this),this.errback.bind(this))};
Deferred.succeed=function(b){var d=new Deferred;d.callback(b);return d};Deferred.fail=function(b){var d=new Deferred;d.errback(b);return d};var queryParam=function(b){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");b=(new RegExp("[\\?&]"+b+"=([^&#]*)")).exec(location.search);return null==b?"":decodeURIComponent(b[1].replace(/\+/g," "))},TrieNode=function(b,d){this.children={};this.prefix=b;this.value=d};
TrieNode.prototype.find=function(b){for(var d=this,f=0;f<b.length;f++){var g=b.charAt(f);if(!(d=d.children[g]))return null}return d};var WordTabCompleter=function(b){this.trieRoot_=new TrieNode("",[]);b&&this.addAll(b)};WordTabCompleter.prototype.complete=function(b){for(b=this.trieRoot_.find(b);b&&1==Object.keys(b.children).length;)b=b.children[Object.keys(b.children)[0]];return b?b.prefix:null};WordTabCompleter.prototype.list=function(b){return(b=this.trieRoot_.find(b))?b.value:[]};
WordTabCompleter.prototype.clear=function(){this.trieRoot_=new TrieNode("",[])};WordTabCompleter.prototype.add=function(b){this.trieRoot_.value.push(b);for(var d=this.trieRoot_,f=0;f<b.length;f++){var g=b.charAt(f);d.children[g]||(d.children[g]=new TrieNode(d.prefix+g,[]));d.children[g].value.push(b);d=d.children[g]}};WordTabCompleter.prototype.addAll=function(b){util.array.each(b,this.add.bind(this))};var PathTabCompleter=function(b){WordTabCompleter.call(this,b)};
goog.inherits(PathTabCompleter,WordTabCompleter);PathTabCompleter.prototype.list=function(b){var d=PathTabCompleter.superClass_.list.call(this,b),f=b.split("/").length-1;b=util.array.map(d,function(b){b=b.split("/");return b.length>f?b[f]:null},!0);return util.array.noDups(b)};var Tokenizer=function(){this.tokenizedStr_="";this.originalTokens_=[]};Tokenizer.prototype.replace=function(b,d){this.originalTokens_[b]=d;return this.rebuild()};
Tokenizer.prototype.tokenTo=function(b,d,f,g,h){var k=d;f=f.split("");for(var l="";d<b.length;d++){if(h&&b[d]==h)d+=1;else if(g&&0>$.inArray(b[d],f)||!g&&0<=$.inArray(b[d],f))break;d<b.length&&(l+=b[d])}return{index:d,token:l,original:b.slice(k,d)}};
Tokenizer.prototype.nextToken=function(b,d){var f=this.tokenTo(b,d," =",!0);this.tokenizedStr_+=f.original;var g=f.index;if(g>=b.length)return null;f=" =";'"'==b[g]&&(f='"',g++);g=this.tokenTo(b,g,f,!1,"\\");this.tokenizedStr_+="$"+this.originalTokens_.length+"$";'"'==f&&(g.index++,g.original='"'+g.original+'"');return g};
Tokenizer.prototype.tokenize=function(b){var d=[];this.originalTokens_=[];for(var f=0,g;f<b.length&&(g=this.nextToken(b,f));)f=g.index,d.push(g.token),this.originalTokens_.push(g.original);return d};Tokenizer.prototype.endsInDelimiter=function(){return 0<this.tokenizedStr_.length&&!this.tokenizedStr_.endsWith("$")};Tokenizer.prototype.rebuild=function(){for(var b=this.tokenizedStr_,d=0;d<this.originalTokens_.length;d++)b=b.replace("$"+d+"$",this.originalTokens_[d]);return b};Tokenizer.tokenize=function(b){return(new Tokenizer).tokenize(b)};
var EventBus=function(){this.listeners_={}};EventBus.prototype.getListeners_=function(b){return this.listeners_[b]||[]};EventBus.prototype.subscribe=function(b,d){this.listeners_[b]=this.getListeners_(b);this.listeners_[b].push(d)};EventBus.prototype.publish=function(b,d,f){util.array.each(this.getListeners_(b),function(b){b(d)})};
var eBus=new EventBus,cons={FileSystem:function(){this.path_=[];this.files_={};this.filesByParent_={};this.folderPathTabCompleter=new PathTabCompleter;this.pathTabCompleter=new PathTabCompleter}};cons.FileSystem.prototype.init=function(b){this.path_=[];this.files_={};this.filesByParent_={};this.folderPathTabCompleter=new PathTabCompleter;this.pathTabCompleter=new PathTabCompleter;this.fetchFolders_();return this.cdById(b)};
cons.FileSystem.prototype.fetchFolders_=function(b,d){var f=b||0;Api.exec("GET","drive","v2","files",{q:'trashed=false and mimeType="'+FOLDER_MIMETYPE+'"',maxResults:500,pageToken:d,fields:"items("+FIELDS+"),nextPageToken"}).addCallback(function(b){this.addFiles_(b.items);f+=b.items.length;eBus.publish("fs-folders-loaded",{num:f,complete:!b.nextPageToken});b.nextPageToken&&this.fetchFolders_(f,b.nextPageToken)}.bind(this),function(b){eBus.publish("fs-folders-load-fail",b)}.bind(this))};
cons.FileSystem.prototype.addToPath_=function(b){this.path_.push(b);this.setPath_(this.path_)};cons.FileSystem.prototype.setPath_=function(b){this.path_=b;gsearchdata.lsPageToken="";gsearchdata.lsPage=0;this.ls({force:!0});eBus.publish("fs-cd",this.path_)};cons.FileSystem.prototype.getHereId=function(){return 0<this.path_.length?this.path_[this.path_.length-1].id:null};cons.FileSystem.prototype.getHereData=function(){return 0<this.path_.length?this.path_[this.path_.length-1]:null};
cons.FileSystem.prototype.addFiles_=function(b){util.array.each(b,function(b){this.addFile_(b,!0)}.bind(this));this.updateTabCompleters_()};cons.FileSystem.prototype.addFile_=function(b,d){this.removeFile_(b.id);this.files_[b.id]=b;0==b.parents.length?(this.filesByParent_.NOPARENT=this.filesByParent_.NOPARENT||{})[b.id]=b:util.array.each(b.parents,function(d){(this.filesByParent_[d.id]=this.filesByParent_[d.id]||{})[b.id]=b}.bind(this));d||this.updateTabCompleters_()};
cons.FileSystem.prototype.removeFile_=function(b){var d=this.files_[b];d&&(delete this.files_[b],0==d.parents.length?delete this.filesByParent_.NOPARENT[b]:util.array.each(d.parents,function(d){delete this.filesByParent_[d.id][b]}.bind(this)))};
cons.FileSystem.prototype.resolve=function(b,d){var f=b.startsWith("/");b=b.replace(/\/$|^\//g,"");for(var g=b.split("/"),h=[],k=f?[]:$.merge([],this.path_),f=0;f<g.length;f++){var l=g[f];h.push(l);if(".."==l)if(0<k.length)k=k.slice(0,k.length-1);else return Deferred.fail(h.join("/")+" does not exist");else{var n=0<k.length?k[k.length-1].id:null,l=this.query().name(l).in(n).go();if(0==l.length)return Deferred.fail(h.join("/")+" does not exist");if(f==g.length-1){var t=[];util.array.each(l,function(b){var d=
$.merge([],k);d.push(b);t.push(d)});return Deferred.succeed(t)}if(l=util.array.first(l,function(b){return b.mimeType==FOLDER_MIMETYPE}))k.push(l);else return Deferred.fail(h.join("/")+" is not a folder")}}return Deferred.succeed([k])};cons.FileSystem.prototype.cd=function(b){var d=this.resolve(b),f=new Deferred;d.addCallbacks(function(b){this.setPath_(b[0]);f.callback()}.bind(this),function(d){1==b.split("/").length?f.follow(this.cdById(b)):f.errback(d)}.bind(this));return f};
cons.FileSystem.prototype.cdById=function(b){var d=this.query().anywhere().id(b).is(FOLDER_MIMETYPE).go();if(0<d.length)return this.setPath_([d[0]]),Deferred.succeed();var d={fields:FIELDS,q:"trashed = false"},f=new Deferred;Api.exec("GET","drive","v2","files/"+b,d).addCallbacks(function(b){this.addFile_(b);this.setPath_([b]);f.callback()}.bind(this),function(d){f.errback("Unknown folder "+b)});return f};
cons.FileSystem.prototype.ls=function(b,d){var f=new Deferred;(d?this.resolve(d):Deferred.succeed([])).addCallbacks(function(g){var h=this.getHereId();if(0<g.length)if(h=g[0],0<h.length){h=h[h.length-1];if(h.mimeType!=FOLDER_MIMETYPE){f.errback(d+" is not a folder");return}h=h.id}else h=null;var k=b||{};if(k.force||k.showtrash||k.shareme||k.entire){if(k.nextpage){if(!gsearchdata.lsPageToken){f.errback("No next page results.");return}}else gsearchdata.lsPageToken="",gsearchdata.lsPage=0;g={fields:"items("+
FIELDS+"),nextPageToken",maxResults:100,q:""};k.nextpage&&gsearchdata.lsPageToken&&(g.pageToken=gsearchdata.lsPageToken,gsearchdata.lsPage||(gsearchdata.lsPage=0),gsearchdata.lsPage++);g.q="";k.showtrash?g.q+="trashed=true":k.shareme?g.q+="sharedWithMe=true":k.entire?g.q+="":(g.q+="trashed=false",h&&(g.q+=' and "'+h+'" in parents'));k.isFolder&&(g.q&&(g.q+=" and "),g.q+='mimeType="'+FOLDER_MIMETYPE+'"');if(k.filter&&0<k.filter.length)for(h=0;h<k.filter.length;h++)g.q&&(g.q+=" and "),g.q+="(title contains '"+
k.filter[h].replace(/(\'|\")/g,"")+"')";Api.exec("GET","drive","v2","files",g).addCallbacks(function(b){!b.items||k.showtrash||k.shareme||k.entire||k.nextpage||this.addFiles_(b.items);b.lsForce=!0;f.callback(b)}.bind(this),f.errback.bind(f));return f}k=b||{};h=this.query().in(h);k.isFolder&&h.is(FOLDER_MIMETYPE);f.callback({items:h.go()})}.bind(this),f.errback.bind(f));return f};
cons.FileSystem.prototype.updateTabCompleters_=function(){this.folderPathTabCompleter.clear();this.folderPathTabCompleter.addAll(this.getPaths(this.getHereId(),!0));this.pathTabCompleter.clear();this.pathTabCompleter.addAll(this.getPaths(this.getHereId()))};
cons.FileSystem.prototype.getPaths=function(b,d){var f=this.query().in(b||null).go();if(0==f.length)return[];var g=[];util.array.each(f,function(f){if(!d||f.mimeType==FOLDER_MIMETYPE){var k=this.getPaths(f.id,d),l=(b?"":"/")+f.title;g.push(l);util.array.each(k,function(b){g.push(l+"/"+b)})}}.bind(this));return g};
cons.FileSystem.prototype.mkfile=function(b,d){var f=b.lastIndexOf("/"),g=b.slice(0,f+1),h=b.slice(f+1),k=new Deferred;(0<g.length?this.resolve(g):Deferred.succeed([])).addCallbacks(function(b){b=b[0]?b[0]:"";(b=0<b.length?b[b.length-1]:null)&&b.mimeType!=FOLDER_MIMETYPE?k.errback(g+" is not a folder"):(b={title:h,mimeType:d,parents:[{id:b?b.id:this.getHereId()}],fields:FIELDS},b=Api.exec("POST","drive","v2","files",{},JSON.stringify(b)),b.addCallbacks(function(b){this.addFile_(b);this.updateTabCompleters_()}.bind(this),
null),k.follow(b))}.bind(this),k.errback.bind(k));return k};
cons.FileSystem.prototype.rename=function(b,d){var f=new Deferred;this.resolve(b).addCallbacks(function(b){b=b[0];b=b[b.length-1];var h={title:d};b.modifiedByMeDate&&(h.modifiedByMeDate=b.modifiedByMeDate);b.modifiedDate&&(h.modifiedDate=b.modifiedDate);b.lastViewedByMeDate&&(h.lastViewedByMeDate=b.lastViewedByMeDate);b=Api.exec("PATCH","drive","v2","files/"+b.id,{},JSON.stringify(h));b.addCallbacks(function(b){this.addFile_(b)}.bind(this),null);f.follow(b)}.bind(this),f.errback.bind(f));return f};
cons.FileSystem.prototype.rm=function(b,d){var f=new Deferred;if("emptytrash"==d){if(confirm("Are you sure?")){var g=Api.exec("DELETE","drive","v2","files/trash",{});g.addCallbacks(function(){this.updateTabCompleters_()}.bind(this),null);f.follow(g)}else f.errback("Canceled by user.");return f}this.resolve(b).addCallbacks(function(b){b=b[0];var g=b[b.length-1];b="trash"==d?Api.exec("POST","drive","v2","files/"+g.id+"/trash",{}):"untrash"==d?Api.exec("POST","drive","v2","files/"+g.id+"/untrash",{}):
Api.exec("DELETE","drive","v2","files/"+g.id,{});b.addCallbacks(function(){this.removeFile_(g.id);this.updateTabCompleters_()}.bind(this),null);f.follow(b)}.bind(this),f.errback.bind(f));return f};cons.FileSystem.prototype.getPath=function(b){return this.path_};cons.FileSystem.prototype.query=function(){return new cons.FileSystem.Query(this)};cons.FileSystem.Query=function(b){this.fs_=b;this.files_={};this.predicates_=[];this.here()};
cons.FileSystem.Query.prototype.id=function(b){this.predicates_.push(function(d){return d.id==b});return this};cons.FileSystem.Query.prototype.anywhere=function(){this.files_=this.fs_.files_;return this};cons.FileSystem.Query.prototype.in=function(b){this.files_=b?this.fs_.filesByParent_[b]||{}:this.fs_.filesByParent_.NOPARENT||{};return this};cons.FileSystem.Query.prototype.here=function(){return this.in(this.fs_.getHereId())};
cons.FileSystem.Query.prototype.is=function(b){this.predicates_.push(function(d){return d.mimeType==b});return this};cons.FileSystem.Query.prototype.name=function(b){this.predicates_.push(function(d){return d.title==b});return this};cons.FileSystem.Query.prototype.matches=function(b){this.predicates_.push(b);return this};
cons.FileSystem.Query.prototype.go=function(){var b=[],d;for(d in this.files_)util.array.all(this.predicates_,function(b){return b(this.files_[d])}.bind(this))&&b.push(this.files_[d]);b.sort(function(b,d){return b.title<d.title?-1:b.title>d.title?1:0});return b};cons.Apps=function(){this.apps_={}};cons.Apps.prototype.init=function(){};cons.Apps.prototype.setApps=function(b){this.apps_=[];util.array.each(b,function(b){this.apps_[b.id]=b}.bind(this))};
cons.Apps.prototype.ls=function(b){if((b||{}).force){var d=new Deferred;Api.exec("GET","drive","v2","apps",{fields:"items("+APP_FIELDS+")"}).addCallbacks(function(b){b.items&&this.setApps(b.items);d.callback(b.items)}.bind(this),d.errback.bind(this));return d}return Deferred.succeed(this.find(Predicates.ALL))};
cons.Apps.prototype.open=function(b){var d=this.find(function(d){return(0<=$.inArray(b.mimeType,d.primaryMimeTypes)||0<=$.inArray(b.mimeType,d.secondaryMimeTypes)||0<=$.inArray(b.fileExtension,d.primaryFileExtensions)||0<=$.inArray(b.fileExtension,d.secondaryFileExtensions))&&!!d.openUrlTemplate});if(0==d.length)return Deferred.fail("No apps can open "+filename);d=d[0].openUrlTemplate.replace("{ids}",b.id).replace("{exportIds}","");window.open(d,"_blank");return Deferred.succeed()};
cons.Apps.prototype.find=function(b){var d=[],f;for(f in this.apps_)b(this.apps_[f])&&d.push(this.apps_[f]);return d};
cons.Console=function(b){this.cursor_=$("#input-cursor");this.consEl_=$("#cons");this.consEl_.on("mouseup",this.onMouseUp_.bind(this));this.consEl_.on("click",this.onClick_.bind(this));this.outputEl_=$("#output");this.outputcount=0;this.inputContainerEl_=$("#input-container");this.inputEl_=$("#input");this.inputEl_MaxH=0;this.inputEl_.on("keydown",this.onKeyDown_.bind(this));this.inputEl_.on("input",this.onInput_.bind(this));this.inputEl_.val(this.prompt_);this.history_=[];this.historyCursor_=0;try{this.history_=
JSON.parse(getstorage("c_cmdhistory")),this.historyCursor_=this.history_.length}catch(d){}this.commands_={};this.setLocation_(b.getPath());this.cmdTabCompleter_=new WordTabCompleter;eBus.subscribe("fs-cd",this.setLocation_.bind(this));eBus.subscribe("fs-folders-loaded",function(b){b.complete?this.write("All folders ("+b.num+") loaded into cache"):this.write(b.num+" folders loaded into cache")}.bind(this));eBus.subscribe("fs-folders-load-fail",function(b){e.complete&&this.write("Failed to load all folders into cache: "+
b)}.bind(this))};cons.Console.prototype.focus=function(){this.inputEl_.focus();this.scrollToBottom()};cons.Console.prototype.setLocation_=function(b){var d=[];util.array.each(b,function(b){d.push(b.title)});b=0<d.length?d.join("/"):"The other";this.cursor_.text(b+" > ")};cons.Console.prototype.installCommand=function(b,d){d instanceof commands.Command||(d=new commands.Fn(this,d));this.commands_[b]=d;this.cmdTabCompleter_.add(b)};cons.Console.prototype.onMouseUp_=function(b){};
cons.Console.prototype.onClick_=function(b){var d;b.target?d=b.target:b.srcElement&&(d=b.srcElement);d&&"A"==d.tagName||(b=_getid("gviewer"),b&&""==b.style.display||0!=window.getSelection().toString().length||(util.doLater(this.focus.bind(this)),window.hide_message&&hide_message()))};cons.Console.prototype.onInput_=function(){this.inputEl_.height(1);var b=this.inputEl_[0].scrollHeight;1<b&&(this.inputEl_MaxH=b);1>=b&&0<this.inputEl_MaxH&&(b=this.inputEl_MaxH);this.inputEl_.height(b)};
cons.Console.prototype.onKeyDown_=function(b){var d=!1;if(!(b.shiftKey||b.ctrlKey||b.metaKey||b.altKey)&&(13==b.which?(this.submit_(),d=!0):38==b.which?(this.historyCursor_=Math.max(this.historyCursor_-1,0),d=this.history_[this.historyCursor_],this.inputEl_.val(d),d=!0):40==b.which?(this.historyCursor_=Math.min(this.historyCursor_+1,this.history_.length),d=this.historyCursor_<this.history_.length?this.history_[this.historyCursor_]:"",this.inputEl_.val(d),d=!0):9==b.which&&(this.tabComplete_(),d=!0),
d))return b.preventDefault(),!1};
cons.Console.prototype.tabComplete_=function(){var b=new Tokenizer,d=this.inputEl_.val(),f=b.tokenize(d),g=b.endsInDelimiter()?"":f[f.length-1]||"",h=new WordTabCompleter;h=1>=f.length&&!b.endsInDelimiter()?this.cmdTabCompleter_:(h=this.getCmd(f[0]))?h.getTabCompleter():new WordTabCompleter;var k=h.complete(g);k&&k!=g?(k=k.replace(/ /g,"\\ "),this.inputEl_.val(b.replace(f.length-1,k)),this.focus()):(b=h.list(g),1<b.length?(this.writeInput_(),this.writeList(b,function(b){return b})):1==b.length?(this.inputEl_.val(d+
" "),this.focus()):(this.writeInput_(),this.write("No known tab completions")))};cons.Console.prototype.write=function(b,d){if(b&&0<b.length){var f={class:"output-block output-block-text"};d?f.html=b:f.text=b;this.writeHTML($("<div/>",f))}};cons.Console.prototype.writeImg=function(b){b&&0<b.length&&this.writeHTML($("<img/>",{class:"output-block output-block-img",src:b}))};
cons.Console.prototype.writeHTML=function(b){b.appendTo(this.outputEl_);util.doLater(this.scrollToBottom.bind(this));this.outputcount++;if(70<this.outputcount){b=this.outputEl_[0].getElementsByTagName("*");for(var d=[],f=0;f<b.length&&!(b[f].className&&(0<=b[f].className.indexOf("output-block")||0<=b[f].className.indexOf("input-container"))&&(d.push(b[f]),10<d.length));f++);for(f=0;f<d.length;f++)d[f].parentNode.removeChild(d[f]);this.outputcount=0}};
cons.Console.prototype.writeList=function(b,d,f,g){if(!(0>=b.length)){var h=$("<div/>",{class:"output-block"}),k=0;util.array.each(b,function(b){k=Math.max(d(b).length,k)});util.array.each(b,function(b){var n="ls-item";f&&f(b)&&(n+=" "+f(b));n={class:n,width:k+"em"};g?n.html=g(b):n.text=d(b);h.append($("<div/>",n))});c.writeHTML(h)}};
cons.Console.prototype.writeInput_=function(){var b=this.inputEl_.val(),d=this.inputContainerEl_.clone(),f=d.children("#input"),b=$("<div/>",{class:"input",text:b});f.before(b);f.remove();this.writeHTML(d)};cons.Console.prototype.scrollToBottom=function(){clearTimeout(gscrolltimer);var b=this;gscrolltimer=setTimeout(function(){b.consEl_.animate({scrollTop:b.consEl_[0].scrollHeight})},50)};
cons.Console.prototype.enableInput=function(b){b?(this.cursor_[0]&&(this.cursor_[0].className="",this.cursor_[0].style.whiteSpace="pre-wrap",this.cursor_[0].style.fontFamily="",this.cursor_[0].style.fontFamily="monospace"),this.inputContainerEl_.show(),this.focus()):this.inputContainerEl_.hide()};cons.Console.prototype.getCmd=function(b){return this.commands_[b]};
cons.Console.prototype.submit_=function(){var b=this.inputEl_.val();this.writeInput_();this.inputEl_.val("");50<this.history_.length&&this.history_.splice(0,1);b&&this.history_[this.history_.length-1]!=b&&this.history_.push(b);this.historyCursor_=this.history_.length;setstorage("c_cmdhistory",JSON.stringify(this.history_));this.enableInput(!1);try{var d=this.execStr(b)}catch(f){this.write(f.toString());this.enableInput(!0);return}d.addErrback(function(b){b&&this.write(b)}.bind(this));d.addBoth(function(b){this.enableInput(!0);
this.focus()}.bind(this))};cons.Console.prototype.execStr=function(b){return this.exec(Tokenizer.tokenize(b),b)};cons.Console.prototype.exec=function(b,d){return this.commands_[b[0]]?this.commands_[b[0]].exec(b,d):Deferred.fail("Sorry, Unknown command "+(b[0]||'""'))};cons.Console.prototype.getCommandTabCompleter=function(){return this.cmdTabCompleter_};var fs=new cons.FileSystem,a=new cons.Apps,c=new cons.Console(fs);c.enableInput(!1);
c.write('<span class="highlight1">Welcome to the Drive Console Emulator. Connecting to Drive...</span>',!0);
Api={root:void 0,exec:function(b,d,f,g,h,k,l,n){b={path:(l?"upload/":"")+d+"/"+f+"/"+g,method:b,params:h,body:k,root:Api.root};n&&(b.headers=n);n=gapi.client.request(b);return Api.executeReq_(n)},get:function(b,d){var f=new Deferred,g=b;if(gapi.auth.getToken()){var h=gapi.auth.getToken().access_token;h&&(g+="&access_token="+encodeURIComponent(h))}var k=new XMLHttpRequest;k.open("GET",g);k.onload=function(){200==this.status?f.callback(d?k.response:k.responseText):f.errback(this.status+" ("+this.statusText+
") occurred while receiving the file.")};k.onerror=function(){f.errback(k.responseCode+": "+k.statusText)};d&&(k.responseType="blob");k.send();return f},executeReq_:function(b){var d=new Deferred;b.execute(function(b,g){"undefined"===typeof b?d.callback():b?b.error?d.errback(JSON.stringify(b,null,"  ")):b.result?d.callback(b.result):d.callback(b):d.errback(g)});return d}};
commands={getParams:function(b){for(var d={},f=0;f<b.length;f++)if(b[f].startsWith("-")){var g=b[f].startsWith("--")?2:1,g=b[f].slice(g);f+1<b.length&&!b[f+1].startsWith("-")?(f++,d[g]=b[f]):d[g]=!0}return d},Flag:function(b,d,f){this.name_=b;this.desc_=f;this.value=this.defaultVal_=d}};commands.Flag.prototype.helpText=function(){var b="-"+this.name_+" "+this.desc_;this.defaultVal_&&(b+=" (Default is "+this.defaultVal_+")");return b};commands.Flag.prototype.reset=function(){this.value=this.defaultVal_};
commands.Flag.prototype.get=function(){return this.value};commands.Command=function(b,d){this.out=b;this.desc_=d;this.registeredFlags_={};this.otherFlags_={};this.params_=[]};commands.Command.prototype.exec=function(b,d){util.object.each(this.registeredFlags_,function(b){b.reset()});this.otherFlags_={};this.params_=[];this.parseParams(b);return this.execInternal(this.params_,this.otherFlags_,b,d)};commands.Command.prototype.execInternal=function(b,d,f,g){return Deferred.succeed()};
commands.Command.prototype.registerFlag=function(b,d,f){d=new commands.Flag(b,d,f);if(this.registeredFlags_[b])throw Error("Two flags registered with the same name "+b);return this.registeredFlags_[b]=d};commands.Command.prototype.parseParams=function(b){for(var d=1;d<b.length;d++)if(b[d].startsWith("-")){var f=b[d].startsWith("--")?2:1,f=b[d].slice(f),g;d+1<b.length&&!b[d+1].startsWith("-")?(d++,g=b[d]):g=!0;this.registeredFlags_[f]?this.registeredFlags_[f].value=g:this.otherFlags_[f]=g}else this.params_.push(b[d])};
commands.Command.prototype.help=function(){this.out.write(this.desc_);0<Object.keys(this.registeredFlags_).length&&(this.out.write("Available flags: "),util.object.each(this.registeredFlags_,function(b){this.out.write(b.helpText())}.bind(this)))};commands.Command.prototype.getTabCompleter=function(b){return new WordTabCompleter};commands.Fn=function(b,d){commands.Command.call(this,b,"No help description for this command.");this.fn_=d};goog.inherits(commands.Fn,commands.Command);
commands.Fn.prototype.execInternal=function(b,d,f,g){return this.fn_(f)};
commands.Auth=function(b){commands.Command.call(this,b,"Authorizes the Google API for a user.");this.user_=this.registerFlag("u",void 0,"The auth user index for which to authorize.");this.scopeStr_=this.registerFlag("scopes","","A space or comma separated list of scopes for which the user will be authorized. These can either be full scopes, or just the portion after https://www.googleapis.com/auth/.");this.clientId_=this.registerFlag("clientId",CLIENT_ID,"The client ID of the app to authorize.");
this.immediate_=this.registerFlag("i",!1,"Whether to attempt to authorize immediately without bringing up a dialog.");this.cons_=b};goog.inherits(commands.Auth,commands.Command);
commands.Auth.prototype.execInternal=function(b,d,f,g){function h(){l&&l.parentNode.removeChild(l)}d=[];if(this.scopeStr_.get())for(d=this.scopeStr_.get().split(/[,\s]+/),f=0;f<d.length;f++)d[f].startsWith("https")||(d[f]="https://www.googleapis.com/auth/"+d[f]);else d=SCOPES;d={client_id:this.clientId_.get(),scope:d.join(" "),authuser:this.user_.get(),immediate:this.immediate_.get()};var k=new Deferred,l;"slient"!=b[0]&&(ginccount++,b="auth_"+ginccount,this.cons_.write('<a id="'+b+'" href="javascript:void(0)">Cancel Authorize</a>',
!0),l=_getid(b))&&(l.href="#",l.onclick=function(){k.errback("Authorize Canceled.");return!1});gapi.auth.authorize(d,function(b){b&&!b.error?Api.exec("GET","drive","v2","about",{}).addCallbacks(function(b){var d;if(b&&b.user){var f=b.user.emailAddress;b=b.user.displayName;f&&(d=b?b+" <"+f+">":f)}d?(this.cons_.write("Authorized as "+d+". Type token to get token info."),k.callback()):k.errback("Failed to authorize.");h()}.bind(this),function(b){k.errback("Failed to authorize "+b);h()}):(k.errback(b),
h())}.bind(this));return k};commands.Call=function(b,d){commands.Command.call(this,b,"Makes an API call. Usage: call [method] [collection/version/path]. Any flags not listed below are passed directly as parameters to the API call.\n\nExample: call GET drive/v2/files");this.body_=this.registerFlag("body","","A JSON representation of the body of the request.");this.fs_=d};goog.inherits(commands.Call,commands.Command);
commands.Call.prototype.execInternal=function(b,d,f,g){if(2>b.length)return Deferred.fail("Usage: call [method] [collection/version/path]");f=b[0];var h=b[1].split("/");if(3>h.length)return Deferred.fail("Usage: call [method] [collection/version/path]");b=h[0];g=h[1];var h=h.slice(2).join("/"),k=new Deferred;Api.exec(f,b,g,h,d,this.body_.get()).addCallbacks(function(b){$1=b;this.out.write(JSON.stringify(b,null,"  "));k.callback()}.bind(this),k.errback.bind(k));return k};
function g_authcheck(b,d){if(gapi&&gapi.auth&&gapi.auth.getToken()&&0>(gapi.auth.getToken().scope||"").indexOf(d))return b.out.write("(403) Insufficient Permission."),0>SCOPES.indexOf(d)&&SCOPES.push(d),b.out.write('<a href="#" onclick="gd_btn_login(true);return false">Authorize this permission, Click this link!</a>',!0),!0}var gcontactsdata={};
commands.Contacts=function(b,d){commands.Command.call(this,b,'List, find Google contacts. Usage: contacts [search keyword] [list count]. ex) contacts, contacts "john" 10, contacts "john" -t, contacts -n');this.fs_=d;this.sortdate_=this.registerFlag("t",!1,"Display sort by date.");this.sortdater_=this.registerFlag("tr",!1,"Display sort by date reverse.");this.nextpage_=this.registerFlag("n",!1,"Display the next page results.")};goog.inherits(commands.Contacts,commands.Command);
commands.Contacts.prototype.execInternal=function(b,d,f,g){function h(b){try{return henc(b||"")}catch(d){return console.log(b),"error"}}var k=new Deferred,l=this;if(g_authcheck(l,"https://www.googleapis.com/auth/contacts"))return k.callback(),k;if(d=l.nextpage_.get())gcontactsdata.itemsPerPage||(gcontactsdata.itemsPerPage=15);else{f=parseInt(b[1]);if(!f||1>f||isNaN(f))f=15;50<f&&(f=50);gcontactsdata.itemsPerPage=f;gcontactsdata.startIndex=1}d&&gcontactsdata.startIndex&&(gcontactsdata.startIndex+=
gcontactsdata.itemsPerPage);gcontactsdata.startIndex||(gcontactsdata.startIndex=1);var n=b[0]||"";b="https://www.google.com/m8/feeds/contacts/default/full?alt=json&q="+encodeURIComponent(n)+"&v=3.0&max-results="+gcontactsdata.itemsPerPage+"&start-index="+gcontactsdata.startIndex;l.sortdate_.get()?b+="&orderby=lastmodified&sortorder=descending":l.sortdater_.get()&&(b+="&orderby=lastmodified&sortorder=ascending");$.ajax({url:b,dataType:"jsonp",data:gapi.auth.getToken(),timeout:9E3,success:function(b){gcontactsdata=
{};if(b&&b.feed){var d="";try{gcontactsdata.itemsPerPage=parseInt(b.feed.openSearch$itemsPerPage.$t);gcontactsdata.startIndex=parseInt(b.feed.openSearch$startIndex.$t);gcontactsdata.totalResults=parseInt(b.feed.openSearch$totalResults.$t);d+='<span class="ls-item-folder">';b.feed.title||(b.feed.title={});d+="Title: "+h(b.feed.title.$t||"No Title");b.feed.author&&b.feed.author[0]&&(d+=" - "+h(b.feed.author[0].name.$t)+" ("+h(b.feed.author[0].email.$t)+")");d+="</span><table>";b.feed.entry||(b.feed.entry=
[]);for(var f,g,r,p=0;p<b.feed.entry.length;p++){f=b.feed.entry[p];d+='<tr><td class="highlight1">'+(gcontactsdata.startIndex+p)+'.<td class="highlight1">Name: <td>';g="";f.gd$name&&f.gd$name.gd$fullName?g=h(f.gd$name.gd$fullName.$t):f.title&&(g=h(f.title.$t));g=g?'<font class="highlight1">'+g+"</font>":g+'<font class="">No Name</font>';d+=g;f.updated&&(d+=" ("+proc_getdate({modifiedDate:f.updated.$t})+")");f.id&&f.id.$t&&(r=f.id.$t.split("/"),r[r.length-1]&&(s3="https://www.google.com/contacts/",
gd_email&&(s3+="?authuser="+encodeURIComponent(gd_email)),s3+="#contact/"+r[r.length-1],d+='&nbsp;<a href="'+s3+'" target="_blank">Link</a>'));if(f.gd$email)for(var d=d+"<tr><td><td>Email: <td>",s=0;s<f.gd$email.length;s++)0<s&&(d+=" &nbsp;"),d+=h(f.gd$email[s].address);if(f.gd$phoneNumber)for(d+="<tr><td><td>Phone: <td>",s=0;s<f.gd$phoneNumber.length;s++)0<s&&(d+=" &nbsp;"),d+=h(f.gd$phoneNumber[s].$t),f.gd$phoneNumber[s].uri&&(d+=" ("+h(f.gd$phoneNumber[s].uri)+")");if(f.gContact$website)for(d+=
"<tr><td><td>Website: <td>",s=0;s<f.gContact$website.length;s++)0<s&&(d+=" &nbsp;"),d+='<a href="'+f.gContact$website[s].href+'" target="_blank">'+h(f.gContact$website[s].href)+"</a>";if(f.gd$structuredPostalAddress)for(d+="<tr><td><td>Address: <td>",s=0;s<f.gd$structuredPostalAddress.length;s++)0<s&&(d+=" &nbsp;"),f.gd$structuredPostalAddress[s].gd$formattedAddress&&(d+=h(f.gd$structuredPostalAddress[s].gd$formattedAddress.$t))}0==b.feed.entry.length&&(d+="<tr><td>No results found");var d=d+"</table>",
w=Math.ceil(gcontactsdata.totalResults/gcontactsdata.itemsPerPage),A=Math.floor(gcontactsdata.startIndex/gcontactsdata.itemsPerPage)+1;A>w&&(A=w);d+='<span class="ls-item-folder">'+gseparate+"&nbsp;"+b.feed.entry.length+" results found. ("+A+"/"+w+" Page) "+henc(n);d=gcontactsdata.startIndex+gcontactsdata.itemsPerPage<gcontactsdata.totalResults?d+" ...[Next Page]":d+" ...[End]";d+="</span>"}catch(E){d="Error. "+E}l.out.write(d,!0)}else l.out.write("Error. No results found.");k.callback()},error:function(b,
d){"timeout"==d?l.out.write("Error. Timeout, There seems to be a problem with the connection."):l.out.write("Error.");k.callback()}});return k};commands.Contacts.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
function proc_more(b,d,f,g){function h(b){var d=_getid("layer_message");d.innerHTML=b;show_message(b,g.left,g.top,5,7E4,99);b=getWindowWidth()-50;g.left+d.offsetWidth>b&&(g.left=getScrollLeft()+b-d.offsetWidth);d.style.left=g.left+"px";b=getWindowHeight()-25;g.top+d.offsetHeight>b&&(g.top=getScrollTop()+b-d.offsetHeight);d.style.top=g.top+"px"}function k(b){if(b&&b.messages){var d=b.messages,f='<table id="moretable" width=500>'+("<tr><td colspan=2><b>Total "+d.length+' messages.</b> &nbsp;<a href="#" onclick="hide_message();return false" style="font-size:15px">Close</a>'),
g="https://mail.google.com/";gd_email&&(g+="?authuser="+encodeURIComponent(gd_email));g+="#inbox/"+b.id;f+=' &nbsp;<a href="'+g+'" target="_blank">Link</a>';b=0;for(var k=new Date,q=0;q<d.length;q++)if(d[q].payload){var r=d[q].payload.headers;if(r){0<b&&(f+='<tr><td colspan=2 style="border-bottom:1px solid black">');for(var g={},p=0;p<r.length;p++)r[p].name&&(g[r[p].name]=r[p].value);g.Subject&&(f+="<tr><td><font class=header1>Subject</font> <td>"+henc(g.Subject));g.From&&(f+="<tr><td><font class=header1>From</font> <td>"+
henc(g.From));g.Date&&(f+="<tr><td><font class=header1>Date</font> <td>"+henc(getdatetime(g.Date,k)));d[q].labelIds&&0<d[q].labelIds.length&&(f+="<tr><td><font class=header1>Label</font> <td>"+d[q].labelIds.join(",").toLowerCase());f+="<tr><td colspan=2>"+d[q].snippet;b++;if(6<b){f+="<tr><td colspan=2>More messages...";break}}}f+='<tr><td align=center colspan=2><a href="#" onclick="hide_message();return false" style="font-size:15px">Close</a></table></table>'}else{var f="Error. ";b&&b.error&&b.error.message&&
(f+=henc(b.error.message))}h(f)}g||(g=getOffset(d),g.top=g.top-_getid("cons").scrollTop+d.offsetHeight,g.left-=150,0>g.left&&(g.left=0));b!=gcount?h("Can not view this. Please select from last list."):d&&k(gresults[f])}
commands.Gmail=function(b,d){commands.Command.call(this,b,'List, move gmail messages. Usage: gmail [search keyword] [list count].\nex) gmail "category:primary invoice" 10, gmail "category:personal has:attachment" 30 -tr, gmail "" 20, gmail " " (all, no search filter)');this.fs_=d;this.sortdater_=this.registerFlag("tr",!1,"Display sort by date reverse.");this.nextpage_=this.registerFlag("n",!1,"Display the next page results.");this.moveto_=this.registerFlag("m",!1,"Move mail threads to specific label. Usage: gmail [number range] [trash,inbox,spam,read,unread] -m\nex) gmail 5 trash -m, gmail 1,2 trash -m, gmail 1-10 read -m");
this.addlabel_=this.registerFlag("la",!1,"Add label to mail threads. Usage: gmail [number range] [Label ID: important,starred..] -la ex) gmail 1,2 important -la, gmail 1-10 starred -la");this.removelabel_=this.registerFlag("lr",!1,"Remove label from mail threads. Usage: gmail [number range] [Label ID: important,starred..] -lr ex) gmail 1,2 important -lr, gmail 1-10 starred -lr")};goog.inherits(commands.Gmail,commands.Command);
commands.Gmail.prototype.execInternal=function(b,d,f,g){function h(){function d(){var b="Usage: gmail [number range] [trash,inbox,spam,read,unread] -m ex) gmail 5 trash -m, gmail 1,2 trash -m, gmail 1-10 read -m";v?b="Usage: gmail [number range] [Label ID: important,starred..] -la ex) gmail 1,2 important -la, gmail 1-10 starred -la":q&&(b="Usage: gmail [number range] [Label ID: important,starred..] -lr ex) gmail 1,2 important -lr, gmail 1-10 starred -lr");t.out.write(b);n.callback()}function f(b){b||
(b={});if(b.error)n.errback(JSON.stringify(b,null,"  "));else{var d,g,h=0;for(x in b)(d=b[x].result)&&d.id&&d.messages?h++:(g,g="Error. "+x+" ->",b[x].error?(b[x].error.code&&(g+=" ("+b[x].error.code+")"),g+=" "+(b[x].error.message||"")):g+=" Unknown Error.",t.out.write(g,!0));t.out.write("<font class=highlight1>"+h+" results were successful.</font>",!0);n.callback()}}if(b[0]&&b[1]){var g=[],h=[],k=b[1].toLowerCase();if(v)g.push(b[1].toUpperCase());else if(q)h.push(b[1].toUpperCase());else if("trash"==
k)g.push("TRASH");else if("inbox"==k)g.push("INBOX");else if("spam"==k)g.push("SPAM");else if("read"==k)h.push("UNREAD");else if("unread"==k)g.push("UNREAD");else{d();return}var l=b[0],k=[];if(0<=l.indexOf(","))k=l.split(",");else if(0<=l.indexOf("-")){var r=l.split("-");if(2==r.length){l=parseInt(r[0]);r=parseInt(r[1]);if(!l||isNaN(l)||!r||isNaN(r)){d();return}for(;l<=r;l++)k.push(l)}}else k.push(l);if(0==k.length)d();else{for(var z=[],D=gapi.client.newBatch(),l=0;l<k.length;l++)r=k[l]-1,gresults[r]&&
(z.push(r+1),D.add(gapi.client.gmail.users.threads.modify({userId:"me",id:gresults[r].id,addLabelIds:g,removeLabelIds:h})));t.out.write("<font>Numbers in the last list: "+(z.join(",")||"None")+"</font>",!0);t.out.write("Trying "+z.length+" mail threads...");0==z.length?f({}):D.execute(f)}}else d()}function k(b,d,f,g){var h=function(f,k){f.execute(function(l){if(l.error)k=[],n.errback(JSON.stringify(l,null,"  "));else{var q=l.nextPageToken;k=k.concat(l.threads);k.length>=p?g(k,q):q?(f=gapi.client.gmail.users.threads.list({userId:b,
maxResults:p,q:d,fields:"threads/id,nextPageToken",pageToken:q}),h(f,k)):g(k,q)}})},k="";f&&(k=gsearchdata.nextPageToken||"",d=gsearchdata.query||"");f=gapi.client.gmail.users.threads.list({userId:b,maxResults:p,q:d,fields:"threads/id,nextPageToken",pageToken:k});h(f,[])}function l(){var b=t.nextpage_.get();if(b&&!gsearchdata.nextPageToken){if(gsearchdata.query){t.out.write("No found the next page.");n.callback();return}b=!1}b&&(r=gsearchdata.query||"");k("me",r,b,function(d,f){function g(h){h||(h=
{});if(h.error)n.errback(JSON.stringify(h,null,"  "));else{gcount++;gresults=[];gsearchdata.nextPageToken=f;gsearchdata.query=r;b?(gsearchdata.page||(gsearchdata.page=0),gsearchdata.page+=1):gsearchdata.page=0;var k,l,q,m=[];for(x in h)(k=h[x].result)&&k.messages&&0!=k.messages.length&&k.messages[0].payload&&k.messages[0].payload.headers&&m.push(k);for(h=0;h<d.length;h++)if(d[h])for(var p=0;p<m.length;p++)if(d[h].id==m[p].id){gresults.push(m[p]);m.splice(p,1);break}var m='<span class="ls-item-folder">'+
gseparate+"</span><table cellpadding=0>",v=0,u=new Date;s&&gresults.reverse();for(h=0;h<gresults.length;h++){k=gresults[h];q={};l=k.messages[0].payload.headers;for(p=0;p<l.length;p++)l[p].name&&(q[l[p].name]=l[p].value);q.Subject||(q.Subject="No subject");k.messages[0].snippet||(k.messages[0].snippet="No snippet");k.subject=q.Subject;k.from=q.From||"Unknown From";k.date=q.Date||"Unknown Date";m+="<tr><td>"+(h+1)+". ";0<=k.messages[0].labelIds.indexOf("UNREAD")&&(m+="<b>");m+=henc(cutstring(q.Subject,
110));0<=k.messages[0].labelIds.indexOf("UNREAD")&&(m+="</b>");m+='&nbsp;<a href="#" onclick="proc_more('+gcount+",this,"+h+');return false">More...</a>';1<k.messages.length&&(m+='<font class="ls-item-folder">('+k.messages.length+")</font>");p="https://mail.google.com/";gd_email&&(p+="?authuser="+encodeURIComponent(gd_email));p+="#inbox/"+k.id;m+='&nbsp;<a href="'+p+'" target="_blank">Link</a>';k.messages[0].labelIds&&0<k.messages[0].labelIds.length&&(m+=" ("+k.messages[0].labelIds.join(",").toLowerCase()+
")");m+='<div style="margin-bottom:2px">';q.Date&&(m+=" <font class=highlight1>"+henc(getdatetime(q.Date,u))+"</font> &nbsp;");q.From&&(m+=' <font class="ls-item-folder">'+henc(q.From)+"</font> &nbsp;");q=k.messages[0].payload.mimeType||"";k.messages[0].sizeEstimate&&0==q.indexOf("multipart/")&&(m+="<font class=highlight1>"+getsize(k.messages[0].sizeEstimate)+"</font>");m+="</div>";v++}0==v&&(m+="<tr><td>No results found");m=m+"</table>"+('<span class="ls-item-folder">'+gseparate+"&nbsp;"+gresults.length+
" results found. ("+(gsearchdata.page+1)+" Page) "+henc(r));m=f?m+" ...[Next Page]":m+" ...[End]";m+="</span>";t.out.write(m,!0);n.callback()}}if(d){for(var h=gapi.client.newBatch(),k=0,l=0;l<d.length;l++)d[l]&&d[l].id&&(k++,h.add(w(d[l].id,{format:"metadata"})));0==k?g({}):h.execute(g)}else t.out.write("Error!!"),n.callback()})}var n=new Deferred,t=this;if(g_authcheck(t,"https://mail.google.com/"))return n.callback(),n;var u=this.moveto_.get(),v=this.addlabel_.get(),q=this.removelabel_.get(),r,p,
s=this.sortdater_.get();gapi.client.load("gmail","v1",function(){if(u||v||q)h();else{r=b[0]||"category:primary";p=parseInt(b[1]);if(!p||1>p||isNaN(p))p=15;50<p&&(p=50);l()}});var w=function(b,d){return gapi.client.request({path:"gmail/v1/users/me/threads/"+b,params:d})};return n};commands.Gmail.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};commands.Cat=function(b,d){commands.Command.call(this,b,"Displays the contents of a file. Usage: cat [filename]");this.fs_=d};
goog.inherits(commands.Cat,commands.Command);
commands.Cat.prototype.execInternal=function(b,d,f,g){if(1>b.length)return Deferred.fail("Usage: cat [filename]");var h=new Deferred;this.fs_.resolve(b[0]).addCallbacks(function(d){d=util.array.map(d,function(b){return b[b.length-1]});var f;d=util.array.first(d,function(b){f=b.fileSize;return!!b.downloadUrl});if(!d)return h.errback(b[0]+" cannot be displayed");var g=d.mimeType.startsWith("image"),t=gViewMaxSize;if(f>1048576*t)return h.errback(b[0]+" size is too large to view. ("+t+" MB limit)");d=
Api.get(d.downloadUrl,g);d.addCallbacks(function(b){g?this.out.writeImg((window.URL||window.webkitURL).createObjectURL(b)):this.out.write(b)}.bind(this),null);h.follow(d)}.bind(this),h.errback.bind(h));return h};commands.Cat.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};commands.Cd=function(b,d){commands.Command.call(this,b,"Change the current working directory. Usage cd [path or ..].");this.fs_=d};goog.inherits(commands.Cd,commands.Command);
commands.Cd.prototype.execInternal=function(b,d,f,g){return 1>b.length?Deferred.fail("Usage: cd [path]"):this.fs_.cd(b[0])};commands.Cd.prototype.getTabCompleter=function(){return this.fs_.folderPathTabCompleter};
commands.Connect=function(b,d,f){commands.Command.call(this,b,"Connects this cons to a drive instance.");this.qual_=this.registerFlag("q",!1,"Whether to use the qual root. If provided, this will override the -root flag.");this.root_=this.registerFlag("root","prod",'The API root to connect to. This should be of the form "https://content-googleapis-test.sandbox.google.com". But you can also provide qual or prod as aliases for the TEST and PROD roots.');this.showinfo_=this.registerFlag("info",!1,"Display only the current user information, quota for Drive.");
this.fs_=d;this.apps_=f};goog.inherits(commands.Connect,commands.Command);
commands.Connect.prototype.execInternal=function(b,d,f,g){var h=new Deferred;b=this.qual_.get()?"qual":this.root_.get();switch(b){case "qual":Api.root=QUAL_URL;break;case "prod":Api.root=void 0;break;default:Api.root=b}var k=this.showinfo_.get();b=Api.exec("GET","drive","v2","about",{});k?c.write('<span class="highlight1">Get the user information for Drive...</span>',!0):c.write('<span class="highlight1">Connecting to Drive...</span>',!0);b.addCallbacks(function(b){if(k){var d=function(b,d,g,h){b&&
(b[d]&&(f+="<tr><td>"+henc(h||d)+"<td>"),f=g?f+(number_format(b[d])+" ("+getsize(b[d])+")"):f+henc(b[d]))},f="<table>";d(b,"name");b&&b.user&&(b.user.picture&&b.user.picture.url&&(f+='<tr><td>picture<td><img src="'+b.user.picture.url+'" height=80>'),d(b.user,"displayName"),d(b.user,"emailAddress"));d(b,"quotaBytesTotal",!0);d(b,"quotaBytesUsed",!0);if(b&&b.quotaBytesByService)for(var g=0;g<=b.quotaBytesByService.length-1;g++)d(b.quotaBytesByService[g],"bytesUsed",!0,"quotaByService("+b.quotaBytesByService[g].serviceName+
")");d(b,"rootFolderId");d(b,"languageCode");f+="</table>";c.write(f,!0);h.callback()}else this.apps_.init(),b=this.fs_.init(b.rootFolderId),b.addCallbacks(function(){ginitfolder=!0}.bind(this),null),h.follow(b)}.bind(this),h.errback.bind(h));return h};
commands.Dcall=function(b,d){commands.Call.call(this,b,"Makes a Drive API call. Usage: call [method] [path]. Any flags not listed below are passed directly as parameters to the API call.\n\nExample: call GET drive/v2/files");this.version_=this.registerFlag("version","v2","The version of the Drive API to use.");this.fs_=d};goog.inherits(commands.Dcall,commands.Call);
commands.Dcall.prototype.execInternal=function(b,d,f,g){if(2>b.length)return Deferred.fail("Usage: call [method] [path]");b[1]="drive/"+this.version_.get()+"/"+b[1];return commands.Dcall.superClass_.execInternal.call(this,b,d,f,g)};commands.Edit=function(b,d){commands.Command.call(this,b,"Edit a file or create a new one. Usage: edit [filename] [MIME type]");this.fs_=d};goog.inherits(commands.Edit,commands.Command);
commands.Edit.prototype.execInternal=function(b,d,f,g){if(1>b.length)return Deferred.fail("Usage: edit [filename] [MIME type]");var h=new Deferred;this.fs_.resolve(b[0]).addCallbacks(function(d){d=util.array.map(d,function(b){return b[b.length-1]});var f;if(d=util.array.first(d,function(b){f=b.fileSize;return!!b.downloadUrl})){var g=gViewMaxSize;if(f>1048576*g)return h.errback(b[0]+" size is too large to edit. ("+g+" MB limit)");d=new commands.Edit.Editor(d);h.follow(d.show(!0))}else h.errback(b[0]+
" cannot be edited inline, try to click the open link.")}.bind(this),function(){this.fs_.mkfile(b[0],b[1]||"text/plain").addCallbacks(function(b){b=new commands.Edit.Editor(b);h.follow(b.show(!0))},h.errback.bind(h))}.bind(this));return h};commands.Edit.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};commands.Edit.Editor=function(b){this.file_=b;this.deferred_=new Deferred;this.commandInput_=this.textArea_=this.editControl_=null;this.createDom_()};
commands.Edit.Editor.DEFAULT_MSG_="Esc enters command mode. w saves, q quits, and wq saves and quits.";
commands.Edit.Editor.prototype.createDom_=function(){this.editControl_=$("<div/>",{id:"fullpagecontrol",class:"full-page-control"});if(this.editControl_[0]){var b=getstorage("c_fontsize")||"14";this.editControl_[0].style.fontSize=b+"px"}this.textArea_=$("<textarea/>",{id:"editortextarea",class:"editor-text-area"});this.textArea_[0]&&this.textArea_[0].setAttribute("spellcheck","false");this.commandInput_=$("<input/>",{class:"editor-input"});this.commandInput_[0]&&this.commandInput_[0].setAttribute("spellcheck",
"false");this.editControl_.append(this.textArea_);this.editControl_.append(this.commandInput_);this.textArea_.on("keydown",this.onKeyDown_.bind(this));this.commandInput_.on("keydown",this.onCommandKeyDown_.bind(this))};commands.Edit.Editor.prototype.onKeyDown_=function(b){if(27==b.keyCode)return this.commandInput_.val(""),this.commandInput_.focus(),b.preventDefault(),!1};
commands.Edit.Editor.prototype.onCommandKeyDown_=function(b){var d=!1;13==b.which?(util.doLater(this.submit_.bind(this)),d=!0):27==b.keyCode&&(this.write_(commands.Edit.Editor.DEFAULT_MSG_),this.textArea_.focus(),d=!0);if(d)return b.preventDefault(),!1};
commands.Edit.Editor.prototype.submit_=function(){var b=this.commandInput_.val().split("");this.commandInput_.val("");this.textArea_.focus();var d=Deferred.succeed();0<=$.inArray("w",b)&&(d=this.save_());0<=$.inArray("q",b)&&d.addCallback(function(){this.editControl_.remove();this.deferred_.callback()}.bind(this))};commands.Edit.Editor.prototype.write_=function(b){this.commandInput_.val(b)};
commands.Edit.Editor.prototype.show=function(){$("body").append(this.editControl_);window.gd_btn_login2&&gd_btn_login2();this.textArea_.focus();var b=this;this.write_("Loading "+this.file_.title+"...");Api.get(this.file_.downloadUrl).addCallbacks(this.handleFileLoaded_.bind(this),function(d){b.write_("Error loading "+b.file_.title+": "+d)});return this.deferred_};commands.Edit.Editor.prototype.handleFileLoaded_=function(b){this.textArea_.val(b);this.textArea_[0].setSelectionRange(0,0);this.write_(commands.Edit.Editor.DEFAULT_MSG_)};
commands.Edit.Editor.prototype.save_=function(){var b={"Content-Type":this.file_.mimeType||"text/plain"},b=Api.exec("PUT","drive","v2","files/"+this.file_.id,{uploadType:"media",alt:"json"},this.textArea_.val(),!0,b);this.write_("Saving "+this.file_.title+"...");b.addCallbacks(function(){this.write_("Saved")}.bind(this),function(){this.write_("Error saving "+this.file_.title)}.bind(this));return b};commands.Js=function(b){commands.Command.call(this,b,"Execute arbitrary javascript. Output is the output of the execution.")};
goog.inherits(commands.Js,commands.Command);commands.Js.prototype.execInternal=function(b,d,f,g){this.out.write(""+eval(g.split(" ").slice(1).join(" ")));return Deferred.succeed()};
commands.Ls=function(b,d){commands.Command.call(this,b,"List files in the current directory. Usage: ls [file-pattern or folder] [option]. ex) ls *.pdf -al -tr");this.fs_=d;this.showall_=this.registerFlag("al",!1,"Display detail list.");this.sortdate_=this.registerFlag("t",!1,"Display sort by date.");this.sortdater_=this.registerFlag("tr",!1,"Display sort by date reverse.");this.sortsize_=this.registerFlag("s",!1,"Display sort by filesize.");this.sortsizer_=this.registerFlag("sr",!1,"Display sort by filesize reverse.");
this.folderOnly_=this.registerFlag("d",!1,"Whether to list directories only.");this.force_=this.registerFlag("f",!1,"Whether to requery the API. If not set, this will list files from a cache");this.showtrash_=this.registerFlag("trash",!1,"Display the trashed file list. this will list files without cache");this.shareme_=this.registerFlag("shareme",!1,"Display files that have been shared with me. this will list files without cache");this.entire_=this.registerFlag("entire",!1,"Find from the entire drive.");
this.nextpage_=this.registerFlag("n",!1,"Display the next page results. Works with -f, -trash, -shareme, -entire options.");this.downlink_=this.registerFlag("down",!1,"Create the downloadable link in the list. default is the viewable link.")};goog.inherits(commands.Ls,commands.Command);
commands.Ls.prototype.execInternal=function(b,d,f,g){var h;d=[];if(b[0]&&0<=b[0].indexOf("*")){h=b[0];f=h.split("*");for(g=0;g<=f.length-1;g++)f[g]=trim(f[g]),f[g]&&d.push(f[g].replace(/(\?)/g,""));b[0]=""}var k=this.entire_.get(),l=this.showtrash_.get(),n=this.shareme_.get();f=this.nextpage_.get();b=this.fs_.ls({isFolder:this.folderOnly_.get(),force:this.force_.get(),showtrash:l,shareme:n,entire:k,nextpage:f,filter:d||[]},b[0]);var t=new Deferred,u=this.showall_.get(),v=this.sortdate_.get(),q=this.sortdater_.get(),
r=this.sortsize_.get(),p=this.sortsizer_.get(),s=this.downlink_.get();b.addCallbacks(function(b){var d=b.items;if(h){for(var f=h,f=f.replace(/\./g,"\\.").replace(/\?/g,"\\?").replace(/\x2a/g,"(.*)"),f=new RegExp("^"+f+"$","i"),g=[],m=0;m<=d.length-1;m++)d[m].title&&d[m].title.match(f)&&g.push(d[m]);d=g}v||q?d.sort(function(b,d){var f=b.modifiedDate||0,g=d.modifiedDate||0,f=f>g?-1:f<g?1:0;q&&(f*=-1);return f}):(r||p)&&d.sort(function(b,d){var f=parseInt(b.fileSize),g=parseInt(d.fileSize);if(!f||isNaN(f))f=
0;if(!g||isNaN(g))g=0;f=f>g?-1:f<g?1:0;p&&(f*=-1);return f});if(0==d.length)m=$("<div/>",{class:"output-block"}),m.html("No found files and folders."),this.out.writeHTML(m);else{var B="";gapi.auth.getToken()&&(B=encodeURIComponent(gapi.auth.getToken().access_token));var C="";ischrome||isfirefox||(C=' target="_blank"');if(u){for(var f="<table>",y,m=0;m<d.length;m++)d[m].mimeType==FOLDER_MIMETYPE?(y='class="ls-item-folder"',f+="<tr "+y+' data="'+escape(d[m].title)+'"><td width=80>Folder<td>0'):(y='style="white-space:nowrap"',
f+='<tr data="'+escape(d[m].title)+'"><td><span style="white-space:nowrap">'+(d[m].fileSize||"?")+'&nbsp;</span><td><span style="white-space:nowrap">'+getsize(d[m].fileSize)+"&nbsp;</span>"),f+='<td><span style="white-space:nowrap">'+proc_getdate(d[m])+"&nbsp;</span>",g=d[m].parents,f+="<td>",l?(f+="<a href=\"#\" onclick=\"ls_action(this,'untrash','"+d[m].id+'\');return false" title="Untrash">[U]</a>',f+="<a href=\"#\" onclick=\"ls_action(this,'delete','"+d[m].id+'\');return false" title="Delete">[D]</a>'):
(f+="<a href=\"#\" onclick=\"ls_action(this,'trash','"+d[m].id+'\');return false" title="Trash">[T]</a>',f+="<a href=\"#\" onclick=\"ls_action(this,'delete','"+d[m].id+'\');return false" title="Delete">[D]</a>',(k||l||n)&&g&&0<g.length&&g[0].id&&(f+="<a href=\"#\" onclick=\"ls_action(this,'setpath','"+g[0].id+'\');return false" title="Set path to the parent folder\nFolder ID: '+g[0].id+'">[G]</a>')),f+="<td>",f=g&&0<g.length&&g[0].id?f+('<a href="'+gd_weburl()+"#folders/"+g[0].id+'" target="_blank" onclick="gd_clickweburl(this)" title="Show parent folder\nFolder ID: '+
henc(g[0].id)+'"><span '+y+">[F]</span></a>"):f+"?",d[m].mimeType==FOLDER_MIMETYPE?f+='<td><a href="'+gd_weburl()+"#folders/"+d[m].id+'" target="_blank" onclick="gd_clickweburl(this)" title="Show folder"><span '+y+">"+henc(d[m].title)+"</span></a>":(f+="<td>",f=s?d[m].downloadUrl||!window.gd_loadfile?f+('<a href="'+(d[m].downloadUrl+"&access_token="+B)+'" title="'+henc(d[m].mimeType)+'" download="'+henc(d[m].title)+'"'+C+">"):f+('<a href="#" onclick="gd_loadfile(\''+d[m].id+'\',false,true);return false;" title="'+
henc(d[m].mimeType)+'">'):f+('<a href="#" onclick="proc_gview(\''+d[m].id+'\');return false" title="'+henc(d[m].mimeType)+'">'),f+=henc(d[m].title)+"</a>"),!l&&d[m].labels&&d[m].labels.trashed&&(f+=" (trashed)"),d[m].shared&&(f+=' <a href="#" class="highlight2" onclick="ls_action(this,\'shareinfo\',\''+d[m].id+"','"+d[m].alternateLink+'\');return false" title="Share Permissions Information">(shared)</a>');f+="</table>";m=$("<div/>",{class:"output-block"});m.html(f);this.out.writeHTML(m)}else this.out.writeList(d,
function(b){return b.title},function(b){return b.mimeType==FOLDER_MIMETYPE?"ls-item-folder":""},function(b){var d;b.mimeType==FOLDER_MIMETYPE?d='<a href="'+gd_weburl()+"#folders/"+b.id+'" target="_blank" onclick="gd_clickweburl(this)" title="Show folder"><span class="ls-item-folder">'+b.title+"</a>":(d=s?b.downloadUrl||!window.gd_loadfile?'<a href="'+(b.downloadUrl+"&access_token="+B)+'" title="'+henc(b.mimeType)+'" download="'+henc(b.title)+'"'+C+">":'<a href="#" onclick="gd_loadfile(\''+b.id+'\',false,true);return false;" title="'+
henc(b.mimeType)+'">':'<a href="#" onclick="proc_gview(\''+b.id+'\');return false" title="'+henc(b.mimeType)+'">',d+=b.title+"</a>");!l&&b.labels&&b.labels.trashed&&(d+=" (trashed)");return d});b.lsForce&&(gsearchdata.lsPageToken=b.nextPageToken,f='<span class="ls-item-folder">'+gseparate+"&nbsp;"+d.length+" results found. ("+(gsearchdata.lsPage+1)+" Page) ",f=b.nextPageToken?f+" ...[Next Page]":f+" ...[End]",f+="</span>",m=$("<div/>",{class:"output-block"}),m.html(f),this.out.writeHTML(m))}t.callback()}.bind(this),
t.errback.bind(t));return t};commands.Ls.prototype.getTabCompleter=function(){return this.fs_.folderPathTabCompleter};
function ls_action(b,d,f,g){function h(b){var d="";b&&(b.error&&b.error.message?d+=b.error.message:b.message&&(d+=b.message));return d}function k(b){hide_message();gd_isdownloading=!1;(b=h(b))?alert(b):fs&&fs.removeFile_(f)}var l={trash:"Trash...",untrash:"Untrash...",setpath:"Set path to the parent folder...","delete":"Delete...",shareinfo:"Share Permissions Information..."};if(l[d]){var n="";b&&b.parentNode&&b.parentNode.parentNode&&(n=unescape(b.parentNode.parentNode.getAttribute("data")||""));
n||(n=f);if("delete"==d)for(b=1;2>=b;b++)if(!confirm("Delete this item.\n\n"+n+"\n\nAre you sure? ["+b+"/2]"))return;if(gd_isdownloading)alert("It's working. Please try again later.");else if(gd_isdownloading=!0,show_message(henc(l[d]+" "+n),"","","",3E4),"trash"==d)d=gapi.client.drive.files.trash({fileId:f}),d.execute(k);else if("untrash"==d)d=gapi.client.drive.files.untrash({fileId:f}),d.execute(k);else if("delete"==d)d=gapi.client.drive.files["delete"]({fileId:f}),d.execute(k);else if("setpath"==
d){var t=function(b){gapi.client.drive.files.get({fileId:b}).execute(function(b){b&&b.id?(u.push(b),(b=b.parents)&&b[0]&&b[0].id?t(b[0].id):(hide_message(),gd_isdownloading=!1,u.reverse(),fs.setPath_(u))):(hide_message(),gd_isdownloading=!1,(b=h(b))&&alert(b))})},u=[];t(f)}else"shareinfo"==d&&(d=gapi.client.drive.permissions.list({fileId:f}),d.execute(function(b){hide_message();gd_isdownloading=!1;if(b&&b.items){for(var d='<div style="margin-left:2px"><b>Permissions Information</b><div class=filename><a href="'+
(g||"https://drive.google.com/file/d/"+f+"/view")+'" title="View a file, Change permissions." target="_blank">'+henc(n)+"</a></div></div><table>",h,k=0;k<=b.items.length-1;k++)d+='<tr><td colspan=2 style="border-bottom:1px solid black">',h=b.items[k],h.name?(d+="<tr><td>",d=h.photoLink?d+('<img src="'+h.photoLink+'" width=50>'):d+'<img src="//iblogbox.github.io/js/img/etc/profile-img.jpg" width=50>',d+="<td>Name: "+henc(h.name)+"<br>",d+="Role: "+(h.role||"")+"<br>",d+=henc("Email: "+(h.emailAddress||
"")+", Domain: "+(h.domain||""))):(d+="<tr><td><td>Name: "+h.type+" ("+h.id+")<br>",d+="Role: "+(h.role||""));d+='<tr><td colspan=2 style="border-bottom:1px solid black"><tr><td align=center colspan=2><a href="#" onclick="hide_message();return false">Close</a></table>';show_message(d,"","","",36E5)}else show_message("Error!! "+n)}))}}commands.Man=function(b){commands.Command.call(this,b,"Get help for the given command. Usage help [cmd].");this.cons_=b};goog.inherits(commands.Man,commands.Command);
commands.Man.prototype.execInternal=function(b,d,f,g){if(1>b.length)return Deferred.fail("Usage: man [cmd]");(b=this.cons_.getCmd(b[0]))?b.help():this.out.write("No help for "+f[0]+". Command isn't installed");return Deferred.succeed()};commands.Man.prototype.getTabCompleter=function(){return this.cons_.getCommandTabCompleter()};commands.Rename=function(b,d){commands.Command.call(this,b,"Rename a file or directory. Usage: rename [filename] [newfilename].");this.fs_=d};
goog.inherits(commands.Rename,commands.Command);commands.Rename.prototype.execInternal=function(b,d,f,g){return 2>b.length?Deferred.fail("Usage: rename [filename] [newfilename]"):this.fs_.rename(b[0],b[1])};commands.Rename.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};commands.Clear=function(b){commands.Command.call(this,b,"Clear screen. Usage clear.")};goog.inherits(commands.Clear,commands.Command);
commands.Clear.prototype.execInternal=function(b,d,f,g){_getid("output").innerHTML="";this.out.outputcount=0;return Deferred.succeed()};commands.Help=function(b){commands.Command.call(this,b,"Display help.")};goog.inherits(commands.Help,commands.Command);commands.Help.prototype.execInternal=function(b,d,f,g){b=_getid("helpdata").value;this.out.write(b,!0);return Deferred.succeed()};
commands.History=function(b,d){commands.Command.call(this,b,"Display all command line history. Usage: history.");this.clearall_=this.registerFlag("c",!1,"Clear all command line history.")};goog.inherits(commands.History,commands.Command);
commands.History.prototype.execInternal=function(b,d,f,g){this.clearall_.get()?(this.out.history_=[],this.out.historyCursor_=this.out.history_.length,setstorage("c_cmdhistory",JSON.stringify(this.out.history_)),b="All history cleared."):b=this.out.history_.join("\n");this.out.write(b);return Deferred.succeed()};commands.History.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
commands.Mkdir=function(b,d){commands.Command.call(this,b,"Create a directory in the current directory. Usage mkdir [foldername].");this.fs_=d};goog.inherits(commands.Mkdir,commands.Command);commands.Mkdir.prototype.execInternal=function(b,d,f,g){return 1>b.length?Deferred.fail("Usage: mkdir [foldername]"):this.fs_.mkfile(b[0],FOLDER_MIMETYPE)};
commands.Mkfile=function(b,d){commands.Command.call(this,b,"Create a file in the current directory. Usage mkfile [name] [MIME type]. ex) mkfile test.txt text/plain");this.fs_=d};goog.inherits(commands.Mkfile,commands.Command);commands.Mkfile.prototype.execInternal=function(b,d,f,g){return 2>b.length?Deferred.fail("Usage mkfile [name] [MIME type]"):this.fs_.mkfile(b[0],b[1])};
commands.Rm=function(b,d){commands.Command.call(this,b,"Deletes a file or folder from the given directory. Usage: rm [filename or folder].");this.fs_=d};goog.inherits(commands.Rm,commands.Command);commands.Rm.prototype.execInternal=function(b,d,f,g){return 1>b.length?Deferred.fail("Usage: rm [filename or folder]"):this.fs_.rm(b[0])};commands.Rm.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
commands.Trash=function(b,d){commands.Command.call(this,b,"Trash a file or folder from the given directory. Usage: trash [filename or folder].");this.fs_=d};goog.inherits(commands.Trash,commands.Command);commands.Trash.prototype.execInternal=function(b,d,f,g){return 1>b.length?Deferred.fail("trash [filename or folder]"):this.fs_.rm(b[0],"trash")};commands.Trash.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
commands.Info=function(b){commands.Command.call(this,b,"Display the current user information, quota for Drive. Usage: info.");this.cons_=b};goog.inherits(commands.Info,commands.Command);commands.Info.prototype.execInternal=function(b,d,f,g){return this.cons_.execStr("connect -info")};commands.Trashs=function(b,d){commands.Command.call(this,b,"Display the trashed file list. this will list files without cache. Display sort by date reverse. Usage: trashs.");this.fs_=d;this.cons_=b};
goog.inherits(commands.Trashs,commands.Command);commands.Trashs.prototype.execInternal=function(b,d,f,g){return this.cons_.execStr("ls --trash --tr --al")};commands.Trashs.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};commands.Emptytrash=function(b,d){commands.Command.call(this,b,"Deletes all of the trashed files. Usage: emptytrash.");this.fs_=d};goog.inherits(commands.Emptytrash,commands.Command);
commands.Emptytrash.prototype.execInternal=function(b,d,f,g){return this.fs_.rm("","emptytrash")};commands.Emptytrash.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
commands.Find=function(b,d){commands.Command.call(this,b,"Find from the entire drive or current folder. Display sort by date reverse. Usage: find [keyword or file-pattern or none].\nex) find pdf, find *.pdf -c, find *pdf* -down, find (recently changed)");this.fs_=d;this.cons_=b;this.current_=this.registerFlag("c",!1,"Find in the current folder.");this.nextpage_=this.registerFlag("n",!1,"Display the next page results.");this.downlink_=this.registerFlag("down",!1,"Create the downloadable link in the list. default is the viewable link.")};
goog.inherits(commands.Find,commands.Command);commands.Find.prototype.execInternal=function(b,d,f,g){d=(b[0]||"").replace(/(\'|\")/g,"");b=""==d?"ls --tr --al":0>b[0].indexOf("*")?'ls "*'+d+'*" --tr --al':'ls "'+d+'" --tr --al';b=this.current_.get()?b+" --f":b+" --entire";this.downlink_.get()&&(b+=" --down");this.nextpage_.get()&&(b+=" --n");return this.cons_.execStr(b)};commands.Find.prototype.getTabCompleter=function(){return this.fs_.pathTabCompleter};
commands.SetRoot=function(b){commands.Command.call(this,b,"Sets the root to use for all API calls. Usage: setRoot [qual|prod|ROOT_URL]");this.cons_=b};goog.inherits(commands.SetRoot,commands.Command);commands.SetRoot.prototype.execInternal=function(b,d,f,g){return 1>b.length?Deferred.fail("Usage: setRoot [qual|prod|ROOT_URL]"):this.cons_.execStr("connect --root="+b[0])};
commands.Start=function(b){commands.Command.call(this,b,"Authorizes then connects. All flags are passed through to auth and connect. See man connect and man auth for details");this.cons_=b};goog.inherits(commands.Start,commands.Command);
commands.Start.prototype.execInternal=function(b,d,f,g){var h=new Deferred;this.cons_.execStr('auth "slient" '+g.split(" ").slice(1).join(" ")).addCallbacks(function(b){h.follow(this.cons_.execStr("connect "+g.split(" ").slice(1).join(" ")))}.bind(this),h.errback.bind(h));return h};commands.Token=function(b){commands.Command.call(this,b,"Displays the current auth token. Usage: token")};goog.inherits(commands.Token,commands.Command);
commands.Token.prototype.execInternal=function(b,d,f,g){this.out.write(JSON.stringify(gapi.auth.getToken(),null,"  "));return Deferred.succeed()};var gd_upicker,lastuploadid;commands.Upload=function(b,d){commands.Command.call(this,b,"Upload files to the current folder. Usage: upload");this.fs_=d;this.cons_=b};goog.inherits(commands.Upload,commands.Command);
commands.Upload.prototype.execInternal=function(b,d,f,g){var h=new Deferred;b=this.fs_.getHereData();var k=this;if(b&&b.id){d=function(b){b.action==google.picker.Action.PICKED&&b.docs&&0<b.docs.length&&b.docs[0].id&&k.cons_.execStr("ls -tr -al -f");b.action!=google.picker.Action.PICKED&&b.action!=google.picker.Action.CANCEL||h.callback()};if(!gd_upicker||lastuploadid!=b.id){lastuploadid=b.id;f=gapi.auth.getToken().access_token;g=new google.picker.DocsUploadView;g.setParent(b.id);var l="Upload files";
b.title&&(l='Upload to "'+b.title+'"');gd_upicker=(new google.picker.PickerBuilder).setLocale("en").setOAuthToken(f).setTitle(l).enableFeature(google.picker.Feature.MULTISELECT_ENABLED).addView(g).setDeveloperKey(gd_developerKey).setCallback(d).build()}gd_upicker.setVisible(!0)}else this.out.write("Can not upload to the current folder."),h.callback();return h};
$(window).load(function(){c.installCommand("ls",new commands.Ls(c,fs));c.installCommand("cd",new commands.Cd(c,fs));c.installCommand("mkdir",new commands.Mkdir(c,fs));c.installCommand("mkfile",new commands.Mkfile(c,fs));c.installCommand("rm",new commands.Rm(c,fs));c.installCommand("rename",new commands.Rename(c,fs));c.installCommand("trash",new commands.Trash(c,fs));c.installCommand("trashs",new commands.Trashs(c,fs));c.installCommand("emptytrash",new commands.Emptytrash(c,fs));c.installCommand("find",
new commands.Find(c,fs));c.installCommand("upload",new commands.Upload(c,fs));c.installCommand("clear",new commands.Clear(c));c.installCommand("cat",new commands.Cat(c,fs));c.installCommand("edit",new commands.Edit(c,fs));c.installCommand("gmail",new commands.Gmail(c,fs));c.installCommand("contacts",new commands.Contacts(c,fs));c.installCommand("man",new commands.Man(c));c.installCommand("start",new commands.Start(c));c.installCommand("auth",new commands.Auth(c));c.installCommand("connect",new commands.Connect(c,
fs,a));c.installCommand("call",new commands.Call(c));c.installCommand("dcall",new commands.Dcall(c));c.installCommand("js",new commands.Js(c));c.installCommand("setRoot",new commands.SetRoot(c));c.installCommand("token",new commands.Token(c));c.installCommand("info",new commands.Info(c));c.installCommand("history",new commands.History(c,fs));c.installCommand("help",new commands.Help(c));var b=queryParam("q"),d=queryParam("u"),f="start --i";b&&(f+=" --q");d&&(f+=" --u="+d);g_console_login=function(){c.execStr(f).addCallbacks(function(){c.enableInput(!0)},
function(){c.write("Connection requires popup. Type <b>start</b> to connect.",!0);c.enableInput(!0)})}});
