var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var h=a[e];if(b.call(c,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<e.length-1;h++){var k=e[h];if(!(k in d))return;d=d[k]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
function g_load(a,b,c){b||(b="No Name.sqlite");window._getid&&(_getid("filename").innerHTML="FileName: "+html_entity_encode(b),1==gsqlloadtype&&(_getid("filename2").innerHTML=""));extractFileNameWithoutExt(b);setIsLoading(!0);resetTableList();try{db&&db.close()}catch(d){}setTimeout(function(){try{db=new SQL.Database(new Uint8Array(a));var d=db.prepare("SELECT * FROM sqlite_master WHERE type='table' ORDER BY name")}catch(g){setIsLoading(!1);alert(shortstring(g+"",1500));return}gfilename=b;1==gsqlloadtype?
window._getid&&_getid("fsave")&&!c&&(_getid("fsave").style.display=""):window._getid&&_getid("fsave")&&(_getid("fsave").style.display="");var e=null,h=$("#tables"),k=[],p=0;try{for(;d.step();){p++;if(1E5<p){k.push("Error. Too many table iterations over 100,000 times.");break}try{var f=d.getAsObject().name}catch(g){k.push(g+"");continue}null===e&&(e=f);try{var m=getTableRowsCount(f)}catch(g){k.push("Table Name: "+f+", "+g);continue}rowCounts[f]=m;var n=henc2(f);h.append('<option value="'+n+'">'+n+
" ("+m+" rows)</option>")}}catch(g){k.push(g+"")}0<k.length&&alert(shortstring(k.join("\n"),1500));d.free();h.select2("val",e);doDefaultSelect(e);$("#output-box").fadeIn();$(".nouploadinfo").hide();$("#sample-db-link").hide();$("#dropzone").delay(50).animate({height:50},500);$("#success-box").show();setIsLoading(!1)},50)}
var SQL_FROM_REGEX=/FROM(?:\s+|(?=["'`\[]))("(?:""|[^"])+"|'(?:''|[^'])+'|`(?:``|[^`])+`|\[[^\]]+\]|([^\s\.;]+))/mi,SQL_LIMIT_REGEX=/LIMIT\s+(\d+)(?:\s*,\s*(\d+))?/mi,SQL_SELECT_REGEX=/SELECT\s+[^;]+\s+FROM\s+/mi,db=null,rowCounts=[],editor=ace.edit("sql-editor"),bottomBarDefaultPos=null,bottomBarDisplayStyle=null,errorBox=$("#error"),lastCachedQueryCount={},gfilename,garraybuffers=[],garraybloburl,glastext,glasttablename;function get_safe_name(a){return a.replace(/"/g,'""')}
function get_number_format(a,b,c,d){a=(a+"").replace(/[^0-9+\-Ee.]/g,"");a=isFinite(+a)?+a:0;b=isFinite(+b)?Math.abs(b):0;d="undefined"===typeof d?",":d;c="undefined"===typeof c?".":c;var e="";e=function(h,k){k=Math.pow(10,k);return""+Math.round(h*k)/k};e=(b?e(a,b):""+Math.round(a)).split(".");3<e[0].length&&(e[0]=e[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,d));(e[1]||"").length<b&&(e[1]=e[1]||"",e[1]+=Array(b-e[1].length+1).join("0"));return e.join(c)}
var selectFormatter=function(a){var b=a.text.lastIndexOf("(");return-1<b?a.text.substring(0,b)+"<span>"+a.text.substring(b-1)+"</span>":a.text},windowResize=function(){positionFooter();var a=$("#main-container");a=a.offset().left+a.outerWidth();$("#bottom-bar").css("left",a)},positionFooter=function(){var a=$("#bottom-bar"),b=a.find("#pager"),c=$("#main-container").height(),d=$(window).scrollTop()+$(window).height();null===bottomBarDefaultPos&&(bottomBarDefaultPos=a.css("position"));null===bottomBarDisplayStyle&&
(bottomBarDisplayStyle=b.css("display"));d>c?(a.css({position:"static"}),b.css("display","inline-block")):(a.css({position:bottomBarDefaultPos}),b.css("display",bottomBarDisplayStyle))};"undefined"===typeof FileReader?($("#dropzone, #dropzone-dialog").hide(),$("#compat-error").show()):$("#dropzone, #dropzone-dialog").fileReaderJS(fileReaderOpts);editor.setTheme("ace/theme/chrome");editor.renderer.setShowGutter(!1);editor.renderer.setShowPrintMargin(!1);editor.renderer.setPadding(20);editor.setHighlightActiveLine(!1);
editor.getSession().setUseWrapMode(!0);editor.getSession().setMode("ace/mode/sql");editor.setOptions({maxLines:5,minLines:2,fontSize:"11pt"});editor.container.style.lineHeight=1.3;editor.$blockScrolling=Infinity;$(window).resize(windowResize).scroll(positionFooter);windowResize();$(".no-propagate").on("click",function(a){a.stopPropagation()});
function getTableRowsCount(a){a=db.prepare('SELECT COUNT(*) AS count FROM "'+get_safe_name(a)+'"');if(a.step()){var b=a.getAsObject().count;a.free();return b}a.free();return-1}
function getQueryRowCount(a){if(a===lastCachedQueryCount.select)return lastCachedQueryCount.count;var b=a.replace(SQL_SELECT_REGEX,"SELECT COUNT(*) AS count_sv FROM ");if(b!==a){b=b.replace(SQL_LIMIT_REGEX,"");b=db.prepare(b);if(b.step()){var c=b.getAsObject().count_sv;lastCachedQueryCount.select=a;lastCachedQueryCount.count=c;b.free();return c}b.free()}return-1}
function getTableColumnTypes(a){var b=[];for(a=db.prepare('PRAGMA table_info("'+get_safe_name(a)+'")');a.step();){var c=a.getAsObject();b[c.name]=c.type}a.free();return b}function resetTableList(){var a=$("#tables");rowCounts=[];a.empty();a.append("<option></option>");a.select2({placeholder:"Select a table",formatSelection:selectFormatter,formatResult:selectFormatter});a.on("change",function(b){doDefaultSelect(b.val)})}
function setIsLoading(a){var b=$("#drop-text"),c=$("#drop-loading");a?(b.hide(),c.show()):(b.show(),c.hide())}function extractFileNameWithoutExt(a){var b=a.lastIndexOf(".");return-1<b?a.substr(0,b):a}function dropzoneClick(){$("#dropzone-dialog").click()}function doDefaultSelect(a){glasttablename=a;a='SELECT * FROM "'+get_safe_name(a)+'" LIMIT 0,30';editor.setValue(a,-1);renderQuery2(a)}var gshowed;
function executeSql(a,b){b?a=b:(a=editor.getSelectedText())||(a=editor.getValue());renderQuery2(a);$("#tables").select2("val",getTableNameFromQuery(a));gshowed||(gshowed=!0)}function getTableNameFromQuery(a){a=SQL_FROM_REGEX.exec(a);if(null!=a&&a[1]){var b=a[1],c={'"':'"',"'":"'","`":"`","[":"]"};a=b[0];var d=b[b.length-1];c[a]&&c[a]===d?(b=b.slice(1,-1),"'"==a?b=b.replace(/''/g,"'"):'"'==a?b=b.replace(/""/g,'"'):"`"==a&&(b=b.replace(/``/g,"`")),a=b):a=b;return a}return null}
function parseLimitFromQuery(a,b){var c=SQL_LIMIT_REGEX.exec(a);if(null!=c){var d={};2<c.length&&"undefined"!==typeof c[2]?(d.offset=parseInt(c[1]),d.max=parseInt(c[2])):(d.offset=0,d.max=parseInt(c[1]));if(0==d.max)return d.pages=0,d.currentPage=0,d;"undefined"===typeof b&&getTableNameFromQuery(a);a=getQueryRowCount(a);-1!=a&&(d.pages=Math.ceil(a/d.max));d.currentPage=Math.floor(d.offset/d.max)+1;d.rowCount=a;return d}return null}
function setPage(a,b){if(!$(a).hasClass("disabled")){var c=a=editor.getSelectedText();c||(c=editor.getValue());try{var d=parseLimitFromQuery(c)}catch(e){showError(e);return}if(d){if("undefined"!==typeof b)b=b?d.currentPage:d.currentPage-2;else if(b=prompt("Go to page"),!isNaN(b)&&1<=b&&b<=d.pages)--b;else return;d=c.replace(SQL_LIMIT_REGEX,"LIMIT "+b*d.max+","+d.max);a?(a=editor.selection.getRange())&&a.end&&(c=editor.session.replace(a,d))&&(a.end.column=c.column,editor.selection.setRange(a)):editor.setValue(d,
-1);executeSql("",d)}else showError('No found "limit" value in a SQL query. '+c)}}
function refreshPagination(a,b){try{var c=parseLimitFromQuery(a,b)}catch(d){showError(d);return}null!==c&&0<c.pages?(a=$("#pager"),a.attr("title","Row count: "+c.rowCount),a.tooltip("fixTitle"),a.text(c.currentPage+" / "+c.pages),1>=c.currentPage?$("#page-prev").addClass("disabled"):$("#page-prev").removeClass("disabled"),c.currentPage+1>c.pages?$("#page-next").addClass("disabled"):$("#page-next").removeClass("disabled"),$("#bottom-bar").show()):$("#bottom-bar").hide()}
function showError(a){$("#data").hide();$("#bottom-bar").hide();errorBox.show();errorBox.text(a)}
function get_file_checktype(a){try{var b=function(d,e){e||(e={});e.offset||(e.offset=0);for(var h=0;h<=d.length-1;h++)if(a[h+e.offset]!=d[h])return;return!0},c="";b([37,80,68,70])?c="pdf":b([255,216,255])?c="jpg":b([137,80,78,71,13,10,26,10])?c="png":b([66,77])?c="bmp":b([71,73,70])?c="gif":b([87,69,66,80],{offset:8})&&(c="webp");if(c)return c;if(b([80,75])&&(3===a[2]||5===a[2]||7===a[2])&&(4===a[3]||6===a[3]||8===a[3]))return"zip";if(b([82,97,114,33,26,7])&&(0===a[6]||1===a[6]))return"rar";if(b([31,
139,8]))return"gz";if(b([66,90,104]))return"bz2";if(b([55,122,188,175,39,28]))return"7z"}catch(d){}}
function renderQuery2(a){function b(t){try{for(var v=t.length/2,w=new Uint8Array(v),u=0;u<v;u++)w[u]=parseInt(t.substr(2*u,2),16);return get_file_checktype(w)}catch(A){}}glastext="";var c=$("#data"),d=c.find("thead").find("tr"),e=c.find("tbody");d.empty();e.empty();errorBox.hide();c.show();var h=[],k=getTableNameFromQuery(a);try{null!=k&&(h=getTableColumnTypes(k));var p=db.prepare(a)}catch(t){showError(t);return}var f=!1;garraybuffers=[];for(var m=0,n,g,q,x=0,r,y=0,z=/^[0-9a-f]+$/i;p.step();){if(!f){f=
!0;n=p.getColumnNames();for(var l=0;l<n.length;l++)d.append('<th><span data-toggle="tooltip" data-placement="top" title="'+h[n[l]]+'">'+henc2(n[l],100)+"</span></th>")}n=$("<tr>");g=p.get();q="";for(l=0;l<g.length;l++)g[l]&&void 0!==g[l].byteLength?(200>y?(r=get_file_checktype(g[l]),y++):r="",garraybuffers.push({type:0,data:g[l],ext:r}),q='[ArrayBuffer]&nbsp;&nbsp;<a href="#" onclick="proc_ab_save(this,'+(garraybuffers.length-1)+');return false">Save</a>',n.append('<td noeditor="1"><span title="Size: '+
get_number_format(g[l].byteLength)+'">'+q+"</span></td>")):(q=!1,100>x&&g[l]&&g[l].length&&1024<g[l].length&&1048576>g[l].length&&0==g[l].length%2&&(x++,("string"===typeof g[l]||g[l]instanceof String)&&z.test(g[l])&&(r=b(g[l].substr(0,100))))&&(garraybuffers.push({type:1,data:g[l],ext:r}),q=henc2(g[l],262144,"...more"),n.append('<td><a href="#" title="Size: '+get_number_format(g[l].length)+'" onclick="proc_ab_save(this,'+(garraybuffers.length-1)+');return false">Save</a> <span title="'+q+'">'+q+"</span></td>"),
q=!0),q||(q=henc2(g[l],262144,"...more"),n.append('<td><span title="'+q+'">'+q+"</span></td>")));e.append(n);m++;if(1E3<m)break}p.free();refreshPagination(a,k);$('[data-toggle="tooltip"]').tooltip({html:!0});c.editableTableWidget2();setTimeout(function(){positionFooter()},100)}function henc2(a,b,c){return a&&("string"===typeof a||a instanceof String)?(b&&a.length>b&&a.substr&&(a=a.substr(0,b)+(c||"...")),henc(a)):a}
function proc_ab_save(a,b){try{if(garraybuffers[b]){if(0==garraybuffers[b].type){if(0==garraybuffers[b].data.byteLength){alert("Data size is zero.");return}}else if(1==garraybuffers[b].type&&0==garraybuffers[b].data.length){alert("Data size is zero.");return}if(window.URL){a=glastext;if(!a){a=garraybuffers[b].ext||localStorage.c_lastext||"bin";a=prompt("Please enter the extension of the file type to be saved.\nex)jpg, png, ico, gif, pdf, doc...\n(Selected value will keep until the table/query is changed)",
a);if(null==a)return;a||(a="bin");a=a.toLowerCase();glastext=localStorage.c_lastext=a}if(1==garraybuffers[b].type){for(var c=garraybuffers[b].data,d=c.length/2,e=new Uint8Array(d),h=0;h<d;h++)e[h]=parseInt(c.substr(2*h,2),16);var k=new Blob([e])}else k=new Blob([garraybuffers[b].data]);var p="Dump_"+k.size+"_"+(b+1)+"."+a;glasttablename&&(p=glasttablename.replace(/[\\\\/:?*"|<>]/g,"-")+"_"+p);var f=_getid("downlink");f||(f=document.createElement("A"),f.id="downlink",document.body.appendChild(f));
navigator.msSaveBlob?navigator.msSaveBlob(k,p):window.URL?(f.download=p,garraybloburl&&window.URL.revokeObjectURL(garraybloburl),garraybloburl=window.URL.createObjectURL(k),issafari?window.open(garraybloburl):(f.target="_blank",f.href=garraybloburl,f.click())):alert("This browser does not support.")}else alert("This browser does not support.")}else alert("No found data.")}catch(m){alert(m+"")}}
$.fn.editableTableWidget2=function(a){return $(this).each(function(){var b=$.extend(function(){var f=$.extend({},$.fn.editableTableWidget2.defaultOptions);f.editor=f.editor.clone();return f}(),a),c=$(this),d=b.editor.css("position","absolute").hide().appendTo(c.parent()),e,h=function(f){e=c.find("td:focus");if(e.length&&"1"!=e.attr("noeditor")){var m=e.height(),n=e.width(),g=e;g.outerWidth()<g[0].scrollWidth&&(m*=2,n=Math.max(n,250));d.val(e.text()).removeClass("error").show().offset(e.offset()).css(e.css(b.cloneProperties)).width(n).height(m).focus();
f&&d.select()}},k=function(){var f=d.val(),m=$.Event("change");if(e.text()===f||d.hasClass("error"))return!0;var n=e.html();e.text(f).trigger(m,f);!1===m.result&&e.html(n)},p=function(f,m){return 39===m?f.next("td"):37===m?f.prev("td"):38===m?f.parent().prev().children().eq(f.index()):40===m?f.parent().next().children().eq(f.index()):[]};d.blur(function(){k();d.hide()}).keydown(function(f){if(13===f.which)k(),d.hide(),e.focus(),f.preventDefault(),f.stopPropagation();else if(27===f.which)d.val(e.text()),
f.preventDefault(),f.stopPropagation(),d.hide(),e.focus();else if(9===f.which)e.focus();else if(this.selectionEnd-this.selectionStart===this.value.length){var m=p(e,f.which);0<m.length&&(m.focus(),f.preventDefault(),f.stopPropagation())}}).on("input paste",function(){var f=$.Event("validate");e.trigger(f,d.val());!1===f.result?d.addClass("error"):d.removeClass("error")});c.on("click keypress dblclick",h).keydown(function(f){var m=!0,n=p($(f.target),f.which);0<n.length?n.focus():13===f.which?h(!1):
(17!==f.which&&91!==f.which&&93!==f.which||h(!0),m=!1);m&&(f.stopPropagation(),f.preventDefault())});c.find("td").prop("tabindex",1);$(window).on("resize",function(){d.is(":visible")&&d.offset(e.offset()).width(e.width()).height(e.height())})})};$.fn.editableTableWidget2.defaultOptions={cloneProperties:"padding padding-top padding-bottom padding-left padding-right text-align font font-size font-family font-weight border border-top border-bottom border-left border-right".split(" "),editor:$("<textarea readonly>")};
